package cn.iocoder.yudao.module.dcc.signature.service.retention;

public enum SignatureGovernanceRetentionBlockerCode {

    ENDPOINT_MISSING,
    BUCKET_MISSING,
    OBJECT_LOCK_MISSING,
    VERSIONING_MISSING,
    DEFAULT_RETENTION_MISSING,
    RETENTION_VERIFICATION_SOURCE_MISSING,
    RETENTION_MODE_MISSING,
    PERMISSION_MISSING,
    OWNER_MISSING,
    OWNER_REVIEW_MISSING,
    SAMPLE_DCC_SIGNATURE_MISSING,
    SAMPLE_EDHR_ARCHIVE_MISSING,
    RECOVERY_RUNTIME_MISSING,
    BACKUP_ID_MISSING,
    OBJECT_KEY_MISSING,
    VERSION_ID_MISSING,
    RETENTION_OBJECT_MISSING,
    RETENTION_METADATA_MISSING,
    RETENTION_VERIFICATION_FAILED,
    RETAIN_UNTIL_MISSING,
    SHA256_MISSING,
    DCC_EVIDENCE_HASH_MISSING,
    EDHR_ARCHIVE_HASH_MISSING,
    SIGNATURE_HASH_MISSING,
    SOURCE_TYPE_MISMATCH,
    HASH_MISMATCH,
    REPORT_WRITE_FAILED,
    AUDIT_EVENT_MISSING,
    AUDIT_WRITE_FAILED
}
