import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import software.amazon.awssdk.awscore.exception.AwsErrorDetails;
import software.amazon.awssdk.http.*;
import software.amazon.awssdk.services.s3.model.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

final class G26ReadOnlyBucketProbeTest {
    static int tests;
    static void check(boolean ok,String why){if(!ok)throw new AssertionError(why);}
    static void scenario(boolean ok,String why){check(ok,why);tests++;}
    static ObjectNode input(){var root=G26ExactObjectRecovery.JSON.createObjectNode();var c=root.putObject("config");c.put("configId","28");c.put("storage",20);c.put("endpoint","http://127.0.0.1:9000");c.put("bucket","offline-bucket");c.put("region","us-east-1");c.put("accessKey","OFFLINE_FAKE_KEY");c.put("accessSecret","OFFLINE_FAKE_SECRET");c.put("pathStyle",true);return root;}
    static String bucketSha()throws Exception{return G26ExactObjectRecovery.hash("offline-bucket".getBytes(StandardCharsets.UTF_8));}
    static class Probe implements G26ReadOnlyBucketProbe.Probe {
        int versionGets,lockGets,closed;S3Exception versionError,lockError;boolean missingRule;
        public GetBucketVersioningResponse versioning(GetBucketVersioningRequest req){versionGets++;check(req.bucket().equals("offline-bucket"),"exact bucket");if(versionError!=null)throw versionError;return(GetBucketVersioningResponse)GetBucketVersioningResponse.builder().status(BucketVersioningStatus.ENABLED).sdkHttpResponse(SdkHttpResponse.builder().statusCode(200).build()).build();}
        public GetObjectLockConfigurationResponse lock(GetObjectLockConfigurationRequest req){lockGets++;check(req.bucket().equals("offline-bucket"),"exact bucket");if(lockError!=null)throw lockError;var config=ObjectLockConfiguration.builder().objectLockEnabled(ObjectLockEnabled.ENABLED);if(!missingRule)config.rule(ObjectLockRule.builder().defaultRetention(DefaultRetention.builder().mode(ObjectLockRetentionMode.COMPLIANCE).days(7).build()).build());return(GetObjectLockConfigurationResponse)GetObjectLockConfigurationResponse.builder().objectLockConfiguration(config.build()).sdkHttpResponse(SdkHttpResponse.builder().statusCode(200).build()).build();}
        public void close(){closed++;}
    }
    record Run(int exit,String output,int factories){}
    static Run run(byte[] raw,Probe p)throws Exception{AtomicInteger factories=new AtomicInteger();var out=new ByteArrayOutputStream();int code=G26ReadOnlyBucketProbe.run(new ByteArrayInputStream(raw),out,c->{factories.incrementAndGet();return p;},bucketSha());String text=out.toString(StandardCharsets.UTF_8);for(String s:List.of("OFFLINE_FAKE","SECRET_IN_EXCEPTION","offline-bucket","http://"))check(!text.contains(s),"no secret/name/url output");JsonNode row=G26ExactObjectRecovery.JSON.readTree(text);Set<String> fields=new HashSet<>();row.fieldNames().forEachRemaining(fields::add);check(fields.equals(Set.of("bucketSha256","status","versioningStatus","mfaDeleteStatus","versioningHttpStatus","versioningErrorCode","objectLockStatus","retentionMode","retentionDays","retentionYears","objectLockHttpStatus","objectLockErrorCode","lifecycleErrorCode")),"exact sanitized fields");return new Run(code,text,factories.get());}
    static Run run(ObjectNode n,Probe p)throws Exception{return run(G26ExactObjectRecovery.JSON.writeValueAsBytes(n),p);}
    static void invalid(ObjectNode n)throws Exception{Probe p=new Probe();Run r=run(n,p);scenario(r.exit==2&&r.factories==0&&p.versionGets==0&&p.lockGets==0,"invalid input no client");}
    static S3Exception error(int http,String code){return(S3Exception)S3Exception.builder().statusCode(http).message("SECRET_IN_EXCEPTION").awsErrorDetails(AwsErrorDetails.builder().errorCode(code).build()).build();}
    public static void main(String[] args)throws Exception{
        G26ExactObjectRecovery.muteSdkLogs();Probe p=new Probe();Run r=run(input(),p);scenario(r.exit==0&&p.versionGets==1&&p.lockGets==1&&p.closed==1&&r.output.contains("COMPLIANCE")&&r.output.contains("retentionDays\":7"),"two exact reads record actual policy");
        p=new Probe();p.missingRule=true;r=run(input(),p);scenario(r.exit==0&&r.output.contains("retentionDays\":null")&&r.output.contains("retentionMode\":null"),"no default retention remains null");
        p=new Probe();p.lockError=error(404,"ObjectLockConfigurationNotFoundError");r=run(input(),p);scenario(r.exit==0&&r.output.contains("NOT_CONFIGURED")&&r.output.contains("404"),"actual not-configured absence is explicit");
        for(S3Exception e:List.of(error(403,"AccessDenied"),error(404,"NoSuchBucket"),error(500,"InternalError"),error(400,"SECRET_IN_EXCEPTION"))){p=new Probe();p.lockError=e;r=run(input(),p);scenario(r.exit==1&&r.output.contains("PROBE_FAILED"),"unknown/error policy never guessed");}
        p=new Probe();p.versionError=error(403,"AccessDenied");r=run(input(),p);scenario(r.exit==1&&p.lockGets==1,"both independent readonly facts captured even one denies");
        p=new Probe(){public void close(){throw new IllegalStateException("SECRET_IN_EXCEPTION");}};r=run(input(),p);scenario(r.exit==1&&r.output.contains("CLIENT_LIFECYCLE_ERROR"),"close failure actual error no success");
        for(String endpoint:List.of("http://example.com:9000","http://u:p@localhost:9000","http://127.0.0.1:9001","http://127.0.0.1:9000/path","http://127.0.0.1:9000/?x=1")){var n=input();((ObjectNode)n.get("config")).put("endpoint",endpoint);invalid(n);}
        var n=input();((ObjectNode)n.get("config")).put("bucket","different-bucket");invalid(n);n=input();((ObjectNode)n.get("config")).put("region","another-region");invalid(n);n=input();((ObjectNode)n.get("config")).put("storage",19);invalid(n);n=input();((ObjectNode)n.get("config")).put("configId","29");invalid(n);n=input();((ObjectNode)n.get("config")).put("pathStyle",false);invalid(n);n=input();n.put("operation","DeleteBucket");invalid(n);
        for(String raw:List.of("{\"config\":{},\"config\":{}}",G26ExactObjectRecovery.JSON.writeValueAsString(input())+" {}","SECRET_IN_EXCEPTION")){p=new Probe();r=run(raw.getBytes(StandardCharsets.UTF_8),p);scenario(r.exit==2&&r.factories==0,"strict JSON no client");}
        var c=G26ReadOnlyBucketProbe.parse(new ByteArrayInputStream(G26ExactObjectRecovery.JSON.writeValueAsBytes(input())),bucketSha());var valid=SdkHttpRequest.builder().protocol("http").host("127.0.0.1").port(9000).method(SdkHttpMethod.GET).encodedPath("/offline-bucket").putRawQueryParameter("versioning","").build();G26ReadOnlyBucketProbe.guard(c,valid);tests++;
        for(var bad:List.of(valid.toBuilder().method(SdkHttpMethod.PUT).build(),valid.toBuilder().encodedPath("/offline-bucket/object").build(),valid.toBuilder().host("remote.example").build(),valid.toBuilder().port(80).build(),valid.toBuilder().putRawQueryParameter("versioning","anything").build(),valid.toBuilder().putRawQueryParameter("object-lock","").build(),valid.toBuilder().removeQueryParameter("versioning").putRawQueryParameter("uploads","").build())){boolean refused=false;try{G26ReadOnlyBucketProbe.guard(c,bad);}catch(software.amazon.awssdk.core.exception.SdkClientException expected){refused=true;}scenario(refused,"only exact two readonly bucket requests");}
        AtomicInteger requests=new AtomicInteger();var transport=new SdkHttpClient(){public ExecutableHttpRequest prepareRequest(HttpExecuteRequest req){requests.incrementAndGet();var q=req.httpRequest();check(q.method()==SdkHttpMethod.GET&&q.encodedPath().equals("/offline-bucket")&&q.host().equals("127.0.0.1")&&q.port()==9000,"actual SDK exact bucket GET");boolean version=q.rawQueryParameters().keySet().equals(Set.of("versioning"));boolean lock=q.rawQueryParameters().keySet().equals(Set.of("object-lock"));check(version||lock,"only actual versioning/lock query");String xml=version?"<VersioningConfiguration xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Status>Enabled</Status></VersioningConfiguration>":"<ObjectLockConfiguration xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><ObjectLockEnabled>Enabled</ObjectLockEnabled><Rule><DefaultRetention><Mode>COMPLIANCE</Mode><Days>7</Days></DefaultRetention></Rule></ObjectLockConfiguration>";return new ExecutableHttpRequest(){public HttpExecuteResponse call(){return HttpExecuteResponse.builder().response(SdkHttpResponse.builder().statusCode(200).putHeader("Content-Type","application/xml").build()).responseBody(AbortableInputStream.create(new ByteArrayInputStream(xml.getBytes(StandardCharsets.UTF_8)))).build();}public void abort(){}};}public void close(){}};
        try(var actual=G26ReadOnlyBucketProbe.createAws(c,transport)){scenario(actual.versioning(GetBucketVersioningRequest.builder().bucket(c.bucket()).build()).status()==BucketVersioningStatus.ENABLED,"real SDK versioning response unmarshalling");scenario(actual.lock(GetObjectLockConfigurationRequest.builder().bucket(c.bucket()).build()).objectLockConfiguration().rule().defaultRetention().days()==7,"real SDK lock response unmarshalling");}scenario(requests.get()==2,"two offline serialized readonly calls no network");
        System.out.println("PASS "+tests+" bucket probe offline cases; real GET=0 PUT=0 DB=0");
    }
}
