-- READ ONLY preparation; execute only Root fresh source verification, never business mutations.
SELECT DATABASE() AS actual_database,@@server_uuid AS actual_uuid,@@version AS mysql_version,@@session.sql_mode AS sql_mode,@@session.time_zone AS time_zone,@@character_set_connection AS connection_charset,@@collation_connection AS connection_collation;
SELECT TABLE_NAME,ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('gxp_audit_policy_operation','gxp_audit_policy_version','system_users','system_role','system_user_role');
SELECT TABLE_NAME,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT,EXTRA,COLLATION_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('gxp_audit_policy_operation','gxp_audit_policy_version','system_users','system_role','system_user_role') ORDER BY TABLE_NAME,ORDINAL_POSITION;
SELECT TABLE_NAME,INDEX_NAME,NON_UNIQUE,SEQ_IN_INDEX,COLUMN_NAME,SUB_PART FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('gxp_audit_policy_operation','gxp_audit_policy_version') ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX;
SELECT * FROM gxp_audit_policy_operation ORDER BY tenant_id,operation_id,policy_version,id;
SELECT * FROM gxp_audit_policy_version ORDER BY tenant_id,policy_version,id;
SELECT u.id,u.tenant_id,u.username,u.nickname,u.status,HEX(u.deleted) AS deleted_hex,r.id AS role_id,r.code AS role_code,r.status AS role_status,HEX(r.deleted) AS role_deleted FROM system_users u LEFT JOIN system_user_role ur ON ur.user_id=u.id AND ur.tenant_id=u.tenant_id AND ur.deleted=b'0' LEFT JOIN system_role r ON r.id=ur.role_id AND r.tenant_id=u.tenant_id WHERE u.tenant_id=1 AND u.id=@dcc_gxp26_quality_approved_by;
SELECT ROUTINE_NAME,ROUTINE_TYPE,DEFINER,CREATED,LAST_ALTERED,SQL_MODE,ROUTINE_DEFINITION FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA=DATABASE() AND ROUTINE_NAME IN ('dcc_gxp26_tenant1_config','dcc_gxp26_tenant1_quality');
-- Root compares every preserved row/column/metadata against frozen preflight; no query returns secrets.
SELECT COUNT(*) AS exact26_namespace_rows FROM gxp_audit_policy_operation WHERE tenant_id=1 AND operation_id IN ('dcc.controlled-file.activate','dcc.controlled-file.auto-obsolete','dcc.controlled-file.control','dcc.controlled-file.legacy-name-occupancy.activate','dcc.controlled-file.obsolete','dcc.folder-template.delete','dcc.folder-template.save','dcc.project-attributes.configure','dcc.project-file-placement.bind','dcc.project-folder.create','dcc.project-folder.delete','dcc.project-folder.update','dcc.project-product.approve','dcc.project-product.complete','dcc.project-product.create','dcc.project-product.resubmit','dcc.project-product.retry','dcc.project-product.review','dcc.project-product.reviewer-config','dcc.project-product.write-failed','dcc.project-reference.cancel','dcc.project-reference.create','dcc.relation.arrange','dcc.relation.controlled','dcc.relation.notification.retry','dcc.relation.replace');
