-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=20260729_dcc_product_catalog_remove_subsidiary_source; type=schema; riskLevel=medium
-- F1: MES process pool foundation. This creates dedicated process-pool tables and does not reuse mes_pro_feedback_surplus_pool.

CREATE TABLE IF NOT EXISTS `mes_pro_process_pool` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工序池ID',
    `work_order_id` bigint NOT NULL COMMENT '生产工单ID',
    `route_id` bigint NOT NULL COMMENT '工艺路线ID',
    `route_process_id` bigint NOT NULL COMMENT '路线工序ID',
    `process_id` bigint NOT NULL COMMENT '工序ID',
    `device_id` bigint NOT NULL COMMENT '设备ID',
    `workstation_id` bigint NOT NULL COMMENT '工作站ID',
    `pool_status` varchar(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '工序池状态',
    `latest_event_id` bigint DEFAULT NULL COMMENT '最近提交事件ID',
    `latest_submit_time` datetime DEFAULT NULL COMMENT '最近服务端提交时间',
    `total_event_count` int NOT NULL DEFAULT 0 COMMENT '提交事件数量',
    `last_actual_employee_id` bigint DEFAULT NULL COMMENT '最近实际员工ID',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_mes_pro_process_pool_context` (`tenant_id`, `work_order_id`, `route_id`, `route_process_id`, `process_id`, `device_id`, `workstation_id`, `deleted`),
    KEY `idx_mes_pro_process_pool_latest_time` (`tenant_id`, `latest_submit_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 工序池';

CREATE TABLE IF NOT EXISTS `mes_pro_process_pool_event` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工序池提交事件ID',
    `pool_id` bigint NOT NULL COMMENT '工序池ID',
    `event_type` varchar(64) NOT NULL COMMENT '提交事件类型',
    `work_order_id` bigint NOT NULL COMMENT '生产工单ID',
    `route_id` bigint NOT NULL COMMENT '工艺路线ID',
    `route_process_id` bigint NOT NULL COMMENT '路线工序ID',
    `process_id` bigint NOT NULL COMMENT '工序ID',
    `actual_employee_id` bigint NOT NULL COMMENT '实际员工ID',
    `device_account_id` bigint NOT NULL COMMENT '设备账号ID',
    `device_id` bigint NOT NULL COMMENT '设备ID',
    `workstation_id` bigint NOT NULL COMMENT '工作站ID',
    `template_type` varchar(64) NOT NULL COMMENT '模板类型',
    `feedback_source_type` varchar(64) NOT NULL COMMENT '报工来源类型',
    `feedback_source_id` bigint NOT NULL COMMENT '报工来源ID',
    `recordbook_source_type` varchar(64) NOT NULL COMMENT '记录本来源类型',
    `recordbook_source_id` bigint NOT NULL COMMENT '记录本来源ID',
    `raw_payload` json NOT NULL COMMENT '原始 payload',
    `server_submit_time` datetime NOT NULL COMMENT '服务端提交时间',
    `signature_id` bigint NOT NULL COMMENT '电子签名ID',
    `signature_user_id` bigint NOT NULL COMMENT '电子签名用户ID',
    `signature_snapshot` json DEFAULT NULL COMMENT '电子签名快照',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_mes_pro_process_pool_event_signature` (`tenant_id`, `signature_id`, `deleted`),
    KEY `idx_mes_pro_process_pool_event_pool` (`tenant_id`, `pool_id`),
    KEY `idx_mes_pro_process_pool_event_context` (`tenant_id`, `work_order_id`, `route_id`, `route_process_id`, `process_id`),
    KEY `idx_mes_pro_process_pool_event_time` (`tenant_id`, `server_submit_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 工序池提交事件';

CREATE TABLE IF NOT EXISTS `mes_pro_process_pool_quantity_fragment` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '数量片段ID',
    `pool_id` bigint NOT NULL COMMENT '工序池ID',
    `event_id` bigint NOT NULL COMMENT '工序池提交事件ID',
    `work_order_id` bigint NOT NULL COMMENT '生产工单ID',
    `route_id` bigint NOT NULL COMMENT '工艺路线ID',
    `route_process_id` bigint NOT NULL COMMENT '路线工序ID',
    `process_id` bigint NOT NULL COMMENT '工序ID',
    `source_quantity_type` varchar(64) NOT NULL COMMENT '来源数量类型',
    `quality_status` varchar(64) DEFAULT NULL COMMENT '质量状态',
    `total_quantity` decimal(24,6) NOT NULL COMMENT '总数量',
    `allocated_quantity` decimal(24,6) NOT NULL DEFAULT 0 COMMENT '已分配数量',
    `available_quantity` decimal(24,6) NOT NULL DEFAULT 0 COMMENT '可用数量',
    `allocation_status` varchar(32) NOT NULL DEFAULT 'AVAILABLE' COMMENT '分配状态',
    `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否锁定',
    `raw_payload` json DEFAULT NULL COMMENT '数量片段原始 payload',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_mes_pro_process_pool_fragment_event` (`tenant_id`, `event_id`),
    KEY `idx_mes_pro_process_pool_fragment_pool` (`tenant_id`, `pool_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 工序池数量片段';

CREATE TABLE IF NOT EXISTS `mes_pro_process_pool_pqc_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'PQC 工序池过程检验记录ID',
    `pool_id` bigint NOT NULL COMMENT '工序池ID',
    `event_id` bigint NOT NULL COMMENT '工序池提交事件ID',
    `work_order_id` bigint NOT NULL COMMENT '生产工单ID',
    `route_id` bigint NOT NULL COMMENT '工艺路线ID',
    `route_process_id` bigint NOT NULL COMMENT '路线工序ID',
    `process_id` bigint NOT NULL COMMENT '工序ID',
    `actual_employee_id` bigint NOT NULL COMMENT '实际员工ID',
    `signature_id` bigint NOT NULL COMMENT '电子签名ID',
    `signature_user_id` bigint NOT NULL COMMENT '电子签名用户ID',
    `inspection_result` varchar(32) NOT NULL COMMENT '过程检验结果',
    `server_submit_time` datetime NOT NULL COMMENT '服务端提交时间',
    `raw_payload` json NOT NULL COMMENT 'PQC 原始 payload',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_mes_pro_process_pool_pqc_event` (`tenant_id`, `event_id`, `deleted`),
    KEY `idx_mes_pro_process_pool_pqc_event` (`tenant_id`, `event_id`),
    KEY `idx_mes_pro_process_pool_pqc_pool` (`tenant_id`, `pool_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 工序池 PQC 过程检验记录';
