-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=; type=schema; riskLevel=medium
CREATE TABLE IF NOT EXISTS `mes_kingdee_bom_list` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `source_form_id` varchar(64) NOT NULL DEFAULT 'ENG_BOM' COMMENT 'ERP来源表单标识',
  `source_fid` varchar(64) NOT NULL COMMENT 'ERP BOM内码',
  `source_line_key` varchar(255) NOT NULL COMMENT 'ERP BOM行唯一键',
  `bom_number` varchar(64) NOT NULL COMMENT 'BOM编号/版本',
  `bom_type` varchar(64) DEFAULT NULL COMMENT 'BOM类型',
  `document_status` varchar(64) DEFAULT NULL COMMENT '审核状态',
  `parent_material_code` varchar(64) NOT NULL COMMENT '父项物料编码',
  `parent_material_name` varchar(255) DEFAULT NULL COMMENT '父项物料名称',
  `parent_material_specification` varchar(512) DEFAULT NULL COMMENT '父项规格型号',
  `parent_quantity` decimal(24,6) DEFAULT NULL COMMENT '父项数量',
  `line_no` int DEFAULT NULL COMMENT '子项行号',
  `child_material_code` varchar(64) NOT NULL COMMENT '子项物料编码',
  `child_material_name` varchar(255) DEFAULT NULL COMMENT '子项物料名称',
  `child_material_specification` varchar(512) DEFAULT NULL COMMENT '子项规格型号',
  `child_unit_name` varchar(64) DEFAULT NULL COMMENT '子项单位',
  `numerator` decimal(24,6) NOT NULL COMMENT '分子',
  `denominator` decimal(24,6) NOT NULL COMMENT '分母',
  `source_modify_time` datetime DEFAULT NULL COMMENT 'ERP来源修改时间',
  `last_sync_time` datetime NOT NULL COMMENT '最后同步时间',
  `raw_payload` longtext DEFAULT NULL COMMENT 'ERP原始载荷快照',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mes_kingdee_bom_list_source` (`tenant_id`, `source_fid`, `source_line_key`),
  KEY `idx_mes_kingdee_bom_list_parent` (`tenant_id`, `parent_material_code`),
  KEY `idx_mes_kingdee_bom_list_child` (`tenant_id`, `child_material_code`),
  KEY `idx_mes_kingdee_bom_list_modify_time` (`tenant_id`, `source_modify_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP物料清单列表同步明细';
