-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=; type=schema; riskLevel=medium
CREATE TABLE IF NOT EXISTS `dcc_nas_acl_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `transfer_task_id` bigint DEFAULT NULL,
  `snapshot_key` char(64) NOT NULL,
  `server` varchar(255) NOT NULL,
  `share` varchar(255) NOT NULL,
  `root_paths_json` longtext NOT NULL,
  `status` varchar(32) NOT NULL,
  `normalization_version` varchar(32) NOT NULL,
  `total_directory_count` bigint NOT NULL DEFAULT 0,
  `snapshotted_directory_count` bigint NOT NULL DEFAULT 0,
  `failed_directory_count` bigint NOT NULL DEFAULT 0,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `failure_code` varchar(64) DEFAULT NULL,
  `failure_message` varchar(1024) DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_nas_acl_snapshot_key` (`tenant_id`, `snapshot_key`),
  KEY `idx_dcc_nas_acl_snapshot_task` (`tenant_id`, `transfer_task_id`, `id`),
  KEY `idx_dcc_nas_acl_snapshot_status` (`tenant_id`, `status`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='NAS ACL snapshot collection';

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_directory_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `snapshot_id` bigint NOT NULL,
  `transfer_task_id` bigint DEFAULT NULL,
  `transfer_task_item_id` bigint DEFAULT NULL,
  `dcc_directory_id` bigint DEFAULT NULL,
  `parent_snapshot_id` bigint DEFAULT NULL,
  `depth` int NOT NULL DEFAULT 0,
  `nas_path` varchar(1024) NOT NULL,
  `path_hash` char(64) NOT NULL,
  `item_name` varchar(255) NOT NULL,
  `descriptor_id` bigint DEFAULT NULL,
  `collect_status` varchar(32) NOT NULL,
  `failure_code` varchar(64) DEFAULT NULL,
  `failure_message` varchar(1024) DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_nas_acl_dir_snapshot_path` (`snapshot_id`, `path_hash`),
  KEY `idx_dcc_nas_acl_dir_snapshot_task_item` (`tenant_id`, `transfer_task_item_id`),
  KEY `idx_dcc_nas_acl_dir_snapshot_dcc_dir` (`tenant_id`, `dcc_directory_id`),
  KEY `idx_dcc_nas_acl_dir_snapshot_descriptor` (`tenant_id`, `descriptor_id`),
  KEY `idx_dcc_nas_acl_dir_snapshot_status` (`tenant_id`, `snapshot_id`, `collect_status`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='NAS ACL directory node snapshot';

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_descriptor` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `descriptor_hash` char(64) NOT NULL,
  `owner_sid` varchar(184) DEFAULT NULL,
  `group_sid` varchar(184) DEFAULT NULL,
  `control_flags` varchar(128) DEFAULT NULL,
  `dacl_present` bit(1) NOT NULL DEFAULT b'0',
  `dacl_protected` bit(1) NOT NULL DEFAULT b'0',
  `sacl_present` bit(1) NOT NULL DEFAULT b'0',
  `raw_descriptor_sha256` char(64) DEFAULT NULL,
  `raw_descriptor_blob` longblob DEFAULT NULL,
  `normalized_descriptor_json` longtext NOT NULL,
  `capture_capability` varchar(32) NOT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_nas_acl_descriptor_hash` (`tenant_id`, `descriptor_hash`),
  KEY `idx_dcc_nas_acl_descriptor_owner` (`tenant_id`, `owner_sid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Deduplicated NAS ACL descriptor';

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_ace` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `descriptor_id` bigint NOT NULL,
  `ace_index` int NOT NULL,
  `ace_hash` char(64) NOT NULL,
  `ace_type` varchar(32) NOT NULL,
  `ace_flags` int DEFAULT NULL,
  `access_mask` bigint NOT NULL,
  `trustee_sid` varchar(184) NOT NULL,
  `trustee_sid_hash` char(64) NOT NULL,
  `inherited` bit(1) NOT NULL DEFAULT b'0',
  `inheritance_flags` varchar(128) DEFAULT NULL,
  `propagation_flags` varchar(128) DEFAULT NULL,
  `object_type_guid` varchar(64) DEFAULT NULL,
  `inherited_object_type_guid` varchar(64) DEFAULT NULL,
  `raw_ace_json` longtext NOT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_nas_acl_ace_order` (`descriptor_id`, `ace_index`),
  KEY `idx_dcc_nas_acl_ace_hash` (`tenant_id`, `ace_hash`),
  KEY `idx_dcc_nas_acl_ace_sid` (`tenant_id`, `trustee_sid_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='NAS ACL ACE detail';

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_identity_mapping` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sid` varchar(184) NOT NULL,
  `sid_hash` char(64) NOT NULL,
  `domain_name` varchar(128) DEFAULT NULL,
  `account_name` varchar(128) DEFAULT NULL,
  `account_display_name` varchar(255) DEFAULT NULL,
  `account_type` varchar(32) NOT NULL,
  `mapping_status` varchar(32) NOT NULL,
  `dcc_subject_type` varchar(32) DEFAULT NULL,
  `dcc_subject_id` bigint DEFAULT NULL,
  `mapping_method` varchar(32) DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `mapped_by_user_id` bigint DEFAULT NULL,
  `block_reason` varchar(512) DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_nas_acl_identity_sid` (`tenant_id`, `sid_hash`),
  KEY `idx_dcc_nas_acl_identity_subject` (`tenant_id`, `dcc_subject_type`, `dcc_subject_id`),
  KEY `idx_dcc_nas_acl_identity_status` (`tenant_id`, `mapping_status`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='NAS SID to DCC subject mapping';

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_restore_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `snapshot_id` bigint NOT NULL,
  `transfer_task_id` bigint DEFAULT NULL,
  `plan_key` char(64) NOT NULL,
  `target_model` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `semantic_policy_version` varchar(64) DEFAULT NULL,
  `identity_mapping_version` varchar(64) DEFAULT NULL,
  `validation_summary_json` longtext DEFAULT NULL,
  `created_by_user_id` bigint NOT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `failure_code` varchar(64) DEFAULT NULL,
  `failure_message` varchar(1024) DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_nas_acl_restore_plan_key` (`tenant_id`, `plan_key`),
  KEY `idx_dcc_nas_acl_restore_plan_snapshot` (`tenant_id`, `snapshot_id`, `id`),
  KEY `idx_dcc_nas_acl_restore_plan_task` (`tenant_id`, `transfer_task_id`, `id`),
  KEY `idx_dcc_nas_acl_restore_plan_status` (`tenant_id`, `status`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='NAS ACL restore plan';

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_restore_plan_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `directory_snapshot_id` bigint NOT NULL,
  `transfer_task_item_id` bigint DEFAULT NULL,
  `dcc_directory_id` bigint DEFAULT NULL,
  `dcc_category_id` bigint DEFAULT NULL,
  `source_descriptor_id` bigint NOT NULL,
  `planned_operations_hash` char(64) DEFAULT NULL,
  `planned_operations_json` longtext DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `block_reason` varchar(1024) DEFAULT NULL,
  `expected_after_hash` varchar(128) DEFAULT NULL,
  `actual_after_hash` varchar(128) DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_nas_acl_restore_item_dir` (`plan_id`, `directory_snapshot_id`),
  KEY `idx_dcc_nas_acl_restore_item_status` (`tenant_id`, `plan_id`, `status`, `id`),
  KEY `idx_dcc_nas_acl_restore_item_dcc_dir` (`tenant_id`, `dcc_directory_id`),
  KEY `idx_dcc_nas_acl_restore_item_descriptor` (`tenant_id`, `source_descriptor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='NAS ACL restore plan item';

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_restore_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `plan_item_id` bigint NOT NULL,
  `attempt_no` int NOT NULL,
  `action_type` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `before_hash` varchar(128) DEFAULT NULL,
  `expected_after_hash` varchar(128) DEFAULT NULL,
  `actual_after_hash` varchar(128) DEFAULT NULL,
  `request_payload_hash` char(64) DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` varchar(1024) DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `operator_user_id` bigint NOT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_nas_acl_restore_log_attempt` (`plan_item_id`, `attempt_no`, `action_type`),
  KEY `idx_dcc_nas_acl_restore_log_plan` (`tenant_id`, `plan_id`, `id`),
  KEY `idx_dcc_nas_acl_restore_log_status` (`tenant_id`, `status`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='NAS ACL restore execution log';

ALTER TABLE `dcc_nas_acl_restore_plan`
  MODIFY COLUMN `semantic_policy_version` varchar(64) DEFAULT NULL,
  MODIFY COLUMN `identity_mapping_version` varchar(64) DEFAULT NULL;

ALTER TABLE `dcc_nas_acl_restore_plan_item`
  MODIFY COLUMN `expected_after_hash` varchar(128) DEFAULT NULL,
  MODIFY COLUMN `actual_after_hash` varchar(128) DEFAULT NULL;

ALTER TABLE `dcc_nas_acl_restore_log`
  MODIFY COLUMN `before_hash` varchar(128) DEFAULT NULL,
  MODIFY COLUMN `expected_after_hash` varchar(128) DEFAULT NULL,
  MODIFY COLUMN `actual_after_hash` varchar(128) DEFAULT NULL;
