CREATE TABLE IF NOT EXISTS `gxp_audit_event` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '审计事件编号',
    `tenant_id` bigint NOT NULL COMMENT '租户编号',
    `operation_id` varchar(128) NOT NULL COMMENT 'GxP 操作登记编号',
    `domain` varchar(64) NOT NULL COMMENT '业务域',
    `subject_type` varchar(64) NOT NULL COMMENT '对象类型',
    `subject_id` varchar(256) NOT NULL COMMENT '对象编号',
    `subject_version` varchar(128) NOT NULL COMMENT '对象版本',
    `action` varchar(64) NOT NULL COMMENT '操作类型',
    `reason` varchar(500) NOT NULL COMMENT '变更原因',
    `actor_id` bigint NOT NULL COMMENT '操作人编号',
    `actor_username` varchar(64) NOT NULL COMMENT '操作人账号',
    `actor_display_name` varchar(128) NOT NULL COMMENT '操作人显示名',
    `server_occurred_at` datetime NOT NULL COMMENT '服务器审计时间',
    `before_state` varchar(32) NOT NULL COMMENT '前状态 ABSENT/PRESENT/VOIDED',
    `before_object_version` varchar(128) NULL COMMENT '前对象版本',
    `before_state_json` longtext NULL COMMENT '前状态规范化 JSON',
    `after_state` varchar(32) NOT NULL COMMENT '后状态 ABSENT/PRESENT/VOIDED',
    `after_object_version` varchar(128) NULL COMMENT '后对象版本',
    `after_state_json` longtext NULL COMMENT '后状态规范化 JSON',
    `policy_version` varchar(128) NOT NULL COMMENT '审计策略版本',
    `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
    `request_id` varchar(128) NULL COMMENT '请求编号',
    `signature_record_id` varchar(128) NULL COMMENT '电子签名记录编号',
    `signature_content_hash` varchar(128) NULL COMMENT '电子签名内容 Hash',
    `canonical_event_json` longtext NOT NULL COMMENT '规范化审计事件 JSON',
    `previous_event_hash` char(64) NULL COMMENT '前序事件 Hash',
    `event_hash` char(64) NOT NULL COMMENT '事件 Hash',
    `algorithm` varchar(32) NOT NULL COMMENT 'Hash 算法',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_gxp_audit_event_idempotency` (`tenant_id`, `idempotency_key`),
    KEY `idx_gxp_audit_event_subject` (`tenant_id`, `domain`, `subject_type`, `subject_id`, `server_occurred_at`),
    KEY `idx_gxp_audit_event_operation` (`tenant_id`, `operation_id`, `server_occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='GxP 统一审计事件只追加账本';

CREATE TABLE IF NOT EXISTS `gxp_audit_policy_version` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '策略版本编号',
    `tenant_id` bigint NOT NULL COMMENT '租户编号',
    `policy_version` varchar(128) NOT NULL COMMENT '策略版本',
    `policy_hash` char(64) NOT NULL COMMENT '策略文件 Hash',
    `approved_by` bigint NOT NULL COMMENT '批准人',
    `approved_at` datetime NOT NULL COMMENT '批准时间',
    `approval_reference` varchar(256) NOT NULL COMMENT '批准依据',
    `coverage_report_hash` char(64) NOT NULL COMMENT '覆盖报告 Hash',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_gxp_audit_policy_version` (`tenant_id`, `policy_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='GxP 审计策略版本登记';
