-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=; type=schema; riskLevel=medium
CREATE TABLE IF NOT EXISTS `mes_kingdee_production_material_list` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `source_form_id` varchar(64) NOT NULL DEFAULT 'PRD_PPBOM' COMMENT 'ERP来源表单标识',
  `source_bill_no` varchar(64) NOT NULL COMMENT 'ERP生产用料清单单据编号',
  `source_entry_id` varchar(64) DEFAULT NULL COMMENT 'ERP来源分录ID',
  `product_code` varchar(64) NOT NULL COMMENT '产品编码',
  `production_order_no` varchar(64) NOT NULL COMMENT '生产订单编号',
  `production_order_line_no` int NOT NULL COMMENT '生产订单行号',
  `production_order_status` varchar(64) DEFAULT NULL COMMENT '生产订单状态',
  `child_material_code` varchar(64) NOT NULL COMMENT '子项物料编码',
  `child_material_name` varchar(255) NOT NULL COMMENT '子项物料名称',
  `child_material_specification` varchar(255) DEFAULT NULL COMMENT '规格型号',
  `child_material_type` varchar(64) DEFAULT NULL COMMENT '子项类型',
  `numerator` decimal(24,6) DEFAULT NULL COMMENT '分子',
  `denominator` decimal(24,6) DEFAULT NULL COMMENT '分母',
  `child_unit_name` varchar(32) DEFAULT NULL COMMENT '子项单位',
  `required_quantity` decimal(24,6) NOT NULL COMMENT '应发数量',
  `issue_method` varchar(64) DEFAULT NULL COMMENT '发料方式',
  `demand_time` datetime DEFAULT NULL COMMENT '需求日期',
  `work_order_id` bigint DEFAULT NULL COMMENT '本地生产工单ID',
  `work_order_code` varchar(64) DEFAULT NULL COMMENT '本地生产工单编号',
  `work_order_bom_id` bigint DEFAULT NULL COMMENT '本地生产工单BOM明细ID',
  `product_id` bigint DEFAULT NULL COMMENT '本地产品物料ID',
  `child_material_id` bigint DEFAULT NULL COMMENT '本地子项物料ID',
  `source_modify_time` datetime DEFAULT NULL COMMENT 'ERP来源修改时间',
  `last_sync_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后同步时间',
  `raw_payload` longtext DEFAULT NULL COMMENT 'ERP原始载荷快照',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mes_kingdee_prod_material_list_source` (`tenant_id`, `source_bill_no`, `production_order_no`, `production_order_line_no`, `child_material_code`),
  KEY `idx_mes_kingdee_prod_material_list_order` (`tenant_id`, `production_order_no`, `production_order_line_no`),
  KEY `idx_mes_kingdee_prod_material_list_child` (`tenant_id`, `child_material_code`),
  KEY `idx_mes_kingdee_prod_material_list_work_order` (`tenant_id`, `work_order_id`),
  KEY `idx_mes_kingdee_prod_material_list_modify_time` (`tenant_id`, `source_modify_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP生产用料清单同步明细';

