-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=20260730_mes_process_pool_foundation; type=schema; riskLevel=medium
-- MES active-order pick-list binding header and immutable line snapshot schema.

CREATE TABLE IF NOT EXISTS mes_pro_process_pool_active_order_pick_list_binding (
  id bigint NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 0,
  active_order_id bigint NOT NULL,
  work_order_id bigint NOT NULL,
  pick_list_id bigint NOT NULL,
  source_fid varchar(128) NOT NULL,
  source_bill_no varchar(128) DEFAULT NULL,
  source_document_status varchar(32) NOT NULL,
  source_modify_time datetime DEFAULT NULL,
  source_snapshot_hash varchar(64) NOT NULL,
  binding_status varchar(32) NOT NULL,
  bound_by bigint NOT NULL,
  bound_at datetime NOT NULL,
  idempotency_key varchar(128) NOT NULL,
  request_payload_hash varchar(64) NOT NULL,
  binding_version int NOT NULL DEFAULT 1,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_active_order_pick_binding_pick_list (tenant_id,active_order_id,pick_list_id,deleted),
  UNIQUE KEY uk_active_order_pick_binding_idempotency (tenant_id,idempotency_key,deleted),
  KEY idx_active_order_pick_binding_pick_list (tenant_id,pick_list_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='活跃订单领料单绑定头快照';

CREATE TABLE IF NOT EXISTS mes_pro_process_pool_active_order_pick_list_binding_item (
  id bigint NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 0,
  binding_id bigint NOT NULL,
  pick_list_item_id bigint NOT NULL,
  source_entry_id varchar(128) NOT NULL,
  source_line_key varchar(128) DEFAULT NULL,
  material_number varchar(128) DEFAULT NULL,
  material_name varchar(255) DEFAULT NULL,
  material_specification varchar(255) DEFAULT NULL,
  unit_name varchar(64) DEFAULT NULL,
  requested_quantity decimal(18,6) DEFAULT NULL,
  actual_quantity decimal(18,6) DEFAULT NULL,
  base_actual_quantity decimal(18,6) DEFAULT NULL,
  lot_number varchar(128) DEFAULT NULL,
  production_order_no varchar(128) NOT NULL,
  production_order_line_no int DEFAULT NULL,
  source_modify_time datetime DEFAULT NULL,
  item_snapshot_hash varchar(64) NOT NULL,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_active_order_pick_binding_item (tenant_id,binding_id,pick_list_item_id,deleted),
  UNIQUE KEY uk_active_order_pick_binding_entry (tenant_id,binding_id,source_entry_id,deleted),
  KEY idx_active_order_pick_binding_item_binding (tenant_id,binding_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='活跃订单领料单绑定明细快照';
