-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=20260802_mes_process_pool_active_order_process_snapshot; type=schema; riskLevel=medium
-- MES M4：统一 activeOrderId 与调拨、发货、补料、退料、报废和批次库存追溯正式关系

CREATE TABLE IF NOT EXISTS `mes_pro_process_pool_active_order_transfer_trace` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `active_order_id` bigint NOT NULL COMMENT '统一活跃订单ID',
    `work_order_id` bigint NOT NULL COMMENT '生产订单ID',
    `route_id` bigint NOT NULL COMMENT '正式工艺路线ID',
    `route_version_id` bigint NOT NULL COMMENT '正式工艺路线版本ID',
    `source_type` varchar(32) NOT NULL COMMENT '来源类型：TRANSFER/SHIPMENT/REPLENISHMENT/RETURN/BATCH_TRACE/SCRAP/REWORK',
    `direction` varchar(32) NOT NULL COMMENT '方向：IN/OUT/SHIPMENT/REPLENISHMENT/RETURN/SCRAP/REWORK',
    `transfer_id` bigint DEFAULT NULL COMMENT '调拨单ID',
    `transfer_line_id` bigint DEFAULT NULL COMMENT '调拨单行ID',
    `transfer_detail_id` bigint DEFAULT NULL COMMENT '调拨明细ID',
    `material_stock_id` bigint DEFAULT NULL COMMENT '库存台账ID',
    `batch_id` bigint DEFAULT NULL COMMENT '物料批次ID',
    `item_id` bigint DEFAULT NULL COMMENT '物料ID',
    `quantity` decimal(24,6) DEFAULT NULL COMMENT '来源数量',
    `source_object_type` varchar(64) NOT NULL COMMENT '来源对象类型',
    `source_object_id` varchar(64) NOT NULL COMMENT '来源对象ID',
    `source_object_code` varchar(128) NOT NULL COMMENT '来源对象编号',
    `source_status` varchar(32) NOT NULL COMMENT '来源状态快照',
    `source_occurred_at` datetime DEFAULT NULL COMMENT '来源发生时间',
    `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
    `source_snapshot_json` json DEFAULT NULL COMMENT '来源快照JSON',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_mes_pp_active_order_transfer_trace` (`tenant_id`, `idempotency_key`, `deleted`),
    KEY `idx_mes_pp_active_order_transfer_trace_order` (`tenant_id`, `active_order_id`, `source_type`, `direction`),
    KEY `idx_mes_pp_active_order_shipment_source` (`tenant_id`, `active_order_id`, `source_type`, `source_status`),
    KEY `idx_mes_pp_active_order_replenishment_return` (`tenant_id`, `active_order_id`, `direction`, `source_type`),
    KEY `idx_mes_pp_active_order_transfer_trace_source` (`tenant_id`, `source_object_type`, `source_object_id`),
    KEY `idx_mes_pp_active_order_batch_material_stock` (`tenant_id`, `active_order_id`, `batch_id`, `material_stock_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 工序池活跃订单调拨发货补退料批次库存追溯';
