-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=; type=schema; riskLevel=medium
-- Add DCC NAS transfer async task persistence tables.
-- Safe to run repeatedly on MySQL runtime schemas.

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_nas_transfer_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `operator_user_id` bigint NOT NULL,
  `template_category_id` bigint NOT NULL,
  `product_master_id` bigint NOT NULL COMMENT 'MDM product selected for DCC submit',
  `effective_date` date NOT NULL,
  `selected_nas_paths_json` longtext NOT NULL,
  `source_type` varchar(32) NOT NULL DEFAULT 'NAS' COMMENT 'NAS or LOCAL_FOLDER',
  `expected_file_count` bigint NOT NULL DEFAULT 0 COMMENT 'Expected files for LOCAL_FOLDER upload session',
  `expected_total_bytes` bigint NOT NULL DEFAULT 0 COMMENT 'Expected bytes for LOCAL_FOLDER upload session',
  `uploaded_file_count` bigint NOT NULL DEFAULT 0 COMMENT 'Uploaded files for LOCAL_FOLDER upload session',
  `uploaded_total_bytes` bigint NOT NULL DEFAULT 0 COMMENT 'Uploaded bytes for LOCAL_FOLDER upload session',
  `upload_completed_at` datetime DEFAULT NULL COMMENT 'LOCAL_FOLDER upload completion time',
  `status` varchar(32) NOT NULL,
  `next_check_at` datetime DEFAULT NULL,
  `last_run_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `last_failure_message` varchar(512) DEFAULT NULL,
  `failure_report_path` varchar(512) DEFAULT NULL,
  `failure_report_generated_at` varchar(64) DEFAULT NULL,
  `failure_report_error` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_dcc_nas_transfer_task_status` (`status`, `next_check_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_nas_transfer_task_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `parent_item_id` bigint DEFAULT NULL,
  `item_type` varchar(16) NOT NULL,
  `nas_path` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `item_name` varchar(255) NOT NULL,
  `source_file_id` bigint DEFAULT NULL COMMENT 'infra_file.id for LOCAL_FOLDER file items',
  `status` varchar(32) NOT NULL,
  `attempt_count` int NOT NULL DEFAULT 0,
  `failure_stage` varchar(32) DEFAULT NULL,
  `last_error` varchar(512) DEFAULT NULL,
  `resolved_directory_id` bigint DEFAULT NULL,
  `resolved_category_id` bigint DEFAULT NULL,
  `directory_outcome` varchar(16) DEFAULT NULL,
  `category_outcome` varchar(16) DEFAULT NULL,
  `preview_download_only` bit(1) NOT NULL DEFAULT b'0',
  `last_attempt_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_nas_transfer_task_item_path` (`task_id`, `nas_path`),
  KEY `idx_dcc_nas_transfer_task_item_status` (`task_id`, `status`, `id`),
  KEY `idx_dcc_nas_transfer_task_item_parent` (`parent_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
