-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=; type=schema; riskLevel=medium
CREATE TABLE IF NOT EXISTS `erp_kingdee_inventory_list` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
  `source_form_id` varchar(64) NOT NULL DEFAULT 'STK_Inventory' COMMENT 'ERP来源表单标识',
  `source_line_key` varchar(255) NOT NULL COMMENT 'ERP即时库存行唯一键',
  `material_number` varchar(64) NOT NULL COMMENT '物料编码',
  `material_name` varchar(255) NOT NULL COMMENT '物料名称',
  `material_specification` varchar(512) DEFAULT NULL COMMENT '规格型号',
  `warehouse_number` varchar(64) NOT NULL COMMENT '仓库编码',
  `warehouse_name` varchar(255) NOT NULL COMMENT '仓库名称',
  `lot_number` varchar(128) DEFAULT NULL COMMENT '批号',
  `unit_name` varchar(64) DEFAULT NULL COMMENT '单位',
  `quantity` decimal(24,6) NOT NULL COMMENT '库存数量',
  `stock_org_number` varchar(64) NOT NULL COMMENT '库存组织编码',
  `stock_org_name` varchar(255) NOT NULL COMMENT '库存组织名称',
  `source_modify_time` datetime DEFAULT NULL COMMENT 'ERP来源修改时间',
  `last_sync_time` datetime NOT NULL COMMENT '最后同步时间',
  `raw_payload` longtext DEFAULT NULL COMMENT 'ERP原始载荷快照',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_erp_kingdee_inventory_list_source` (`tenant_id`, `source_line_key`),
  KEY `idx_erp_kingdee_inventory_list_material` (`tenant_id`, `material_number`),
  KEY `idx_erp_kingdee_inventory_list_warehouse` (`tenant_id`, `warehouse_number`),
  KEY `idx_erp_kingdee_inventory_list_modify_time` (`tenant_id`, `source_modify_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ERP即时库存列表同步明细';
