-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=20260608_edhr_batch_execution_schema; type=schema; riskLevel=high
-- Flow 9 controlled independent-entry prerequisite receipt ledger.
-- Receipt payloads are issued by the backend only; no client supplied credential is persisted.

CREATE TABLE IF NOT EXISTS mes_independent_batch_prerequisite_receipt (
  id bigint NOT NULL AUTO_INCREMENT,
  receipt_id varchar(64) NOT NULL,
  tenant_id bigint NOT NULL,
  entry_type varchar(32) NOT NULL,
  work_order_id bigint NOT NULL,
  work_order_code varchar(64) NOT NULL,
  route_id bigint NOT NULL,
  route_version_id bigint NOT NULL,
  route_version varchar(64) NOT NULL,
  batch_code varchar(128) NOT NULL,
  source_relation_id varchar(128) NOT NULL,
  source_relation_version varchar(64) NOT NULL,
  source_relation_snapshot_hash char(64) NOT NULL,
  source_object_type varchar(64) NOT NULL,
  source_object_id varchar(128) NOT NULL,
  material_source_type varchar(64) NOT NULL,
  material_source_id varchar(128) NOT NULL,
  source_context_hash char(64) NOT NULL,
  source_snapshot_hash char(64) NOT NULL,
  business_reason varchar(512) NOT NULL,
  issuer_system varchar(128) NOT NULL,
  issuer_user_id bigint NOT NULL,
  issuer_user_role varchar(128) NOT NULL,
  issued_at datetime NOT NULL,
  expires_at datetime NOT NULL,
  revoked_at datetime DEFAULT NULL,
  revocation_reason varchar(512) DEFAULT NULL,
  credential_version bigint NOT NULL,
  status varchar(16) NOT NULL,
  canonical_payload longtext NOT NULL,
  source_evidence_json longtext NOT NULL,
  receipt_hash char(64) NOT NULL,
  payload_hash char(64) NOT NULL,
  signature char(64) NOT NULL,
  audit_event_id varchar(128) NOT NULL,
  idempotency_key varchar(128) NOT NULL,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_independent_receipt_tenant_receipt (tenant_id, receipt_id, deleted),
  UNIQUE KEY uk_independent_receipt_tenant_idempotency (tenant_id, entry_type, idempotency_key, deleted),
  KEY idx_independent_receipt_source_relation (tenant_id, source_relation_id, source_relation_version),
  KEY idx_independent_receipt_source_snapshot (tenant_id, source_snapshot_hash),
  KEY idx_independent_receipt_status (tenant_id, status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流程9独立批次正式前置凭证';
