-- T3：统一电子签名内核最小持久化模型
-- 说明：该表是新签名事实源；DCC/BPM/MES 旧表迁移在 T4-T6 完成后不得再作为正式写入口。

CREATE TABLE IF NOT EXISTS `system_electronic_signature` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '签名记录编号',
  `tenant_id` bigint NOT NULL COMMENT '租户编号',
  `module_code` varchar(64) NOT NULL COMMENT '业务模块编码',
  `action_code` varchar(64) NOT NULL COMMENT '签名动作编码',
  `subject_type` varchar(64) NOT NULL COMMENT '被签对象类型',
  `subject_id` varchar(2048) NOT NULL COMMENT '被签对象编号',
  `subject_version` varchar(128) NOT NULL COMMENT '被签对象版本',
  `actor_id` bigint NOT NULL COMMENT '签名人用户编号',
  `meaning_code` varchar(64) NOT NULL COMMENT '签名含义编码',
  `meaning_label` varchar(128) NOT NULL COMMENT '签名含义名称',
  `reason` varchar(500) NOT NULL COMMENT '签名理由',
  `signed_at` datetime NOT NULL COMMENT '服务端签名时间',
  `time_evidence_id` varchar(128) NOT NULL COMMENT '时间证据编号',
  `authentication_method` varchar(64) NOT NULL COMMENT '身份验证方式',
  `content_hash` char(64) NOT NULL COMMENT '规范化内容 SHA-256',
  `before_content_hash` char(64) DEFAULT NULL COMMENT '变更前内容 SHA-256',
  `after_content_hash` char(64) DEFAULT NULL COMMENT '变更后内容 SHA-256',
  `canonical_content_json` json NOT NULL COMMENT '规范化可读内容',
  `before_content_json` json DEFAULT NULL COMMENT '变更前可读内容',
  `after_content_json` json DEFAULT NULL COMMENT '变更后可读内容',
  `field_diff_json` json DEFAULT NULL COMMENT '字段级差异',
  `evidence_hash` char(64) NOT NULL COMMENT '签名证据 SHA-256',
  `algorithm` varchar(32) NOT NULL COMMENT '摘要算法',
  `key_version` varchar(64) NOT NULL COMMENT '证据密钥版本',
  `policy_version` varchar(64) NOT NULL COMMENT '签名策略版本',
  `verification_status` varchar(32) NOT NULL COMMENT '验证状态',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `command_hash` char(64) NOT NULL COMMENT '不含密码的命令摘要',
  `process_instance_id` varchar(128) DEFAULT NULL COMMENT '流程实例编号',
  `task_id` varchar(128) DEFAULT NULL COMMENT '流程任务编号',
  `node_code` varchar(64) DEFAULT NULL COMMENT '流程节点编码',
  `node_order` int DEFAULT NULL COMMENT '流程节点顺序',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_system_esign_idempotency` (`tenant_id`, `idempotency_key`, `deleted`),
  KEY `idx_system_esign_subject` (`tenant_id`, `module_code`, `subject_type`, `subject_id`, `deleted`),
  KEY `idx_system_esign_actor_time` (`tenant_id`, `actor_id`, `signed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='统一电子签名记录';
