-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=20260730_dcc_nas_control_audit; type=schema; riskLevel=medium
-- Add queryable DCC NAS uncontrolled-file audit details.

CREATE TABLE IF NOT EXISTS `dcc_nas_control_audit_file` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL COMMENT 'dcc_nas_control_audit_task.id',
  `nas_share_name` varchar(128) NOT NULL COMMENT 'NAS share name',
  `root_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Scanned root path',
  `normalized_relative_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'Normalized path relative to NAS share',
  `path_hash` char(64) NOT NULL COMMENT 'SHA-256 of share and normalized path',
  `file_name` varchar(255) NOT NULL COMMENT 'Source file name',
  `file_size` bigint NOT NULL COMMENT 'Source file size in bytes',
  `modified_at` datetime NOT NULL COMMENT 'Source file modified time snapshot',
  `source_signature` char(64) NOT NULL COMMENT 'SHA-256 of path_hash|file_size|modified_at_utc_epoch_millis',
  `control_status` varchar(32) NOT NULL DEFAULT 'NOT_CONTROLLED' COMMENT 'NOT_CONTROLLED',
  `classification_status` varchar(32) NOT NULL DEFAULT 'PENDING_RECOGNITION' COMMENT 'PENDING_RECOGNITION, MATCHED, UNCLASSIFIED_PENDING, AMBIGUOUS',
  `matched_project_code_id` bigint DEFAULT NULL COMMENT 'dcc_project_code.id when uniquely matched',
  `matched_file_type_taxonomy_id` bigint DEFAULT NULL COMMENT 'dcc_file_type_taxonomy.id when uniquely matched',
  `matched_file_type_level1` varchar(128) DEFAULT NULL,
  `matched_file_type_level2` varchar(128) DEFAULT NULL,
  `matched_file_type_level3` varchar(128) DEFAULT NULL,
  `matched_file_type_level4` varchar(128) DEFAULT NULL,
  `matched_file_type_level5` varchar(128) DEFAULT NULL,
  `classification_reason` varchar(255) DEFAULT NULL COMMENT 'Recognition result or pending reason',
  `classification_candidates_json` text DEFAULT NULL COMMENT 'Bounded recognition candidate summary JSON',
  `expected_local_relative_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Backend-generated expected local relative path',
  `download_status` varchar(32) NOT NULL DEFAULT 'NOT_SELECTED' COMMENT 'NOT_SELECTED, SELECTED, CONTENT_READY, LOCAL_WRITTEN, LOCAL_WRITE_FAILED',
  `archive_status` varchar(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT 'NOT_STARTED, ARCHIVED, PENDING_MANUAL_REVIEW, FAILED',
  `local_relative_path` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Authorized local relative path only',
  `local_write_error_code` varchar(64) DEFAULT NULL COMMENT 'Local write failure code',
  `local_write_error` varchar(512) DEFAULT NULL COMMENT 'Local write failure message',
  `archive_error_code` varchar(64) DEFAULT NULL COMMENT 'Archive failure code',
  `archive_error` varchar(512) DEFAULT NULL COMMENT 'Archive failure message',
  `controlled_file_id` bigint DEFAULT NULL COMMENT 'dcc_controlled_file.id after archive',
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_dcc_nas_audit_file_task` (`tenant_id`, `task_id`, `id`),
  KEY `idx_dcc_nas_audit_file_path_hash` (`tenant_id`, `nas_share_name`, `path_hash`, `deleted`),
  KEY `idx_dcc_nas_audit_file_status` (`tenant_id`, `classification_status`, `download_status`, `archive_status`),
  KEY `idx_dcc_nas_audit_file_controlled` (`tenant_id`, `controlled_file_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
