-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=; type=schema; riskLevel=medium
-- ERP base schema repair for MySQL.
-- Generated from yudao-module-erp DO annotations and fields.
-- Safe to run repeatedly: creates missing tables only and does not delete data.

CREATE TABLE IF NOT EXISTS `erp_account` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(128) DEFAULT NULL,
  `no` varchar(64) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `sort` int DEFAULT NULL,
  `default_status` bit(1) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_account_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpAccountDO';

CREATE TABLE IF NOT EXISTS `erp_customer` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(128) DEFAULT NULL,
  `contact` varchar(128) DEFAULT NULL,
  `mobile` varchar(32) DEFAULT NULL,
  `telephone` varchar(32) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `sort` int DEFAULT NULL,
  `tax_no` varchar(64) DEFAULT NULL,
  `tax_percent` decimal(24,6) DEFAULT NULL,
  `bank_name` varchar(128) DEFAULT NULL,
  `bank_account` varchar(255) DEFAULT NULL,
  `bank_address` varchar(255) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_customer_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpCustomerDO';

CREATE TABLE IF NOT EXISTS `erp_finance_payment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `payment_time` datetime DEFAULT NULL,
  `finance_user_id` bigint DEFAULT NULL,
  `supplier_id` bigint DEFAULT NULL,
  `account_id` bigint DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `discount_price` decimal(24,6) DEFAULT NULL,
  `payment_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_finance_payment_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpFinancePaymentDO';

CREATE TABLE IF NOT EXISTS `erp_finance_payment_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `payment_id` bigint DEFAULT NULL,
  `biz_type` int DEFAULT NULL,
  `biz_id` bigint DEFAULT NULL,
  `biz_no` varchar(64) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `paid_price` decimal(24,6) DEFAULT NULL,
  `payment_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_finance_payment_item_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpFinancePaymentItemDO';

CREATE TABLE IF NOT EXISTS `erp_finance_receipt` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `receipt_time` datetime DEFAULT NULL,
  `finance_user_id` bigint DEFAULT NULL,
  `customer_id` bigint DEFAULT NULL,
  `account_id` bigint DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `discount_price` decimal(24,6) DEFAULT NULL,
  `receipt_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_finance_receipt_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpFinanceReceiptDO';

CREATE TABLE IF NOT EXISTS `erp_finance_receipt_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `receipt_id` bigint DEFAULT NULL,
  `biz_type` int DEFAULT NULL,
  `biz_id` bigint DEFAULT NULL,
  `biz_no` varchar(64) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `receipted_price` decimal(24,6) DEFAULT NULL,
  `receipt_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_finance_receipt_item_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpFinanceReceiptItemDO';

CREATE TABLE IF NOT EXISTS `erp_product` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(128) DEFAULT NULL,
  `bar_code` varchar(64) DEFAULT NULL,
  `category_id` bigint DEFAULT NULL,
  `unit_id` bigint DEFAULT NULL,
  `status` int DEFAULT NULL,
  `standard` varchar(1024) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `expiry_day` int DEFAULT NULL,
  `weight` decimal(24,6) DEFAULT NULL,
  `purchase_price` decimal(24,6) DEFAULT NULL,
  `sale_price` decimal(24,6) DEFAULT NULL,
  `min_price` decimal(24,6) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_product_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpProductDO';

CREATE TABLE IF NOT EXISTS `erp_product_category` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `parent_id` bigint DEFAULT NULL,
  `name` varchar(128) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  `sort` int DEFAULT NULL,
  `status` int DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_product_category_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpProductCategoryDO';

CREATE TABLE IF NOT EXISTS `erp_product_unit` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(128) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_product_unit_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpProductUnitDO';

CREATE TABLE IF NOT EXISTS `erp_purchase_in` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `supplier_id` bigint DEFAULT NULL,
  `account_id` bigint DEFAULT NULL,
  `in_time` datetime DEFAULT NULL,
  `order_id` bigint DEFAULT NULL,
  `order_no` varchar(64) DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `payment_price` decimal(24,6) DEFAULT NULL,
  `total_product_price` decimal(24,6) DEFAULT NULL,
  `total_tax_price` decimal(24,6) DEFAULT NULL,
  `discount_percent` decimal(24,6) DEFAULT NULL,
  `discount_price` decimal(24,6) DEFAULT NULL,
  `other_price` decimal(24,6) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_in_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpPurchaseInDO';

CREATE TABLE IF NOT EXISTS `erp_purchase_in_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `in_id` bigint DEFAULT NULL,
  `order_item_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `tax_percent` decimal(24,6) DEFAULT NULL,
  `tax_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_in_items_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpPurchaseInItemDO';

CREATE TABLE IF NOT EXISTS `erp_purchase_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `supplier_id` bigint DEFAULT NULL,
  `account_id` bigint DEFAULT NULL,
  `order_time` datetime DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `total_product_price` decimal(24,6) DEFAULT NULL,
  `total_tax_price` decimal(24,6) DEFAULT NULL,
  `discount_percent` decimal(24,6) DEFAULT NULL,
  `discount_price` decimal(24,6) DEFAULT NULL,
  `deposit_price` decimal(24,6) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `in_count` decimal(24,6) DEFAULT NULL,
  `return_count` decimal(24,6) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_order_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpPurchaseOrderDO';

CREATE TABLE IF NOT EXISTS `erp_purchase_order_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `tax_percent` decimal(24,6) DEFAULT NULL,
  `tax_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `in_count` decimal(24,6) DEFAULT NULL,
  `return_count` decimal(24,6) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_order_items_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpPurchaseOrderItemDO';

CREATE TABLE IF NOT EXISTS `erp_purchase_return` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `supplier_id` bigint DEFAULT NULL,
  `account_id` bigint DEFAULT NULL,
  `return_time` datetime DEFAULT NULL,
  `order_id` bigint DEFAULT NULL,
  `order_no` varchar(64) DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `refund_price` decimal(24,6) DEFAULT NULL,
  `total_product_price` decimal(24,6) DEFAULT NULL,
  `total_tax_price` decimal(24,6) DEFAULT NULL,
  `discount_percent` decimal(24,6) DEFAULT NULL,
  `discount_price` decimal(24,6) DEFAULT NULL,
  `other_price` decimal(24,6) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_return_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpPurchaseReturnDO';

CREATE TABLE IF NOT EXISTS `erp_purchase_return_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `return_id` bigint DEFAULT NULL,
  `order_item_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `tax_percent` decimal(24,6) DEFAULT NULL,
  `tax_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_purchase_return_items_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpPurchaseReturnItemDO';

CREATE TABLE IF NOT EXISTS `erp_sale_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `customer_id` bigint DEFAULT NULL,
  `account_id` bigint DEFAULT NULL,
  `sale_user_id` bigint DEFAULT NULL,
  `order_time` datetime DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `total_product_price` decimal(24,6) DEFAULT NULL,
  `total_tax_price` decimal(24,6) DEFAULT NULL,
  `discount_percent` decimal(24,6) DEFAULT NULL,
  `discount_price` decimal(24,6) DEFAULT NULL,
  `deposit_price` decimal(24,6) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `out_count` decimal(24,6) DEFAULT NULL,
  `return_count` decimal(24,6) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_order_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpSaleOrderDO';

CREATE TABLE IF NOT EXISTS `erp_sale_order_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `tax_percent` decimal(24,6) DEFAULT NULL,
  `tax_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `out_count` decimal(24,6) DEFAULT NULL,
  `return_count` decimal(24,6) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_order_items_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpSaleOrderItemDO';

CREATE TABLE IF NOT EXISTS `erp_sale_out` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `customer_id` bigint DEFAULT NULL,
  `account_id` bigint DEFAULT NULL,
  `sale_user_id` bigint DEFAULT NULL,
  `out_time` datetime DEFAULT NULL,
  `order_id` bigint DEFAULT NULL,
  `order_no` varchar(64) DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `receipt_price` decimal(24,6) DEFAULT NULL,
  `total_product_price` decimal(24,6) DEFAULT NULL,
  `total_tax_price` decimal(24,6) DEFAULT NULL,
  `discount_percent` decimal(24,6) DEFAULT NULL,
  `discount_price` decimal(24,6) DEFAULT NULL,
  `other_price` decimal(24,6) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_out_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpSaleOutDO';

CREATE TABLE IF NOT EXISTS `erp_sale_out_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `out_id` bigint DEFAULT NULL,
  `order_item_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `tax_percent` decimal(24,6) DEFAULT NULL,
  `tax_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_out_items_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpSaleOutItemDO';

CREATE TABLE IF NOT EXISTS `erp_sale_return` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `customer_id` bigint DEFAULT NULL,
  `account_id` bigint DEFAULT NULL,
  `sale_user_id` bigint DEFAULT NULL,
  `return_time` datetime DEFAULT NULL,
  `order_id` bigint DEFAULT NULL,
  `order_no` varchar(64) DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `refund_price` decimal(24,6) DEFAULT NULL,
  `total_product_price` decimal(24,6) DEFAULT NULL,
  `total_tax_price` decimal(24,6) DEFAULT NULL,
  `discount_percent` decimal(24,6) DEFAULT NULL,
  `discount_price` decimal(24,6) DEFAULT NULL,
  `other_price` decimal(24,6) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_return_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpSaleReturnDO';

CREATE TABLE IF NOT EXISTS `erp_sale_return_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `return_id` bigint DEFAULT NULL,
  `order_item_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `tax_percent` decimal(24,6) DEFAULT NULL,
  `tax_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_sale_return_items_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpSaleReturnItemDO';

CREATE TABLE IF NOT EXISTS `erp_stock` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `product_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockDO';

CREATE TABLE IF NOT EXISTS `erp_stock_check` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `check_time` datetime DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_check_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockCheckDO';

CREATE TABLE IF NOT EXISTS `erp_stock_check_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `check_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `stock_count` decimal(24,6) DEFAULT NULL,
  `actual_count` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_check_item_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockCheckItemDO';

CREATE TABLE IF NOT EXISTS `erp_stock_in` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `supplier_id` bigint DEFAULT NULL,
  `in_time` datetime DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_in_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockInDO';

CREATE TABLE IF NOT EXISTS `erp_stock_in_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `in_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_in_item_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockInItemDO';

CREATE TABLE IF NOT EXISTS `erp_stock_move` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `move_time` datetime DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_move_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockMoveDO';

CREATE TABLE IF NOT EXISTS `erp_stock_move_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `move_id` bigint DEFAULT NULL,
  `from_warehouse_id` bigint DEFAULT NULL,
  `to_warehouse_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_move_item_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockMoveItemDO';

CREATE TABLE IF NOT EXISTS `erp_stock_out` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `no` varchar(64) DEFAULT NULL,
  `customer_id` bigint DEFAULT NULL,
  `out_time` datetime DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `file_url` varchar(1024) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_out_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockOutDO';

CREATE TABLE IF NOT EXISTS `erp_stock_out_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `out_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `product_id` bigint DEFAULT NULL,
  `product_unit_id` bigint DEFAULT NULL,
  `product_price` decimal(24,6) DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_price` decimal(24,6) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_out_item_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockOutItemDO';

CREATE TABLE IF NOT EXISTS `erp_stock_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `product_id` bigint DEFAULT NULL,
  `warehouse_id` bigint DEFAULT NULL,
  `count` decimal(24,6) DEFAULT NULL,
  `total_count` decimal(24,6) DEFAULT NULL,
  `biz_type` int DEFAULT NULL,
  `biz_id` bigint DEFAULT NULL,
  `biz_item_id` bigint DEFAULT NULL,
  `biz_no` varchar(64) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_stock_record_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpStockRecordDO';

CREATE TABLE IF NOT EXISTS `erp_supplier` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(128) DEFAULT NULL,
  `contact` varchar(128) DEFAULT NULL,
  `mobile` varchar(32) DEFAULT NULL,
  `telephone` varchar(32) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `sort` int DEFAULT NULL,
  `tax_no` varchar(64) DEFAULT NULL,
  `tax_percent` decimal(24,6) DEFAULT NULL,
  `bank_name` varchar(128) DEFAULT NULL,
  `bank_account` varchar(255) DEFAULT NULL,
  `bank_address` varchar(255) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_supplier_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpSupplierDO';

CREATE TABLE IF NOT EXISTS `erp_warehouse` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(128) DEFAULT NULL,
  `address` varchar(512) DEFAULT NULL,
  `sort` bigint DEFAULT NULL,
  `remark` varchar(512) DEFAULT NULL,
  `principal` varchar(255) DEFAULT NULL,
  `warehouse_price` decimal(24,6) DEFAULT NULL,
  `truckage_price` decimal(24,6) DEFAULT NULL,
  `status` int DEFAULT NULL,
  `default_status` bit(1) DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_erp_warehouse_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ErpWarehouseDO';
