CREATE TABLE IF NOT EXISTS `mes_pro_batch_record_repeat_row_group` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  `scope_type` varchar(64) NOT NULL COMMENT '配置范围',
  `scope_id` bigint NOT NULL COMMENT '范围 ID',
  `route_id` bigint DEFAULT NULL COMMENT '工艺路线 ID',
  `batch_record_definition_id` bigint DEFAULT NULL COMMENT '批记录定义 ID',
  `batch_record_version_id` bigint DEFAULT NULL COMMENT '批记录版本 ID',
  `route_process_id` bigint NOT NULL COMMENT '路线工序 ID',
  `target_report_id` varchar(64) NOT NULL COMMENT '目标批记录表单 reportId',
  `target_report_name` varchar(128) DEFAULT NULL COMMENT '目标批记录表单名称',
  `template_start_row_index` int NOT NULL COMMENT '模板记录开始行',
  `template_end_row_index` int NOT NULL COMMENT '模板记录结束行',
  `repeat_area_start_row_index` int NOT NULL COMMENT '重复区域开始行',
  `repeat_area_end_row_index` int NOT NULL COMMENT '重复区域结束行',
  `source_type` varchar(64) NOT NULL COMMENT '来源类型',
  `records_json` longtext NOT NULL COMMENT '用户确认的重复记录顺序',
  `mappings_json` longtext NOT NULL COMMENT '模板字段映射与投影目标',
  `config_version` bigint NOT NULL COMMENT '配置版本',
  `template_snapshot_hash` varchar(128) NOT NULL COMMENT '模板快照哈希',
  `enabled` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_mes_batch_record_repeat_row_group_scope` (`tenant_id`, `scope_type`, `scope_id`, `target_report_id`, `route_process_id`, `deleted`),
  KEY `idx_mes_batch_record_repeat_row_group_target` (`tenant_id`, `batch_record_version_id`, `target_report_id`, `enabled`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 批记录重复行组对应关系';