-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=20260618_mes_edhr_flow_intervention_log; type=schema; riskLevel=low
-- Local/runtime-safe eDHR flow intervention schema guard: create only the missing event/intervention tables.

CREATE TABLE IF NOT EXISTS `mes_pro_edhr_flow_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `business_object_type` varchar(64) NOT NULL COMMENT '业务对象类型',
  `business_object_id` varchar(128) NOT NULL COMMENT '业务对象ID',
  `business_object_code` varchar(128) DEFAULT NULL COMMENT '业务对象编号',
  `intervention_id` bigint DEFAULT NULL COMMENT '流程干预ID',
  `flow_instance_id` varchar(128) DEFAULT NULL COMMENT '流程实例ID',
  `task_id` varchar(128) DEFAULT NULL COMMENT '流程任务ID',
  `node_key` varchar(128) DEFAULT NULL COMMENT '节点标识',
  `event_type` varchar(32) NOT NULL COMMENT '事件类型',
  `from_status` varchar(32) NOT NULL COMMENT '原状态',
  `to_status` varchar(32) NOT NULL COMMENT '目标状态',
  `actor_user_id` bigint DEFAULT NULL COMMENT '操作人',
  `target_user_id` bigint DEFAULT NULL COMMENT '目标处理人',
  `permission_code` varchar(128) NOT NULL COMMENT '权限编码',
  `permission_decision` varchar(32) NOT NULL COMMENT '权限判定',
  `reason` varchar(500) DEFAULT NULL COMMENT '原因',
  `signoff_evidence_hash` char(64) DEFAULT NULL COMMENT '签核证据摘要',
  `integrity_check_result` varchar(32) NOT NULL COMMENT '完整性复检结果',
  `integrity_check_snapshot_json` longtext DEFAULT NULL COMMENT '完整性复检快照JSON',
  `event_snapshot_json` longtext DEFAULT NULL COMMENT '事件快照JSON',
  `evidence_hash` char(64) NOT NULL COMMENT '事件证据摘要',
  `occurred_at` datetime NOT NULL COMMENT '事件发生时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_mes_pro_edhr_flow_event_object` (`tenant_id`, `business_object_type`, `business_object_id`, `occurred_at`, `deleted`),
  KEY `idx_mes_pro_edhr_flow_event_instance` (`tenant_id`, `flow_instance_id`, `task_id`, `occurred_at`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES eDHR 流程事件';

CREATE TABLE IF NOT EXISTS `mes_pro_edhr_flow_intervention` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `intervention_code` varchar(64) NOT NULL COMMENT '干预编号',
  `business_object_type` varchar(64) NOT NULL COMMENT '业务对象类型',
  `business_object_id` varchar(128) NOT NULL COMMENT '业务对象ID',
  `business_object_code` varchar(128) DEFAULT NULL COMMENT '业务对象编号',
  `flow_instance_id` varchar(128) DEFAULT NULL COMMENT '流程实例ID',
  `intervention_action` varchar(32) NOT NULL COMMENT '干预动作',
  `intervention_status` varchar(32) NOT NULL COMMENT '干预状态',
  `from_status` varchar(32) NOT NULL COMMENT '原状态',
  `to_status` varchar(32) NOT NULL COMMENT '目标状态',
  `source_task_id` varchar(128) DEFAULT NULL COMMENT '来源任务ID',
  `target_task_id` varchar(128) DEFAULT NULL COMMENT '目标任务ID',
  `node_key` varchar(128) DEFAULT NULL COMMENT '节点标识',
  `target_user_id` bigint DEFAULT NULL COMMENT '目标处理人',
  `requested_by` bigint DEFAULT NULL COMMENT '申请人',
  `requested_at` datetime NOT NULL COMMENT '申请时间',
  `reason_category` varchar(64) DEFAULT NULL COMMENT '原因分类',
  `reason` varchar(500) NOT NULL COMMENT '原因',
  `authorization_basis` varchar(500) DEFAULT NULL COMMENT '授权依据',
  `signoff_evidence_hash` char(64) NOT NULL COMMENT '签核证据摘要',
  `idempotency_key` varchar(128) NOT NULL COMMENT '幂等键',
  `integrity_check_result` varchar(32) NOT NULL COMMENT '完整性复检结果',
  `integrity_check_snapshot_json` longtext DEFAULT NULL COMMENT '完整性复检快照JSON',
  `evidence_hash` char(64) NOT NULL COMMENT '干预证据摘要',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mes_pro_edhr_flow_intervention_idempotency` (`tenant_id`, `business_object_type`, `business_object_id`, `intervention_action`, `idempotency_key`, `deleted`),
  KEY `idx_mes_pro_edhr_flow_intervention_object` (`tenant_id`, `business_object_type`, `business_object_id`, `requested_at`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES eDHR 流程干预';
