-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=20260801_mes_process_pool_team_leader_p4_order_completion_backfill; type=schema; riskLevel=medium
-- Flow repair 4: immutable active-order Tx-A completion/backfill receipt.
-- This migration does not add batchExecutionId or any mutable Flow-6 provision state.

CREATE TABLE IF NOT EXISTS `mes_pro_process_pool_active_order_completion_receipt` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '不可变完成/回填回执编号',
    `active_order_id` bigint NOT NULL COMMENT '活跃订单编号',
    `work_order_id` bigint NOT NULL COMMENT '生产工单编号',
    `batch_code` varchar(128) NOT NULL COMMENT '正式生产批次编码',
    `route_id` bigint NOT NULL COMMENT '冻结工艺路线编号',
    `route_version_id` bigint NOT NULL COMMENT '冻结工艺路线版本编号',
    `leader_user_id` bigint NOT NULL COMMENT '点击完成的生产组长用户编号',
    `request_idempotency_key` varchar(128) NOT NULL COMMENT '完成命令幂等键',
    `request_payload_hash` char(64) NOT NULL COMMENT '规范完成请求哈希',
    `source_snapshot_hash` char(64) NOT NULL COMMENT '正式来源快照哈希',
    `formal_source_snapshot_json` json NOT NULL COMMENT '正式生产/领料/PQC来源快照',
    `signature_snapshot_json` json NOT NULL COMMENT '生产与PQC签名事实快照',
    `receipt_hash` char(64) NOT NULL COMMENT '不可变完成回填回执哈希',
    `expected_version` int NOT NULL COMMENT '客户端提交的订单版本',
    `completed_version` int NOT NULL COMMENT '完成后订单版本',
    `receipt_status` varchar(32) NOT NULL COMMENT '完成回填回执状态：BACKFILL_SUCCEEDED',
    `batch_record_status` varchar(32) NOT NULL COMMENT '批记录回填状态：SUCCESS',
    `process_inspection_status` varchar(32) NOT NULL COMMENT '过程检验回填状态：SUCCESS',
    `loss_report_status` varchar(32) NOT NULL COMMENT '损耗回填状态：SUCCESS/NOT_REQUIRED',
    `has_actual_loss` bit(1) NOT NULL COMMENT '订单/工序是否存在实际损耗',
    `loss_quantity` decimal(24,6) NOT NULL COMMENT '订单/工序实际损耗数量',
    `loss_record_id` bigint DEFAULT NULL COMMENT '实际损耗正式单据编号；无损耗时为空',
    `zero_loss_confirmation_snapshot` json DEFAULT NULL COMMENT '无损耗正式零损耗确认快照',
    `loss_condition_facts_json` json NOT NULL COMMENT '逐工序损耗条件快照：REQUIRED/NO_LOSS，BLOCKED不得成功提交',
    `batch_record_source_ids_json` json NOT NULL COMMENT '批记录正式来源编号集合',
    `process_inspection_source_ids_json` json NOT NULL COMMENT '过程检验正式来源编号集合',
    `loss_source_hash` char(64) DEFAULT NULL COMMENT '损耗事实来源哈希',
    `provision_handoff` varchar(32) NOT NULL COMMENT '仅表示交接结果：PENDING_FLOW6',
    `completed_at` datetime NOT NULL COMMENT '完成时间',
    `completed_by` bigint NOT NULL COMMENT '完成操作人',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建后不可变更新时间快照',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_mes_pp_completion_receipt_order` (`tenant_id`, `active_order_id`, `deleted`),
    UNIQUE KEY `uk_mes_pp_completion_receipt_idempotency` (`tenant_id`, `request_idempotency_key`, `deleted`),
    KEY `idx_mes_pp_completion_receipt_source_hash` (`tenant_id`, `source_snapshot_hash`),
    KEY `idx_mes_pp_completion_receipt_work_order` (`tenant_id`, `work_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 活跃订单完成节点不可变 Tx-A 回填回执';

CREATE TABLE IF NOT EXISTS `mes_pro_process_pool_active_order_completion_backfill` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '完成节点资料回填编号',
    `active_order_id` bigint NOT NULL COMMENT '活跃订单编号',
    `work_order_id` bigint NOT NULL COMMENT '生产工单编号',
    `backfill_type` varchar(32) NOT NULL COMMENT 'BATCH_RECORD/PROCESS_INSPECTION/LOSS_REPORT',
    `status` varchar(32) NOT NULL COMMENT 'SUCCESS',
    `source_ids_json` json NOT NULL COMMENT '正式来源编号集合',
    `source_snapshot_hash` char(64) NOT NULL COMMENT '正式来源哈希',
    `payload_json` json NOT NULL COMMENT '来源事实冻结快照',
    `materialized_at` datetime NOT NULL COMMENT 'Tx-A 物化时间',
    `materialized_by` bigint NOT NULL COMMENT '完成操作人',
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_mes_pp_completion_backfill_order_type` (`tenant_id`, `active_order_id`, `backfill_type`, `deleted`),
    KEY `idx_mes_pp_completion_backfill_receipt_hash` (`tenant_id`, `source_snapshot_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 活跃订单完成节点三类正式资料回填';
