-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=20260803_mes_process_pool_pqc_process_inspection_aggregation,20260803_mes_pqc_item_equipment_standard_snapshot; type=schema; riskLevel=medium
-- AC-M21: PQC leader-approved submissions must create structured, traceable process-inspection aggregate rows.

CREATE TABLE IF NOT EXISTS `mes_pqc_process_inspection_aggregate_detail` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `source_pqc_record_id` bigint NOT NULL COMMENT '来源PQC工序池记录ID',
    `source_piece_detail_id` bigint NOT NULL COMMENT '来源PQC逐件明细ID',
    `event_id` bigint NOT NULL COMMENT 'PQC工序池事件ID',
    `review_id` bigint NOT NULL COMMENT '触发汇集的组长复核ID',
    `production_submit_event_id` bigint NOT NULL COMMENT '绑定的生产提交事件ID',
    `pqc_task_id` bigint NOT NULL COMMENT 'PQC检验任务ID',
    `work_order_id` bigint NOT NULL COMMENT '生产订单ID',
    `route_id` bigint NOT NULL COMMENT '工艺路线ID',
    `route_process_id` bigint NOT NULL COMMENT '工艺路线工序ID',
    `process_id` bigint NOT NULL COMMENT '工序ID',
    `regulation_version_id` bigint NOT NULL COMMENT 'QA规程发布版本ID',
    `inspection_type` varchar(32) NOT NULL COMMENT '检验类型',
    `business_date` date NOT NULL COMMENT '业务日期',
    `shift_code` varchar(32) NOT NULL COMMENT '班次编码',
    `round_no` int NOT NULL COMMENT '轮次',
    `actual_inspection_quantity` int NOT NULL COMMENT '实际检验数量',
    `sample_no` int NOT NULL COMMENT '逐件样本序号',
    `item_code` varchar(64) NOT NULL COMMENT '检验项目编码',
    `item_name` varchar(128) NOT NULL COMMENT '检验项目名称',
    `inspection_method` varchar(512) NOT NULL COMMENT '检验方法快照',
    `standard_text` varchar(1024) NOT NULL COMMENT '合格标准快照',
    `selected_equipment_id` bigint DEFAULT NULL COMMENT '实际检验设备ID快照',
    `selected_equipment_code` varchar(64) DEFAULT NULL COMMENT '实际检验设备编码快照',
    `selected_equipment_name` varchar(128) DEFAULT NULL COMMENT '实际检验设备名称快照',
    `selected_equipment_number` varchar(64) DEFAULT NULL COMMENT '实际检验设备编号快照',
    `standard_lower_limit` decimal(18,6) DEFAULT NULL COMMENT '接收标准下限快照',
    `standard_upper_limit` decimal(18,6) DEFAULT NULL COMMENT '接收标准上限快照',
    `standard_unit` varchar(32) DEFAULT NULL COMMENT '接收标准单位快照',
    `standard_precision` int DEFAULT NULL COMMENT '接收标准小数位快照',
    `result_type` varchar(32) NOT NULL COMMENT '结果类型',
    `item_result` varchar(64) DEFAULT NULL COMMENT '检验结果',
    `measured_value` varchar(128) NOT NULL COMMENT '实测值',
    `judgement` varchar(32) NOT NULL COMMENT '判定',
    `aggregated_at` datetime NOT NULL COMMENT '过程检验汇集时间',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_mes_pqc_process_inspection_aggregate` (`tenant_id`, `event_id`, `source_piece_detail_id`, `deleted`),
    KEY `idx_mes_pqc_process_inspection_review` (`tenant_id`, `review_id`),
    KEY `idx_mes_pqc_process_inspection_task` (`tenant_id`, `pqc_task_id`, `sample_no`),
    KEY `idx_mes_pqc_process_inspection_submit_event` (`tenant_id`, `production_submit_event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES PQC 过程检验汇集明细';

ALTER TABLE `mes_pqc_inspection_task`
    MODIFY COLUMN `task_status` varchar(32) NOT NULL COMMENT '任务状态：PENDING/SUBMITTED/CONFIRMED/CANCELLED';
