package cn.iocoder.yudao.module.mes;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class MesProEdhrReleaseServiceImplTest {

    private static final Pattern M4_PLACEHOLDER_PATTERN = Pattern.compile(
            "buildSourceNotIntegratedItem\\([\\s\\S]*?(CHECK_INSPECTION_RESULT|CHECK_DEVIATION_CLOSED|CHECK_REWORK_CLOSED|CHECK_SCRAP_RECORDED|CHECK_INVENTORY_CONSISTENCY)");

    @Test
    void releasePrecheckMustUseFormalM4SourceAdaptersInsteadOfSourceNotIntegratedPlaceholders() throws Exception {
        String source = Files.readString(resolveBackendPath(
                "yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/batchrecord/MesProEdhrReleaseServiceImpl.java"),
                StandardCharsets.UTF_8);

        assertFalse(M4_PLACEHOLDER_PATTERN.matcher(source).find(),
                "M4 release checks must not be generated by source-not-integrated placeholders.");
        assertTrue(source.contains("MesOrderReleaseCompletenessService"),
                "Release service must depend on the formal M4 completeness source adapter.");
        assertTrue(source.contains("evaluateInspectionResult"));
        assertTrue(source.contains("evaluateDeviationClosed"));
        assertTrue(source.contains("evaluateReworkClosed"));
        assertTrue(source.contains("evaluateScrapRecorded"));
        assertTrue(source.contains("evaluateInventoryConsistency"));
    }

    @Test
    void completenessSourceAdapterMustExposeAllReleaseCheckMethods() throws Exception {
        Class<?> serviceClass = Class.forName(
                "cn.iocoder.yudao.module.mes.service.pro.batchrecord.MesOrderReleaseCompletenessService");
        Class<?> batchClass = Class.forName(
                "cn.iocoder.yudao.module.mes.dal.dataobject.pro.batchrecord.MesProEdhrBatchExecutionDO");
        Class<?> resultClass = Class.forName(
                "cn.iocoder.yudao.module.mes.service.pro.batchrecord.MesOrderReleaseCompletenessCheck");

        for (String methodName : new String[]{
                "evaluateInspectionResult",
                "evaluateDeviationClosed",
                "evaluateReworkClosed",
                "evaluateScrapRecorded",
                "evaluateInventoryConsistency"}) {
            Method method = serviceClass.getDeclaredMethod(methodName, batchClass);
            assertTrue(resultClass.isAssignableFrom(method.getReturnType()), methodName);
        }
    }

    private static Path resolveBackendPath(String relative) {
        Path cwd = Paths.get("").toAbsolutePath();
        if ("yudao-module-mes".equals(cwd.getFileName().toString())) {
            return cwd.getParent().resolve(relative);
        }
        if ("IntRuoyiBackend".equals(cwd.getFileName().toString())) {
            return cwd.resolve(relative);
        }
        return cwd.resolve("IntRuoyiBackend").resolve(relative);
    }
}
