package cn.iocoder.yudao.module.mes.productionrelease.core;

public enum MesReleaseFlowBlockerType {
    PRODUCTION_PROGRESS_NOT_COMPLETED,
    PRODUCTION_QUANTITY_CONFLICT,
    INSPECTION_PROGRESS_NOT_COMPLETED,
    ACTIVE_ORDER_LEADER_FORBIDDEN,
    PQC_RELEASE_ROLE_REQUIRED,
    MANAGEMENT_REPRESENTATIVE_ROLE_REQUIRED,
    WORK_TASK_NOT_PROCESSABLE,
    STATE_VERSION_CONFLICT,
    IDEMPOTENCY_KEY_INVALID,
    IDEMPOTENCY_PAYLOAD_CONFLICT,
    FROZEN_ROUTE_SOURCE_REQUIRED,
    BATCH_RECORD_SOURCE_REQUIRED,
    PROCESS_INSPECTION_SOURCE_REQUIRED,
    LOSS_REPORT_SOURCE_REQUIRED,
    LEGACY_RELEASE_APPLICATION_MIGRATION_REQUIRED,
    LEGACY_BATCH_EXECUTION_MIGRATION_REQUIRED,
    REPORT_OWNER_REQUIRED,
    REPORT_ATTACHMENT_REQUIRED,
    REPORT_NODE_NOT_PROCESSABLE,
    REPORT_NODE_SKIP_FORBIDDEN,
    REPORT_ATTACHMENT_LOCKED,
    REPORT_SNAPSHOT_CHANGED,
    RELEASE_TRANSACTION_NOT_PROCESSABLE,
    UNSUPPORTED_RELEASE_ACTION
}
