-- release-migration: allowedEnvironments=test,backup,prod; dependsOn=20260730_mes_process_pool_fifo_allocation; type=schema; riskLevel=medium
-- MES 生产一线工序池 F5：审核副本上下限修正

CREATE TABLE IF NOT EXISTS `mes_pro_process_pool_review_copy` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `event_id` bigint NOT NULL COMMENT '来源工序池提交事件ID',
    `process_pool_id` bigint NOT NULL COMMENT '来源工序池ID',
    `work_order_id` bigint NOT NULL COMMENT '生产工单ID',
    `route_id` bigint NOT NULL COMMENT '工艺路线ID',
    `route_process_id` bigint NOT NULL COMMENT '工艺路线工序ID',
    `process_id` bigint NOT NULL COMMENT '工序ID',
    `feedback_source_type` varchar(64) NOT NULL COMMENT '报工来源类型',
    `feedback_source_id` bigint NOT NULL COMMENT '报工来源ID',
    `recordbook_source_type` varchar(64) NOT NULL COMMENT '记录本来源类型',
    `recordbook_source_id` bigint NOT NULL COMMENT '记录本来源ID',
    `raw_payload_snapshot` json NOT NULL COMMENT '原始 payload 快照',
    `review_status` varchar(32) NOT NULL COMMENT '审核副本状态',
    `reviewer_user_id` bigint NOT NULL COMMENT '审核人用户ID',
    `reviewer_signature_id` bigint NOT NULL COMMENT '审核电子签名ID',
    `reviewer_signature_user_id` bigint NOT NULL COMMENT '审核电子签名用户ID',
    `reviewer_signature_snapshot` json NOT NULL COMMENT '审核电子签名快照',
    `reviewed_at` datetime NOT NULL COMMENT '服务端审核时间',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_mes_pp_review_copy_signature` (`tenant_id`, `reviewer_signature_id`, `deleted`),
    KEY `idx_mes_pp_review_copy_event` (`tenant_id`, `event_id`),
    KEY `idx_mes_pp_review_copy_pool` (`tenant_id`, `process_pool_id`),
    KEY `idx_mes_pp_review_copy_reviewer` (`tenant_id`, `reviewer_user_id`, `reviewed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 工序池审核副本';

CREATE TABLE IF NOT EXISTS `mes_pro_process_pool_review_copy_field` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '编号',
    `review_copy_id` bigint NOT NULL COMMENT '审核副本ID',
    `event_id` bigint NOT NULL COMMENT '来源工序池提交事件ID',
    `source_quantity_fragment_id` bigint DEFAULT NULL COMMENT '来源数量片段ID',
    `field_code` varchar(128) NOT NULL COMMENT '字段编码',
    `field_name` varchar(255) NOT NULL COMMENT '字段名称',
    `raw_value` varchar(1000) NOT NULL COMMENT '原始值',
    `corrected_value` varchar(1000) NOT NULL COMMENT '修正值',
    `rule_type` varchar(32) NOT NULL COMMENT '修正规则',
    `lower_limit` decimal(24,6) NOT NULL COMMENT '下限',
    `upper_limit` decimal(24,6) NOT NULL COMMENT '上限',
    `value_type` varchar(32) DEFAULT NULL COMMENT '字段值类型',
    `affects_allocation` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否影响 FIFO 分配',
    `feedback_source_type` varchar(64) NOT NULL COMMENT '报工来源类型',
    `feedback_source_id` bigint NOT NULL COMMENT '报工来源ID',
    `recordbook_source_type` varchar(64) NOT NULL COMMENT '记录本来源类型',
    `recordbook_source_id` bigint NOT NULL COMMENT '记录本来源ID',
    `template_field_metadata_json` json NOT NULL COMMENT '模板字段元数据快照',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_mes_pp_review_copy_field_copy` (`tenant_id`, `review_copy_id`),
    KEY `idx_mes_pp_review_copy_field_event` (`tenant_id`, `event_id`, `field_code`),
    KEY `idx_mes_pp_review_copy_field_fragment` (`tenant_id`, `source_quantity_fragment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES 工序池审核副本字段明细';
