CREATE TABLE mes_pqc_inspection_piece_detail (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL,
    task_id bigint NOT NULL,
    sample_no int NOT NULL,
    item_code varchar(64) NOT NULL,
    measured_value varchar(64) NOT NULL,
    deleted boolean NOT NULL DEFAULT FALSE,
    current_sample_no int GENERATED ALWAYS AS (CASE WHEN deleted=FALSE THEN sample_no ELSE NULL END),
    CONSTRAINT uk_mes_pqc_piece_current UNIQUE (tenant_id, task_id, current_sample_no, item_code)
);
