-- Private H2 equivalents of 20260717_bpm_form_center.sql and the BPM test schema.
-- These tables are not runtime migrations. Preserve actual columns and unique identities.
CREATE TABLE IF NOT EXISTS bpm_form_action_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_code VARCHAR(128) NOT NULL,
    tenant_id BIGINT NOT NULL,
    policy_id BIGINT NOT NULL,
    applicant_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    data_domain VARCHAR(64) NOT NULL,
    system_code VARCHAR(64) NOT NULL,
    object_type VARCHAR(64) NOT NULL,
    object_id VARCHAR(128) NOT NULL,
    object_version VARCHAR(128) NOT NULL,
    action_code VARCHAR(64) NOT NULL,
    object_state VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    business_context_json CLOB NOT NULL,
    form_data_json CLOB,
    bpm_process_instance_id VARCHAR(128),
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (tenant_id, system_code, object_type, object_id, object_version, action_code, idempotency_key)
);
CREATE TABLE IF NOT EXISTS bpm_form_action_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    snapshot_type VARCHAR(32) NOT NULL,
    snapshot_version INT NOT NULL,
    form_data_json CLOB,
    business_context_json CLOB NOT NULL,
    attachment_ids_json CLOB,
    creator VARCHAR(64) DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (tenant_id, instance_id, snapshot_version)
);
