-- G21 read-only collection only; do not concatenate migration SQL. No session writes/DDL/routines.
-- Run in explicitly selected ruoyi-vue-pro; validator rejects different database.
SELECT JSON_OBJECT('kind','runtime','database',DATABASE(),'version',@@version,'hostname',@@hostname);
SELECT JSON_OBJECT('kind','table','table',TABLE_NAME,'engine',ENGINE,'collation',TABLE_COLLATION)
 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('bpm_form_action_instance','bpm_form_action_policy','bpm_form_action_snapshot','bpm_form_effect_execution','bpm_form_task_permission','bpm_form_template_version','dcc_category_approval_route','dcc_category_approval_route_node','dcc_controlled_file','dcc_controlled_file_access_log','dcc_controlled_file_checkout','dcc_controlled_file_master','dcc_controlled_file_name_claim','dcc_controlled_file_obsolete_audit','dcc_controlled_file_recognition_record','dcc_controlled_file_related_file','dcc_controlled_file_signature','dcc_controlled_file_task_assignee_snapshot','dcc_data_relation','dcc_file_category','dcc_file_directory','dcc_file_type_taxonomy','dcc_product_catalog','dcc_project_code','dcc_project_file_template_item','dcc_project_product_create_request','dcc_project_product_identity_claim','dcc_project_product_relation','dcc_publication_followup_batch','dcc_publication_impact_audit','dcc_publication_impact_task','dcc_publication_notification_candidate','dcc_publication_notification_candidate_reason','dcc_publication_relation_direction_snapshot','dcc_publication_relation_snapshot','dcc_publication_visibility_rule_snapshot','dcc_publication_visibility_user_snapshot','system_menu','system_notify_message','system_role_menu','system_tenant_package') ORDER BY TABLE_NAME;
SELECT JSON_OBJECT('kind','column','table',TABLE_NAME,'column',COLUMN_NAME,'type',COLUMN_TYPE,
 'nullable',IS_NULLABLE,'collation',COLLATION_NAME,'default',COLUMN_DEFAULT,'extra',EXTRA,'expression',GENERATION_EXPRESSION)
 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('bpm_form_action_instance','bpm_form_action_policy','bpm_form_action_snapshot','bpm_form_effect_execution','bpm_form_task_permission','bpm_form_template_version','dcc_category_approval_route','dcc_category_approval_route_node','dcc_controlled_file','dcc_controlled_file_access_log','dcc_controlled_file_checkout','dcc_controlled_file_master','dcc_controlled_file_name_claim','dcc_controlled_file_obsolete_audit','dcc_controlled_file_recognition_record','dcc_controlled_file_related_file','dcc_controlled_file_signature','dcc_controlled_file_task_assignee_snapshot','dcc_data_relation','dcc_file_category','dcc_file_directory','dcc_file_type_taxonomy','dcc_product_catalog','dcc_project_code','dcc_project_file_template_item','dcc_project_product_create_request','dcc_project_product_identity_claim','dcc_project_product_relation','dcc_publication_followup_batch','dcc_publication_impact_audit','dcc_publication_impact_task','dcc_publication_notification_candidate','dcc_publication_notification_candidate_reason','dcc_publication_relation_direction_snapshot','dcc_publication_relation_snapshot','dcc_publication_visibility_rule_snapshot','dcc_publication_visibility_user_snapshot','system_menu','system_notify_message','system_role_menu','system_tenant_package') ORDER BY TABLE_NAME,ORDINAL_POSITION;
SELECT JSON_OBJECT('kind','index','table',TABLE_NAME,'name',INDEX_NAME,'unique',NON_UNIQUE=0,
 'sequence',SEQ_IN_INDEX,'column',COLUMN_NAME,'prefix',SUB_PART,'direction',COLLATION,'expression',EXPRESSION,'type',INDEX_TYPE)
 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('bpm_form_action_instance','bpm_form_action_policy','bpm_form_action_snapshot','bpm_form_effect_execution','bpm_form_task_permission','bpm_form_template_version','dcc_category_approval_route','dcc_category_approval_route_node','dcc_controlled_file','dcc_controlled_file_access_log','dcc_controlled_file_checkout','dcc_controlled_file_master','dcc_controlled_file_name_claim','dcc_controlled_file_obsolete_audit','dcc_controlled_file_recognition_record','dcc_controlled_file_related_file','dcc_controlled_file_signature','dcc_controlled_file_task_assignee_snapshot','dcc_data_relation','dcc_file_category','dcc_file_directory','dcc_file_type_taxonomy','dcc_product_catalog','dcc_project_code','dcc_project_file_template_item','dcc_project_product_create_request','dcc_project_product_identity_claim','dcc_project_product_relation','dcc_publication_followup_batch','dcc_publication_impact_audit','dcc_publication_impact_task','dcc_publication_notification_candidate','dcc_publication_notification_candidate_reason','dcc_publication_relation_direction_snapshot','dcc_publication_relation_snapshot','dcc_publication_visibility_rule_snapshot','dcc_publication_visibility_user_snapshot','system_menu','system_notify_message','system_role_menu','system_tenant_package') ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX;
SELECT JSON_OBJECT('kind','ledger','migrationId',migration_id,'sha256',sha256,'status',status,'environment',target_environment)
 FROM infra_release_migration WHERE deleted=b'0' AND target_environment='test' AND migration_id IN ('20260513_dcc_base_schema','20260615_system_config_package_menu','20260710_dcc_product_catalog_database','20260717_bpm_form_center','20260719_dcc_file_type_taxonomy','20260815_system_notify_message_business_key') ORDER BY migration_id;
SELECT JSON_OBJECT('kind','scalar','name','route_empty_action_type','value',COUNT(*)) FROM dcc_category_approval_route WHERE action_type IS NULL OR BINARY action_type=BINARY '';
SELECT JSON_OBJECT('kind','scalar','name','notify_duplicate_business_keys','value',COUNT(*)) FROM
 (SELECT tenant_id,business_key FROM system_notify_message WHERE business_key IS NOT NULL GROUP BY tenant_id,business_key HAVING COUNT(*)>1) duplicate_keys;
