-- Read-only final schema capture; first and repeat collect the same complete affected-table facts.
SELECT JSON_OBJECT('kind','runtime','database',DATABASE(),'serverUuid',@@server_uuid,'version',@@version);
SELECT JSON_OBJECT('kind','table','table',TABLE_NAME,'engine',ENGINE,'charset',SUBSTRING_INDEX(TABLE_COLLATION,'_',1),'collation',TABLE_COLLATION)
 FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('dcc_application_round_link','dcc_controlled_file','dcc_controlled_file_access_log','dcc_controlled_file_master','dcc_controlled_file_name_claim','dcc_controlled_file_obsolete_audit','dcc_controlled_file_signature','dcc_controlled_file_task_assignee_snapshot','dcc_current_file_relation','dcc_current_file_relation_set','dcc_folder_template','dcc_folder_template_history','dcc_project_application_attributes','dcc_project_code','dcc_project_file_placement','dcc_project_file_reference','dcc_project_folder','dcc_project_product_create_request','dcc_project_reviewer_config','dcc_relation_arrangement','dcc_relation_change_command','dcc_relation_controlled_event','dcc_relation_notification_outbox','dcc_relation_remediation_task','dcc_workflow_lifecycle_event','dcc_workflow_obsolete_archive') ORDER BY TABLE_NAME;
SELECT JSON_OBJECT('kind','column','table',TABLE_NAME,'column',COLUMN_NAME,'type',COLUMN_TYPE,'nullable',IS_NULLABLE,
 'charset',CHARACTER_SET_NAME,'collation',COLLATION_NAME,'default',COLUMN_DEFAULT,'extra',EXTRA,'expression',GENERATION_EXPRESSION)
 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('dcc_application_round_link','dcc_controlled_file','dcc_controlled_file_access_log','dcc_controlled_file_master','dcc_controlled_file_name_claim','dcc_controlled_file_obsolete_audit','dcc_controlled_file_signature','dcc_controlled_file_task_assignee_snapshot','dcc_current_file_relation','dcc_current_file_relation_set','dcc_folder_template','dcc_folder_template_history','dcc_project_application_attributes','dcc_project_code','dcc_project_file_placement','dcc_project_file_reference','dcc_project_folder','dcc_project_product_create_request','dcc_project_reviewer_config','dcc_relation_arrangement','dcc_relation_change_command','dcc_relation_controlled_event','dcc_relation_notification_outbox','dcc_relation_remediation_task','dcc_workflow_lifecycle_event','dcc_workflow_obsolete_archive') ORDER BY TABLE_NAME,ORDINAL_POSITION;
SELECT JSON_OBJECT('kind','index','table',TABLE_NAME,'name',INDEX_NAME,'unique',NON_UNIQUE=0,'type',INDEX_TYPE,
 'sequence',SEQ_IN_INDEX,'column',COLUMN_NAME,'prefix',SUB_PART,'direction',COLLATION,'expression',EXPRESSION)
 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('dcc_application_round_link','dcc_controlled_file','dcc_controlled_file_access_log','dcc_controlled_file_master','dcc_controlled_file_name_claim','dcc_controlled_file_obsolete_audit','dcc_controlled_file_signature','dcc_controlled_file_task_assignee_snapshot','dcc_current_file_relation','dcc_current_file_relation_set','dcc_folder_template','dcc_folder_template_history','dcc_project_application_attributes','dcc_project_code','dcc_project_file_placement','dcc_project_file_reference','dcc_project_folder','dcc_project_product_create_request','dcc_project_reviewer_config','dcc_relation_arrangement','dcc_relation_change_command','dcc_relation_controlled_event','dcc_relation_notification_outbox','dcc_relation_remediation_task','dcc_workflow_lifecycle_event','dcc_workflow_obsolete_archive') ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX;
SELECT JSON_OBJECT('kind','ledger','migrationId',migration_id,'sha256',sha256,'status',status,'environment',target_environment)
 FROM infra_release_migration WHERE deleted=b'0' AND target_environment='test' AND migration_id IN ('20260513_dcc_base_schema','20260615_system_config_package_menu','20260710_dcc_product_catalog_database','20260717_bpm_form_center','20260719_dcc_file_type_taxonomy','20260815_system_notify_message_business_key') ORDER BY migration_id;
