package cn.iocoder.yudao.module.mes.service.pro.handoff;
import cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder;
import cn.iocoder.yudao.module.mes.dal.dataobject.pro.handoff.MesActiveOrderHandoffTaskDO;
import org.junit.jupiter.api.*;
import java.nio.file.*;
import static org.junit.jupiter.api.Assertions.*;
class MesActiveOrderHandoffContractTest {
 @AfterEach void clear(){TenantContextHolder.clear();}
 static MesActiveOrderHandoffTaskDO review(){var t=new MesActiveOrderHandoffTaskDO().setId(1900000000000000001L).setActiveOrderId(413L).setWorkOrderId(274L).setRouteProcessId(91L).setTaskType("PQC_REVIEW").setSourceType("PROCESS_POOL_EVENT").setSourceId(176L).setRoundId(701L).setCandidateUserSnapshot("343").setReason("签名复核").setStatus("TODO").setRowVersion(0).setNotificationOnly(false);
 t.setTenantId(1L);t.setActionUrl("/mes/pro/process-pool/pqc-leader?activeOrderId=413&eventId=176&handoffTaskId=1900000000000000001&roundId=701&handoffType=PQC_REVIEW");return t;}
 @Test void exactCycleSourceRoundAndUnsafeJavascriptIdArePreserved(){TenantContextHolder.setTenantId(1L);var t=review();assertDoesNotThrow(()->MesActiveOrderHandoffContract.validate(t));assertEquals("1900000000000000001",MesActiveOrderHandoffContract.actionQuery(t).get("handoffTaskId"));}
 @Test void alteredCycleRoundSourceAndOffsiteOrDuplicateQueryAreRejected(){for(String url:new String[]{review().getActionUrl().replace("activeOrderId=413","activeOrderId=414"),review().getActionUrl().replace("roundId=701","roundId=702"),review().getActionUrl().replace("eventId=176","eventId=177"),"https://example.invalid"+review().getActionUrl(),review().getActionUrl()+"&eventId=176"}){var t=review().setActionUrl(url);assertThrows(RuntimeException.class,()->MesActiveOrderHandoffContract.validate(t));}}
 @Test void processHandoffRequiresFormalProcessButOrderHandoffDdlAllowsNull()throws Exception{assertThrows(RuntimeException.class,()->MesActiveOrderHandoffContract.validate(review().setRouteProcessId(null)));String ddl=Files.readString(Path.of("../sql/mysql/20261005_mes_active_order_handoff.sql"));assertTrue(ddl.contains("route_process_id BIGINT NULL"));assertFalse(ddl.contains("FOREIGN KEY"));var t=review().setTaskType("PRODUCTION_HANDOFF").setSourceType("ACTIVE_ORDER").setSourceId(413L).setRoundId(413L).setRouteProcessId(null).setActionUrl("/mes/pro/feedback/edhr-batch-production-fill?activeOrderId=413&cycleId=413&handoffTaskId=1900000000000000001&roundId=413&handoffType=PRODUCTION_HANDOFF");assertDoesNotThrow(()->MesActiveOrderHandoffContract.validate(t));}
 @Test void tenantAndFrozenCandidateAreMandatory(){TenantContextHolder.setTenantId(1L);assertThrows(RuntimeException.class,()->MesActiveOrderHandoffContract.access(review(),344L));var t=review();t.setTenantId(2L);assertThrows(RuntimeException.class,()->MesActiveOrderHandoffContract.access(t,343L));assertThrows(RuntimeException.class,()->MesActiveOrderHandoffContract.candidates("343,343"));}
 @Test void voidDoneResultUsesOnlyPersonalNotificationRoute(){var t=review().setTaskType("QA_DECISION_HANDOFF").setSourceType("NONCONFORMANCE_REVIEW").setSourceId(91L).setRoundId(91L).setReason("void：签名作废").setStatus("DONE").setActionUrl("/user/profile?activeOrderId=413&reviewId=91&handoffTaskId=1900000000000000001&roundId=91&handoffType=QA_DECISION_HANDOFF&tab=notifyMessage");assertDoesNotThrow(()->MesActiveOrderHandoffContract.validate(t));assertThrows(RuntimeException.class,()->MesActiveOrderHandoffContract.validate(t.setStatus("TODO")));}
}
