package cn.iocoder.yudao.module.bpm.businessapproval.service;

public enum BusinessApprovalErrorCode {

    BUSINESS_APPROVAL_CONTEXT_INVALID,
    BUSINESS_APPROVAL_POLICY_NOT_FOUND,
    BUSINESS_APPROVAL_POLICY_CONFLICT,
    BUSINESS_APPROVAL_POLICY_STATUS_INVALID,
    BUSINESS_APPROVAL_MODE_INVALID,
    BUSINESS_APPROVAL_PROCESS_DEFINITION_MISSING,
    BUSINESS_APPROVAL_SIGNATURE_PASSWORD_REQUIRED,
    BUSINESS_APPROVAL_PROCESS_NOT_STARTED,
    BUSINESS_APPROVAL_EXECUTOR_MISSING,
    BUSINESS_APPROVAL_EXECUTOR_CONFLICT,
    BUSINESS_APPROVAL_REQUEST_NOT_FOUND,
    BUSINESS_APPROVAL_PENDING_CONFLICT,
    BUSINESS_APPROVAL_EVENT_STALE,
    BUSINESS_APPROVAL_EVENT_MISMATCH

}
