const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '../../../..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const importer = read('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/batchrecordreport/MesProBatchRecordRecognitionDeviceSyncService.java')
const runtime = read('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/frontline/MesFrontlineRuntimeConfigServiceImpl.java')
const submit = read('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/feedback/frontline/MesProFrontlineFeedbackSubmitServiceImpl.java')
const splitter = read('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/feedback/frontline/MesProFrontlineFeedbackPayloadSplitter.java')
const activeOrder = read('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesTeamLeaderActiveOrderServiceImpl.java')

assert.match(importer, /requireSelectionMode\(group\)/)
assert.match(importer, /\.deviceGroupKey\(groupKey\)\.selectionMode\(selectionMode\)/)
assert.match(importer, /processDeviceMapper\.updateById\(binding\.setDeviceGroupKey/)
assert.match(runtime, /getDeviceSelectionSnapshotJson\(\)/)
assert.match(runtime, /MesDeviceSelectionSnapshotCodec\.sha256\(selectionJson\)/)
assert.match(runtime, /frozenGroup\.selectionMode\(\)/)
assert.match(submit, /selectedDevice is no longer supported/)
assert.match(submit, /"SINGLE"\.equals\(allowed\.selectionMode\(\)\) && selectedCount > 1/)
assert.match(submit, /unselected device parameter/)
assert.match(splitter, /payload\.put\("selectedDevices", feedback\.getSelectedDevices\(\)\)/)
assert.match(activeOrder, /MesDeviceSelectionSnapshotCodec\.canonicalize/)
assert.match(activeOrder, /\.deviceSelectionSnapshotSha256\(MesDeviceSelectionSnapshotCodec\.sha256/)

console.log('PASS: backend frontline multi-device static contract')
