const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')
const root = path.resolve(__dirname, '../../../../')
const java = path.join(root, 'yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes')
const read = (name) => fs.readFileSync(path.join(java, name), 'utf8')
const batch = read('service/pro/batchrecord/MesProEdhrBatchExecutionServiceImpl.java')
const complete = batch.slice(batch.indexOf('public MesProductionReleaseReportNodeEvidence completeProductionReleaseReportNode('), batch.indexOf('public MesProductionReleaseReportNodeEvidence completePreReleaseDossierNode('))
assert(complete.includes('syncBatchStatus('), 'Report completion must persist batch readiness in its transaction')
const finalizer = read('service/pro/batchrecord/MesProEdhrReleaseServiceImpl.java')
assert(finalizer.includes('appendReleaseDecision('), 'Final release must append the application decision to traceability')
const adapter = read('approval/MesProEdhrApprovalTaskAdapter.java')
const approve = adapter.slice(adapter.indexOf('releaseService.approve('), adapter.indexOf('releaseService.reject('))
assert.match(approve, /setWorkTaskId\(workTaskId\)/, 'Approval center must pass the task it authorized')
console.log('PASS: merged release chain wiring')
