const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')
const backend = path.resolve(__dirname, '../../../../')
const read = (p) => fs.readFileSync(path.join(backend, p), 'utf8')
const manager = read('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/productionrelease/manager/MesProductionReleaseManagerApprovalServiceImpl.java')
assert(!manager.includes('BpmApprovalSignatureRecordMapper'), 'Manager must consume current unified signature evidence, not the retired projection')
const bpm = read('yudao-module-bpm/src/main/java/cn/iocoder/yudao/module/bpm/approval/service/signature/ApprovalSignatureRecordServiceImpl.java')
assert(bpm.includes('.evidenceHash(signature.evidenceHash())'), 'Return the persisted unified evidence hash')
assert(bpm.includes('.subjectId(subjectId)'), 'Return the exact signed subject identity')
console.log('PASS: unified manager signature source')
