const fs = require('fs')
const path = require('path')
const assert = require('assert')

const repoRoot = path.resolve(__dirname, '../../../../..')
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')

const flowGraphDesigner = read('yudao-ui-admin-vue3/src/views/mes/pro/route/RouteFlowGraphDesigner.vue')
const flowConfigApi = read('yudao-ui-admin-vue3/src/api/mes/pro/route/flowconfig.ts')
const routeProcessColumns = read('yudao-ui-admin-vue3/src/views/mes/pro/route/routeProcessSettingsColumns.ts')
const backendService = read('ruoyi-vue-pro/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/route/MesProRouteFlowConfigServiceImpl.java')
const routeBindingDO = read('ruoyi-vue-pro/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/dal/dataobject/pro/route/MesProRouteFlowProcessBatchRecordDO.java')
const taskDO = read('ruoyi-vue-pro/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/dal/dataobject/pro/batchrecord/MesProEdhrBatchExecutionTaskDO.java')
const runtimeService = read('ruoyi-vue-pro/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/batchrecord/MesProEdhrBatchExecutionServiceImpl.java')
const publishProjectionService = read('ruoyi-vue-pro/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/route/MesProRouteVersionPublishProjectionServiceImpl.java')
const workTaskService = read('ruoyi-vue-pro/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/batchrecord/MesProEdhrWorkTaskServiceImpl.java')
const saveVO = read('ruoyi-vue-pro/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/route/vo/flowconfig/MesProRouteFlowFormBindingSaveReqVO.java')
const respVO = read('ruoyi-vue-pro/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/route/vo/flowconfig/MesProRouteFlowFormBindingRespVO.java')

assert.match(flowConfigApi, /interface\s+ProRouteFlowFormBindingVO/, '前端 flow-config 必须定义动态表单绑定响应类型。')
assert.match(flowConfigApi, /interface\s+ProRouteFlowFormBindingSaveVO/, '前端 flow-config 必须定义动态表单绑定保存类型。')
assert.match(flowConfigApi, /formBindings\?:\s*ProRouteFlowFormBindingVO\[\]/, '前端响应必须使用 formBindings。')
assert.match(flowConfigApi, /formTemplateId:\s*number/, '前端保存类型必须只提交模板稳定 ID。')
assert.doesNotMatch(flowConfigApi, /formTemplateVersionNo|versionNo.*ProRouteFlowFormBindingSaveVO/s, '前端动态表单保存类型不得提交版本号。')
assert.doesNotMatch(flowConfigApi, /interface\s+ProRouteFlowFormBindingSaveVO[\s\S]*formSlotType/, '前端动态表单保存类型不得提交旧固定槽位 formSlotType。')
assert.match(flowConfigApi, /candidateSourceType\?:\s*EdhrProcessFormCandidateSourceType\s*\|\s*null/, '前端响应类型必须保存填写人来源。')
assert.match(flowConfigApi, /candidateSourceIds\?:\s*number\[\]/, '前端响应类型必须保存填写人 ID 列表。')
assert.match(flowConfigApi, /candidateSourceNames\?:\s*string\[\]/, '前端响应类型必须保存填写人名称快照。')

assert.match(flowGraphDesigner, /getTemplatePool/, '工序表单下拉必须读取表单中心模板池。')
assert.match(flowGraphDesigner, /data-flow-action="add-form-binding"/, '动态表单列表必须提供新增表单按钮。')
assert.match(flowGraphDesigner, /data-flow-action="copy-process-form-bindings"/, '动态表单列表必须提供复制其他工序整组表单配置按钮。')
assert.match(flowGraphDesigner, /data-flow-action="remove-form-binding"/, '动态表单列表必须提供删除表单按钮。')
assert.doesNotMatch(flowGraphDesigner, /data-flow-action="copy-form-binding"/, '动态表单列表不再展示单槽位复制红框按钮。')
assert.doesNotMatch(flowGraphDesigner, /data-flow-action="move-form-binding-up"/, '动态表单列表不再展示单槽位上移红框按钮。')
assert.doesNotMatch(flowGraphDesigner, /data-flow-action="move-form-binding-down"/, '动态表单列表不再展示单槽位下移红框按钮。')
assert.match(flowGraphDesigner, /formTemplateId/, '路线工序表单绑定必须按 formTemplateId 选择。')
assert.match(flowGraphDesigner, /formTemplateName/, '路线工序表单绑定必须展示模板名称快照。')
assert.match(flowGraphDesigner, /data-route-process-setting-field="process-independent-switch"/, '表单槽位必须提供工序独立开关。')
assert.match(flowGraphDesigner, /data-route-process-setting-field="candidate-source-type"/, '表单槽位必须提供填写人来源选择。')
assert.match(flowGraphDesigner, /data-route-process-setting-field="candidate-source-id"/, '表单槽位必须提供填写人选择器。')
assert.match(flowGraphDesigner, /validateRecordBindingCandidateSource/, '前端保存前必须阻断已选表单但缺少填写人。')
assert.match(flowGraphDesigner, /candidateSourceType:\s*binding\.candidateSourceType/, '保存 payload 必须提交填写人来源。')
assert.match(flowGraphDesigner, /candidateSourceIds:\s*binding\.candidateSourceIds/, '保存 payload 必须提交填写人 ID。')
assert.match(flowGraphDesigner, /candidateSourceNames:\s*binding\.candidateSourceNames/, '保存 payload 必须提交填写人名称快照。')
assert.match(flowGraphDesigner, /validateDuplicateFormTemplate/, '前端保存前必须阻断同一工序重复模板。')
assert.doesNotMatch(flowGraphDesigner, /buildFormBindingSaveRows[\s\S]*formSlotType:/, '前端动态表单保存 payload 不得提交旧固定槽位 formSlotType。')
assert.match(flowGraphDesigner, /getChangedSelectedProcessScheduleDrafts/, '前端必须单独判断排产属性变更。')
assert.match(flowGraphDesigner, /getChangedSelectedProcessRecordBindingDrafts/, '前端必须单独判断动态表单绑定变更。')
assert.match(flowGraphDesigner, /scheduleChangedDrafts\.length > 0[\s\S]*saveScheduleConfig/, '只有排产属性变更时才保存排产配置。')
assert.match(flowGraphDesigner, /recordBindingChangedDrafts\.length > 0[\s\S]*saveBatchRecordConfig/, '只有动态表单绑定变更时才保存表单绑定配置。')
assert.doesNotMatch(flowGraphDesigner, /const\s+changedDrafts\s*=\s*getChangedSelectedProcessAttributeDrafts\(\)[\s\S]*saveScheduleConfig[\s\S]*saveBatchRecordConfig/, '动态表单保存不得与排产配置保存共用同一变更集合。')
assert.doesNotMatch(flowGraphDesigner, /const\s+RECORD_BINDING_TYPES/, '前端不得再固定 MAIN/LOSS/检验/参数四个槽位。')
assert.doesNotMatch(flowGraphDesigner, /BatchRecordReportApi\.getGeneratedReportPage/, '动态表单下拉不得再读取批记录报表选项。')
assert.doesNotMatch(flowGraphDesigner, /batchRecordReports:\s*processConfig\.batchRecordReports/, '保存 payload 不得继续提交旧 batchRecordReports。')

assert.match(routeProcessColumns, /'batchRecordFormNames'/, '工序设置列必须保留批记录表单 MAIN 展示列。')
assert.doesNotMatch(routeProcessColumns, /lossReportFormNames|processInspectionFormNames|parameterRecordFormNames/, '工序设置列不得保留损耗、检验、参数固定槽位列。')
assert.match(routeProcessColumns, /'formSlots'/, '工序设置列保留动态表单汇总列。')

assert.match(routeBindingDO, /private String formBindingKey;/, '路线工序绑定 DO 必须保存稳定 formBindingKey。')
assert.match(routeBindingDO, /private Long formTemplateId;/, '路线工序绑定 DO 必须保存 formTemplateId。')
assert.match(routeBindingDO, /private String formTemplateNameSnapshot;/, '路线工序绑定 DO 必须保存模板名称快照。')
assert.match(routeBindingDO, /private Long lastPublishedTemplateVersionId;/, '路线工序绑定 DO 必须保存最后校验的发布版本 ID。')
assert.match(routeBindingDO, /private String lastPublishedTemplateVersionNo;/, '路线工序绑定 DO 必须保存最后校验的发布版本号。')
assert.match(routeBindingDO, /private String candidateSourceType;/, '路线工序绑定 DO 必须保存填写人来源快照。')
assert.match(routeBindingDO, /private String candidateSourceIds;/, '路线工序绑定 DO 必须保存填写人 ID 快照。')
assert.match(routeBindingDO, /private String candidateSourceNames;/, '路线工序绑定 DO 必须保存填写人名称快照。')
assert.match(saveVO, /private String candidateSourceType;/, '后端保存 VO 必须接收填写人来源。')
assert.match(saveVO, /private List<Long> candidateSourceIds;/, '后端保存 VO 必须接收填写人 ID 列表。')
assert.match(saveVO, /private List<String> candidateSourceNames;/, '后端保存 VO 必须接收填写人名称快照。')
assert.match(respVO, /private String candidateSourceType;/, '后端响应 VO 必须返回填写人来源。')
assert.match(respVO, /private List<Long> candidateSourceIds;/, '后端响应 VO 必须返回填写人 ID 列表。')
assert.match(respVO, /private List<String> candidateSourceNames;/, '后端响应 VO 必须返回填写人名称快照。')

assert.match(backendService, /FormTemplateVersionMapper/, '路线配置保存必须接入表单中心模板版本 Mapper。')
assert.match(backendService, /selectLatestPublishedByTemplateId/, '路线配置保存必须按 templateId 校验最新已发布版本。')
assert.match(backendService, /PRO_ROUTE_FLOW_CONFIG_FORM_TEMPLATE_DUPLICATE/, '后端必须对同一工序重复模板 fail fast。')
assert.match(backendService, /PRO_ROUTE_FLOW_CONFIG_FORM_TEMPLATE_PUBLISHED_VERSION_NOT_EXISTS/, '后端必须对缺少发布版本 fail fast。')
assert.match(backendService, /AdminUserApi/, '后端必须校验个人填写人 ID。')
assert.match(backendService, /RoleApi/, '后端必须校验权限角色 ID。')
assert.match(backendService, /validateFormBindingCandidateSource/, '后端保存必须校验动态表单槽位填写人配置。')
assert.doesNotMatch(backendService, /validateBatchProcessConfig[\s\S]*loadReportMap\(reportIds\)/, '新配置保存不得再按批记录报表存在性作为兜底。')

assert.match(publishProjectionService, /MesProEdhrProcessFormPermissionRuleMapper/, '发布投影必须写入工序表单填写人规则。')
assert.match(publishProjectionService, /syncRouteFormFillRule/, '发布投影必须把槽位填写人同步为 FILL 规则。')
assert.match(publishProjectionService, /candidateSourceType/, '发布投影必须读取槽位填写人来源。')
assert.match(publishProjectionService, /candidateSourceIds/, '发布投影必须读取槽位填写人 ID。')
assert.match(workTaskService, /resolveProcessFormRuleBindingKey/, '运行态填写规则查找必须支持动态 formBindingKey。')

assert.match(taskDO, /private String formBindingKey;/, 'eDHR 任务必须保存 formBindingKey。')
assert.match(taskDO, /private Long formTemplateId;/, 'eDHR 任务必须保存表单中心 templateId。')
assert.match(taskDO, /private Long formTemplateVersionId;/, 'eDHR 任务必须保存运行时发布版本 ID 快照。')
assert.match(taskDO, /private String formTemplateVersionNo;/, 'eDHR 任务必须保存运行时发布版本号快照。')
assert.match(taskDO, /private Long formCenterInstanceId;/, 'eDHR 任务必须保存表单中心实例 ID。')
assert.match(runtimeService, /FormCenterRuntimeService/, 'eDHR 运行态必须通过表单中心创建实例。')
assert.match(runtimeService, /MES_EDHR_ROUTE_FORM_FILL/, 'eDHR 路线表单填写必须注册专用 effect executor。')
assert.match(runtimeService, /selectLatestPublishedByTemplateId/, 'eDHR 运行态必须按 templateId 解析最新已发布版本。')
assert.match(runtimeService, /formCenterRuntimeService\.createInstance/, 'eDHR 任务生成必须创建表单中心实例。')
assert.doesNotMatch(runtimeService, /selectById\(\s*batchRecord\.getLastPublishedTemplateVersionId\(\)/, 'eDHR 运行态不得锁死保存时校验版本。')
assert.doesNotMatch(runtimeService, /validateRouteFormBinding[\s\S]*batchRecordReportId/, '运行态绑定校验不得依赖旧批记录报表 ID。')

console.log('mes-route-dynamic-form-slots-static PASS')
