const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '../../..')
const backendRoot = path.resolve(root, '..')
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

const reqVo = read('src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/productionrelease/vo/MesPqcProductionReleaseApproveReqVO.java')
const command = read('src/main/java/cn/iocoder/yudao/module/mes/service/pro/productionrelease/pqc/MesPqcProductionReleaseApproveCommand.java')
const service = read('src/main/java/cn/iocoder/yudao/module/mes/service/pro/productionrelease/pqc/MesPqcProductionReleaseServiceImpl.java')
const udiPolicy = read('src/main/java/cn/iocoder/yudao/module/mes/service/pro/productionrelease/pqc/MesPqcProductionReleaseUdiPolicy.java')
const activeOrder = read('src/main/java/cn/iocoder/yudao/module/mes/dal/dataobject/pro/processpool/team/MesProcessPoolActiveOrderDO.java')
const activeOrderMapper = read('src/main/java/cn/iocoder/yudao/module/mes/dal/mysql/pro/processpool/team/MesProcessPoolActiveOrderMapper.java')
const detailModel = read('src/main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesTeamLeaderActiveOrderDetail.java')
const detailVo = read('src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/processpool/team/vo/MesTeamLeaderActiveOrderDetailRespVO.java')
const detailService = read('src/main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesTeamLeaderActiveOrderDetailServiceImpl.java')
const detailController = read('src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/processpool/team/MesProcessPoolTeamLeaderController.java')
const readFront = (relativePath) => fs.readFileSync(path.join(backendRoot, '../IntRuoyiFronted', relativePath), 'utf8')
const frontApi = readFront('src/api/mes/pro/productionRelease/index.ts')
const frontPage = readFront('src/views/mes/pro/production-release/PqcProductionReleasePage.vue')
const frontDetailApi = readFront('src/api/mes/pro/processpool/teamLeader.ts')
const frontDetail = readFront('src/views/mes/pro/processpool/components/ActiveOrderSubmissionDetailPanel.vue')
const migrationPath = 'sql/mysql/20260924_mes_pqc_release_udi_document_no.sql'

test('approve contract carries a required trimmed UDI document number', () => {
  assert.match(reqVo, /@NotBlank[\s\S]*private String udiControlDocumentNo;/)
  assert.match(command, /private String udiControlDocumentNo;/)
  assert.match(service, /requireUdiControlDocumentNo\(/)
  assert.match(udiPolicy, /MAX_LENGTH = 128/)
})

test('approve persists only against the formal application active order and rejects conflicts', () => {
  assert.match(service, /application\.getActiveOrderId\(\)/)
  assert.match(service, /selectByIdForUpdate\(application\.getActiveOrderId\(\)\)/)
  assert.match(service, /udiControlDocumentNo/)
  assert.match(udiPolicy, /不同的UDI编号|不能覆盖/i)
  assert.match(activeOrder, /private String udiControlDocumentNo;/)
  assert.match(activeOrderMapper, /writeUdiControlDocumentNo/)
})

test('UDI document number participates in idempotency payload hash and detail response', () => {
  assert.match(service, /decisionPayloadHash\([^;]*udiControlDocumentNo/s)
  assert.match(detailModel, /private String udiControlDocumentNo;/)
  assert.match(detailVo, /private String udiControlDocumentNo;/)
  assert.match(detailService, /setUdiControlDocumentNo\(activeOrder\.getUdiControlDocumentNo\(\)\)/)
  assert.match(detailController, /setUdiControlDocumentNo\(detail\.getUdiControlDocumentNo\(\)\)/)
})

test('migration is explicit and frontend exposes input plus readonly detail', () => {
  assert.ok(fs.existsSync(path.join(backendRoot, migrationPath)), `missing ${migrationPath}`)
  const migration = fs.readFileSync(path.join(backendRoot, migrationPath), 'utf8')
  assert.match(migration, /release-migration: allowedEnvironments=test,backup,prod;/)
  assert.match(migration, /udi_control_document_no/)
  assert.match(frontApi, /udiControlDocumentNo: string/)
  assert.match(frontPage, /label="UDI编号"/)
  assert.doesNotMatch(frontPage, /线下 UDI 文件编号/)
  assert.match(frontPage, /data-pqc-production-release-udi-document-no/)
  assert.match(frontPage, /v-model="releaseForm\.udiControlDocumentNo"/)
  assert.match(frontDetailApi, /udiControlDocumentNo\?: string/)
  assert.match(frontDetail, /<th>UDI编号<\/th>/)
  assert.doesNotMatch(frontDetail, /线下 UDI 文件编号/)
  assert.match(frontDetail, /detail\.udiControlDocumentNo \|\| '未填写'/)
})
