const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const moduleRoot = path.resolve(__dirname, '..', '..')
const servicePath = path.join(moduleRoot, 'main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesReportAllocationCommandService.java')
const reviewServicePath = path.join(moduleRoot, 'main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesTeamLeaderSubmissionReviewServiceImpl.java')
const auditPath = path.join(moduleRoot, 'main/java/cn/iocoder/yudao/module/mes/dal/dataobject/pro/processpool/team/MesProcessPoolReportAllocationAdjustmentAuditDO.java')
const mapperPath = path.join(moduleRoot, 'main/resources/mapper/pro/processpool/MesProProcessPoolTimelineReadMapper.xml')
const source = fs.readFileSync(servicePath, 'utf8')
const review = fs.readFileSync(reviewServicePath, 'utf8')
const audit = fs.readFileSync(auditPath, 'utf8')
const mapper = fs.readFileSync(mapperPath, 'utf8')

assert.match(review, /LEADER_TYPE_PRODUCTION[\s\S]*STATUS_REJECTED[\s\S]*rejectProductionSubmission/)
assert.match(source, /@Transactional\(rollbackFor = Exception\.class\)[\s\S]*rejectProductionSubmission/)
assert.match(source, /EVENT_TYPE_PRODUCTION_SUBMIT/)
assert.match(source, /findReleasedActiveOrderIdsForUpdate/)
assert.match(source, /supersedeCurrentRows/)
assert.match(source, /rebuildForVersion\(event, rejectedVersion, List\.of\(\)\)/)
assert.match(source, /reconcileAffectedAllocations/)
assert.match(source, /deleteById\(existingReview\.getId\(\)\)/)
assert.match(source, /STATUS_REJECTED/)
assert.match(audit, /SOURCE_SUBMISSION_REJECTED/)
assert.match(mapper, /allocationView == 'WORKBENCH'[\s\S]*REJECTED/)
assert.match(source, /STATUS_REJECTED[\s\S]*SUBMISSION_REVIEW_TERMINAL_EXISTS/)

console.log('PASS production-report-rejection-backend-static')
