const assert = require('assert')
const fs = require('fs')
const path = require('path')

const repoRoot = path.resolve(__dirname, '..', '..', '..')
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')

const domain = read('IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesTeamLeaderActiveOrderDetail.java')
const service = read('IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesTeamLeaderActiveOrderDetailServiceImpl.java')
const vo = read('IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/processpool/team/vo/MesTeamLeaderActiveOrderDetailRespVO.java')
const controller = read('IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/processpool/team/MesProcessPoolTeamLeaderController.java')
const api = read('IntRuoyiFronted/src/api/mes/pro/processpool/teamLeader.ts')
const edhrPage = read('IntRuoyiFronted/src/views/mes/pro/edhr-batch/BatchExecutionActiveOrderDetailPage.vue')
const activeOrderPage = read('IntRuoyiFronted/src/views/mes/pro/processpool/ActiveOrderSubmissionDetailPage.vue')
const detailPanel = read('IntRuoyiFronted/src/views/mes/pro/processpool/components/ActiveOrderSubmissionDetailPanel.vue')

assert.match(domain, /private ActiveOrderStatusSummary activeOrderStatus;/, '详情领域模型必须返回 activeOrderStatus。')
assert.match(domain, /class ActiveOrderStatusSummary[\s\S]*private String status;[\s\S]*private String statusLabel;/, '活跃订单状态摘要必须包含状态码和显示文本。')
assert.match(vo, /private ActiveOrderStatusSummary activeOrderStatus;/, '详情响应 VO 必须透出 activeOrderStatus。')
assert.match(controller, /\.setActiveOrderStatus\(toActiveOrderStatusSummaryRespVO\(detail\.getActiveOrderStatus\(\)\)\)/, 'Controller 映射必须复制 activeOrderStatus。')
assert.match(service, /resolveActiveOrderStatus\(application\)/, '详情服务必须从最新放行申请解析统一状态。')
assert.match(service, /"NOT_APPLIED"[\s\S]*"未申请"/, '无放行申请必须显示未申请。')
assert.match(service, /MesReleaseFlowStatus\.PQC_RELEASE_PENDING[\s\S]*"待PQC放行"/, '待 PQC 放行状态必须显示待PQC放行。')
assert.match(service, /MesReleaseFlowStatus\.PQC_RELEASE_REJECTED[\s\S]*"待审查"/, 'PQC 拒绝状态必须显示待审查。')
assert.match(service, /nonconformanceReviewMapper\.selectLatestBySource\("PQC_RELEASE",\s*application\.getId\(\)\)/, 'PQC 拒绝后的详情状态必须读取对应不合格评审终态。')
assert.match(service, /"VOIDED"[\s\S]*"已作废"/, 'PQC 拒绝后不合格评审处置为作废时必须显示已作废。')
assert.match(service, /MesReleaseFlowStatus\.MANAGER_RELEASE_PENDING[\s\S]*"待上市放行"/, 'PQC 通过后、上市前必须显示待上市放行。')
assert.match(service, /MesReleaseFlowStatus\.RELEASED[\s\S]*"已上市放行"/, '最终放行完成必须显示已上市放行。')
assert.match(api, /activeOrderStatus\?: TeamLeaderActiveOrderStatusSummaryRespVO/, '前端 API 类型必须包含 activeOrderStatus。')
assert.match(edhrPage, /<ActiveOrderSubmissionDetailPanel/, 'eDHR 详情页必须复用活跃订单详情公共面板。')
assert.match(activeOrderPage, /<ActiveOrderSubmissionDetailPanel/, '生产组长活跃订单详情页必须复用活跃订单详情公共面板。')
assert.match(detailPanel, /data-active-order-current-status/, '公共详情面板必须有当前状态展示节点。')
assert.match(detailPanel, /detail\.activeOrderStatus\?\.statusLabel/, '公共详情面板必须展示后端返回的状态文本。')
assert.match(detailPanel, /team-leader-workbench__active-order-detail-record-boundary[\s\S]*grid-template-columns:\s*1fr auto 1fr/, '当前状态必须位于详情批记录栏中间。')

console.log('PASS active-order-detail-current-status-static')
