const assert = require('node:assert/strict')
const path = require('node:path')
const fs = require('node:fs')
const test = require('node:test')
const { ESLint } = require('eslint')
const { parse, compileTemplate } = require('vue/compiler-sfc')

test('active order layout passes project lint and preserves its default slot', async () => {
  const root = path.resolve(__dirname, '../..')
  const filename = path.join(root, 'src/views/mes/pro/processpool/components/ActiveOrderDetailLayout.vue')
  const results = await new ESLint({ cwd: root }).lintFiles([filename])
  assert.deepEqual(results.flatMap(result => result.messages), [])
  const { descriptor, errors } = parse(fs.readFileSync(filename, 'utf8'))
  assert.deepEqual(errors, [])
  const template = compileTemplate({ source: descriptor.template.content, filename, id: 'active-order-layout' })
  assert.deepEqual(template.errors, [])
  assert.match(template.code, /_renderSlot\(_ctx\.\$slots, "default"\)/)
  assert.match(descriptor.styles[0].content, /overflow-x:\s*hidden/)
})
