const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

const root = path.resolve(__dirname, '../..')
const read = (relativePath) =>
  fs.readFileSync(path.join(root, relativePath), 'utf8').replace(/\r\n/g, '\n')

const dialog = read('src/views/mes/pro/batchrecordformlist/BatchRecordCellRulesConfirmDialog.vue')
const template = dialog.slice(dialog.indexOf('<template>'), dialog.indexOf('<script setup'))
const script = dialog.slice(dialog.indexOf('<script setup'), dialog.indexOf('</script>'))

const includes = (content, token, message) => assert.ok(content.includes(token), message)
const notIncludes = (content, token, message) => assert.ok(!content.includes(token), message)

includes(script, 'const resolveSelectedPropertyTargetKeys = () =>', '属性修改必须先解析当前多选目标集合。')
includes(script, 'const ensureRulesForKeys = (keys: string[]) =>', '批量属性修改必须能为全部已选格子创建正式规则。')
includes(script, 'const setSelectedRulesFillable = (value: boolean) => {', '可填写状态必须支持应用到全部已选格子。')
includes(script, 'const setSelectedRulesRequired = (value: boolean) => {', '必填状态必须支持应用到全部已选格子。')
includes(script, 'const setSelectedRulesComponentFlag = (value: string) => {', '控件类型必须支持应用到全部已选格子。')
includes(script, 'const applyValueTypeToRuleKeys = async (', '字段类型必须通过统一批量类型函数处理。')
includes(script, 'const selectedPropertyTargetKeys = computed(() => resolveSelectedPropertyTargetKeys())', '右侧属性面板必须以当前多选集合作为属性读取目标。')
includes(script, 'const isSelectedPropertyFillable = computed(() =>', '可填写开关必须按多选集合计算，不得只看最后焦点格。')
includes(script, 'const isSelectedPropertyRequired = computed(() =>', '必填开关必须按多选集合计算，不得只看最后焦点格。')
includes(script, 'const selectedPropertyValueType = computed(() =>', '字段类型选择必须按多选集合计算，不得只看最后焦点格。')
includes(script, 'const selectedPropertyComponentFlag = computed(() =>', '控件类型选择必须按多选集合计算，不得只看最后焦点格。')
includes(script, 'await applyValueTypeToRuleKeys(resolveSelectedPropertyTargetKeys(), value)', '右侧字段类型选择必须作用到多选集合，而不是只改焦点格。')
includes(template, '@change="handleSelectedFillableChange"', '可填写开关必须走多选感知处理器。')
includes(template, '@change="handleSelectedRequiredChange"', '必填开关必须走多选感知处理器。')
includes(template, '@change="handleSelectedComponentFlagChange"', '控件类型选择必须走多选感知处理器。')
includes(template, ':model-value="isSelectedPropertyFillable"', '可填写开关显示值必须来自多选集合。')
includes(template, ':model-value="isSelectedPropertyRequired"', '必填开关显示值必须来自多选集合。')
includes(template, ':model-value="selectedPropertyValueType"', '字段类型显示值必须来自多选集合，混合类型时应为空以触发批量选择。')
includes(template, ':model-value="selectedPropertyComponentFlag"', '控件类型显示值必须来自多选集合，混合控件时应为空以触发批量选择。')
notIncludes(template, 'v-model="selectedRule.required"', '必填开关不能直接绑定焦点格，否则多选只会改最后一个格子。')
notIncludes(template, 'v-model="selectedRule.valueType"', '字段类型不能直接绑定焦点格，否则取消映射冲突确认时已提前改值。')
notIncludes(template, 'v-model="selectedRule.componentFlag"', '控件类型不能直接绑定焦点格，否则多选只会改最后一个格子。')
notIncludes(template, ':model-value="isSelectedCellFillable"', '可填写开关不能只显示最后焦点格状态。')
notIncludes(template, ':model-value="selectedRule.required"', '必填开关不能只显示最后焦点格状态。')
notIncludes(template, ':model-value="selectedRule.valueType"', '字段类型选择不能只显示最后焦点格状态。')
notIncludes(template, ':model-value="selectedRule.componentFlag"', '控件类型选择不能只显示最后焦点格状态。')

console.log('PASS batch-record-cell-rules-batch-properties-static')
