const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const ts = require('typescript')
const vm = require('node:vm')
const root = path.resolve(__dirname, '../..')
const sourcePath = path.join(root, 'src/views/dcc/controlled-file/project-attributes/state.ts')
assert.ok(fs.existsSync(sourcePath), '三申请共用属性状态模块必须存在')
const exportsObject = {}
const code = ts.transpileModule(fs.readFileSync(sourcePath, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText
vm.runInNewContext(code, { exports: exportsObject, Error })
const { validateAttributes, changeMarkets, changeTransfer, createAttributeState, loadProjectDefaults, restoreDefaults, editActual, buildSnapshot } = exportsObject
const defaults = { targetMarkets: ['NMPA'], licenseHolder: 'Y', actualManufacturer: 'N', documentTransfer: 'N' }
const plain = value => JSON.parse(JSON.stringify(value))
async function run() {
  let count = 0
  for (const action of ['UPLOAD', 'REVISION', 'OBSOLETE']) {
    const state = createAttributeState(action)
    assert.equal(await loadProjectDefaults(state, '1', async () => defaults, async () => true), true)
    editActual(state, { ...defaults, targetMarkets: ['CE'], documentTransfer: 'Y', transferTo: '甲方' })
    const snapshot = buildSnapshot(state)
    assert.deepEqual(plain(snapshot.defaultSource.targetMarkets), ['NMPA'])
    assert.deepEqual(plain(snapshot.actual.targetMarkets), ['CE'])
    defaults.targetMarkets.push('FDA')
    assert.deepEqual(plain(snapshot.defaultSource.targetMarkets), ['NMPA'])
    defaults.targetMarkets.pop()
    const reopened = createAttributeState(action, snapshot)
    assert.deepEqual(plain(buildSnapshot(reopened)), plain(snapshot))
    assert.equal(await loadProjectDefaults(reopened, '2', async () => defaults, async () => false), false)
    assert.equal(reopened.projectId, '1')
    await loadProjectDefaults(reopened, '2', async () => ({ ...defaults, targetMarkets: ['MADSAP'] }), async () => true)
    assert.equal(reopened.projectId, '2')
    assert.deepEqual(plain(reopened.actual.targetMarkets), ['MADSAP'])
    count++
  }
  assert.throws(() => validateAttributes({ ...defaults, targetMarkets: [] }))
  assert.throws(() => validateAttributes({ ...defaults, targetMarkets: ['NA', 'FDA'] }))
  assert.throws(() => validateAttributes({ ...defaults, targetMarkets: ['OTHER'] }))
  assert.throws(() => validateAttributes({ ...defaults, documentTransfer: 'Y' }))
  assert.throws(() => validateAttributes({ ...defaults, licenseHolder: '' }))
  assert.throws(() => validateAttributes({ ...defaults, actualManufacturer: 'Y', documentTransfer: 'NA' }))
  assert.throws(() => validateAttributes({ ...defaults, transferTo: '不应提交' }))
  validateAttributes({ ...defaults, licenseHolder: 'Y', actualManufacturer: 'Y' })
  assert.deepEqual(plain(changeMarkets({ ...defaults, targetMarkets: ['OTHER'], otherMarket: '说明' }, ['NA'])), { ...defaults, targetMarkets: ['NA'] })
  assert.deepEqual(plain(changeTransfer({ ...defaults, documentTransfer: 'Y', transferTo: '目标' }, 'N')), defaults)
  const state = createAttributeState('UPLOAD')
  await assert.rejects(loadProjectDefaults(state, '1', async () => { throw new Error('权限拒绝') }, async () => true), /权限拒绝/)
  assert.equal(state.error, '权限拒绝')
  assert.equal(state.projectId, undefined)
  await loadProjectDefaults(state, '1', async () => defaults, async () => true)
  editActual(state, { ...defaults, targetMarkets: ['CE'] })
  assert.equal(await restoreDefaults(state, async () => defaults, async () => false), false)
  assert.deepEqual(plain(state.actual.targetMarkets), ['CE'])
  await restoreDefaults(state, async () => defaults, async () => true)
  assert.deepEqual(plain(state.actual.targetMarkets), ['NMPA'])
  let releaseFirst
  const firstRequest = loadProjectDefaults(state, '10', () => new Promise(resolve => { releaseFirst = resolve }), async () => true)
  await loadProjectDefaults(state, '11', async () => ({ ...defaults, targetMarkets: ['FDA'] }), async () => true)
  releaseFirst({ ...defaults, targetMarkets: ['CE'] })
  assert.equal(await firstRequest, false)
  assert.equal(state.projectId, '11')
  assert.deepEqual(plain(state.actual.targetMarkets), ['FDA'])
  const component = fs.readFileSync(path.join(root, 'src/views/dcc/controlled-file/project-attributes/ProjectAttributesFields.vue'), 'utf8')
  for (const field of ['targetMarkets', 'licenseHolder', 'actualManufacturer', 'documentTransfer', 'transferTo']) assert.ok(component.includes(field))
  console.log(`PASS: ${count} application paths + validation/switch/restore/error/frozen-draft checks`)
}
run().catch(error => { console.error(error); process.exitCode = 1 })
