const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '../..')
const api = fs.readFileSync(path.join(root, 'src/api/dcc/controlledFile/workflow.ts'), 'utf8')
const page = fs.readFileSync(path.join(root, 'src/views/dcc/controlled-file/browser/index.vue'), 'utf8')

assert.match(api, /export const checkoutControlledFile[\s\S]*request\.post\(\{ url: `\/dcc\/controlled-files\/\$\{id\}\/checkout`, data \}\)/)
assert.match(api, /export const checkinControlledFile[\s\S]*request\.post\(\{ url: `\/dcc\/controlled-files\/\$\{id\}\/checkin`, data \}\)/)
assert.match(api, /export const cancelCheckoutControlledFile[\s\S]*request\.post\(\{ url: `\/dcc\/controlled-files\/\$\{id\}\/checkout\/cancel`, data \}\)/)
assert.match(api, /ControlledFileCheckoutReqVO/)
assert.match(api, /ControlledFileCheckinReqVO/)
assert.match(api, /ControlledFileCancelCheckoutReqVO/)
assert.match(api, /export const createControlledFileMajorRevision[\s\S]*url: '\/dcc\/controlled-files\/major-revision'/)
assert.match(api, /cancelCheckoutControlledFile/)
assert.match(api, /checkedOutByName\?: string \| null/)
assert.match(page, /checkoutControlledFile/)
assert.match(page, /checkinControlledFile/)
assert.match(page, /cancelCheckoutControlledFile/)
assert.match(page, /uploadControlledFilePreview/)
assert.match(page, /请输入本次修改原因/)
assert.match(page, /label="修改说明"/)
assert.match(page, /uploadControlledFilePreview/)
assert.match(page, /data-testid="dcc-controlled-browser-checkin-upload"/)
assert.match(page, /uploaded\.uploadTicket/)
assert.match(page, /data-testid="dcc-controlled-browser-cancel-checkout"/)
assert.match(page, /data-testid="dcc-controlled-browser-major-revision"/)
assert.match(page, /sourceControlledFileId: String\(file\.id\)/)
assert.doesNotMatch(page, /sourceControlledFileId: Number\(file\.id\)/)
assert.match(page, /升大版本原因/)
assert.match(page, /cancelCheckoutControlledFile/)
assert.match(page, /data-testid="dcc-controlled-browser-checkout"/)
assert.match(page, /data-testid="dcc-controlled-browser-checkin"/)
assert.match(page, /data-testid="dcc-controlled-browser-checkin-upload"/)
assert.match(page, /data-testid="dcc-controlled-browser-checkin-submit"/)
assert.match(page, /data-testid="dcc-controlled-browser-cancel-checkout"/)
assert.match(page, /data-testid="dcc-controlled-browser-checked-out-by"/)
assert.match(page, /uploadTicket:\s*uploaded\.uploadTicket/)
assert.match(page, /sessionId:\s*checkinUploadSessionId\.value/)
assert.match(page, /文件已检入，新版本为/)
assert.match(page, /已撤销检出，未生成新版本/)
assert.match(page, /!getSelectedVersion\(row\)\.checkedOutBy/)
assert.match(page, /isCheckedOutByCurrentUser/)
assert.match(page, /const currentActiveVersionNo = String\(row\.currentActiveVersionNo \|\| ''\)\.trim\(\)/)
assert.match(page, /item\.status === 'ACTIVE'/)
assert.match(page, /String\(item\.versionNo \|\| ''\)\.trim\(\) === currentActiveVersionNo/)

console.log('PASS: dcc browser checkout static contract')
