const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..', '..')
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8')

const api = read('src/api/dcc/controlledFile/publicationFollowup.ts')
const workbench = read('src/views/dcc/controlled-file/workbench/index.vue')
const admin = read('src/views/dcc/controlled-file/publication-followup/index.vue')
const routes = read('src/router/modules/remaining.ts')
const migration = read('../IntRuoyiBackend/sql/mysql/20260907_dcc_publication_notification.sql')
const presentation = read('src/views/dcc/controlled-file/shared/publicationFollowupPresentation.ts')
const timeline = read('src/views/dcc/controlled-file/shared/PublicationFollowupTimeline.vue')

assert.match(api, /export type DccBusinessId = string/)
assert.doesNotMatch(api, /\b(?:Number|parseInt)\s*\(/)
assert.match(api, /publication-followups\/my-impact-tasks/)
assert.match(api, /publication-followups\/management-page/)
assert.match(api, /notification-deliveries\/\$\{deliveryId\}\/retry/)
assert.match(api, /revision-options/)
assert.match(api, /link-revision/)
assert.match(api, /publication-impact-tasks\/\$\{taskId\}\/reopen/)

assert.match(workbench, /我的影响评估/)
assert.match(workbench, /data-testid="dcc-workbench-impact-assessments"/)
assert.match(workbench, /v-loading="impactLoading"/)
assert.match(workbench, /impactLoadError/)
assert.match(workbench, /暂无待处理影响评估/)
assert.match(workbench, /data-testid="dcc-impact-revision-dialog"/)
assert.match(workbench, /openMajorRevision/)
assert.match(workbench, /sourceIterations/)
assert.match(workbench, /关联现有版本/)
assert.match(workbench, /row\.decision === 'REVISION_REQUIRED' && row\.revisionTrackingStatus === 'NOT_STARTED'/)
assert.match(workbench, /revisionTrackingStatusLabel\(row\.revisionTrackingStatus\)/)
assert.doesNotMatch(workbench, /impactRows\.value\s*=.*filter\([^\n]*COMPLETED/)
assert.match(workbench, /impactActionTaskId/)
assert.match(workbench, /<Pagination/)
assert.match(workbench, /isMessageBoxCancel/)
assert.match(workbench, /role="alert"/)

assert.match(admin, /发布后续/)
assert.match(admin, /data-testid="dcc-publication-followup-management"/)
assert.match(admin, /通知状态/)
assert.match(admin, /任务状态/)
assert.match(admin, /重试/)
assert.match(admin, /role="alert"/)
assert.match(admin, /@media \(max-width: 768px\)/)
assert.doesNotMatch(admin, /查看新发布文件的通知结果与关联文件影响评估/)
assert.match(admin, /isMessageBoxCancel/)
assert.match(admin, /notificationStatusLabel/)
assert.match(admin, /data-testid="dcc-management-publication-timeline"/)
assert.match(admin, /重新打开/)
assert.match(admin, /reopenImpactTask/)
assert.match(admin, /row\.timeline/)
assert.match(timeline, /发送尝试次数/)
assert.match(timeline, /原负责人/)
assert.match(timeline, /新负责人/)
assert.match(timeline, /关联版本 ID/)
assert.match(timeline, /版本号未记录/)
assert.match(routes, /name: 'DccControlledFilePublicationFollowup'/)
assert.match(routes, /dcc:controlled-file:publication-followup:manage/)
assert.match(migration, /DccControlledFilePublicationFollowup/)
assert.match(migration, /target_role\.`code` = 'doc_control'/)
assert.match(presentation, /未知状态（\$\{code\}）/)
for (const name of ['batchStatusLabel', 'notificationStatusLabel', 'impactTaskStatusLabel',
  'revisionTrackingStatusLabel', 'visibilitySourceLabel', 'relationDirectionLabel']) {
  assert.match(presentation, new RegExp(`export const ${name}`))
}

console.log('dcc release impact workbench static contract passed')
