const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '../..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const detail = read('src/views/dcc/controlled-file/detail/index.vue')
assert.match(detail, /<DetailApplicationPanel\b/, '详情应挂正式申请组件')
assert.match(detail, /<DetailSignoffAssignment\b/, '详情应挂正式会签指派')
assert.match(detail, /<WorkflowDistributionPanel\b/, '受控后应挂正式下发组件')
assert.match(detail, /<DetailObsoleteApplication\b/, '独立作废应有完整申请表')
assert.doesNotMatch(detail.slice(detail.indexOf('const handleManualRelease ='), detail.indexOf('const handleManualRelease =') + 900), /manualReleaseControlledFile\(/, '下发不调用旧放行接口')
const application = read('src/views/dcc/controlled-file/detail/DetailApplicationPanel.vue')
assert.match(application, /<DccRevisionPanel\b/)
assert.match(application, /getWorkingApplicationAttributes/)
assert.match(application, /selectedIterationId/)
assert.match(application, /ElMessageBox\.confirm/)
assert.doesNotMatch(application, /isLatestWorkingIteration/)
const assignment = read('src/views/dcc/controlled-file/detail/DetailSignoffAssignment.vue')
assert.match(assignment, /getSignoffAssignmentContext/)
assert.match(assignment, /<SignoffAssignmentPanel\b/)
assert.match(assignment, /relationArrangements/)
assert.match(assignment, /\.validate\(/)
const obsolete = read('src/views/dcc/controlled-file/detail/DetailObsoleteApplication.vue')
assert.match(obsolete, /action="OBSOLETE"/)
assert.match(obsolete, /projectAttributes/)
assert.match(obsolete, /ElMessageBox\.confirm/)
console.log('PASS DCC detail public workflow integration')
