const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '../..')
const read = (p) => fs.readFileSync(path.join(root, 'src', p), 'utf8')
const tabs = read('views/mes/pro/edhr-batch/EdhrBatchRecordTabs.vue')
assert.doesNotMatch(tabs, /pageGraph|批记录页面关系图/)
assert.match(tabs, /label="作废" name="voided"/)
assert.match(tabs, /voided: '\/mes\/pro\/feedback\/edhr-batch-voided'/)
const routes = read('router/modules/remaining.ts')
assert.match(routes, /path: 'pro\/feedback\/edhr-batch-voided'[\s\S]*?BatchVoidedPage.vue/)
const helper = read('utils/routerHelper.ts')
const override = helper.slice(helper.indexOf('const applyRouteMetaOverrides'), helper.indexOf('export const registerComponent'))
assert.match(override, /mes\/pro\/edhr-nonconformance\/NonconformanceReviewPage/)
assert.match(override, /meta.hidden = true/)
assert.match(override, /meta.activeMenu = '\/mes\/pro\/feedback\/edhr-batch-execution'/)
const page = read('views/mes/pro/edhr-batch/BatchVoidedPage.vue')
assert.match(page, /active-tab="voided"/)
assert.match(page, /status: EDHR_BATCH_STATUS_VOIDED/)
assert.match(page, /completedTraceOnly: true/)
assert.match(page, /getEdhrBatchExecutionPage/)
assert.match(page, /batchExecutionId: String\(row.id\)/)
assert.match(page, /edhr-batch-execution\/active-order-detail/)
assert.match(page, /from: '\/mes\/pro\/feedback\/edhr-batch-voided'/)
assert.match(page, /v-if="loadError"/)
assert.match(page, /<Pagination/)
assert.doesNotMatch(page, /releasedOnly|excludeStatuses|\.filter\(/)
console.log('PASS batch navigation and voided list contract')
