const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '../..')
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

const history = read('src/views/mes/pro/edhr-batch/BatchRecordHistoryPage.vue')
const detail = read('src/views/mes/pro/edhr-batch/BatchExecutionActiveOrderDetailPage.vue')
const panel = read('src/views/mes/pro/edhr-batch/components/BatchReverseTracePanel.vue')
const api = read('src/api/mes/pro/edhr/reverseTrace.ts')
const state = read('src/views/mes/pro/edhr-batch/reverseTraceState.ts')

assert.match(history, /data-edhr-history-reverse-trace/)
assert.match(history, /BatchReverseTracePanel/)
assert.match(history, /reverseTraceBatchExecutionId/)
assert.match(detail, /data-edhr-detail-reverse-trace/)
assert.match(detail, /BatchReverseTracePanel/)
assert.match(detail, /batchExecutionId/)
assert.match(detail, /canOpenReverseTrace/)
assert.match(detail, /isHistoryDetail/)
assert.match(panel, /data-edhr-reverse-trace-panel/)
assert.match(panel, /data-edhr-reverse-trace-add-condition/)
assert.match(panel, /data-edhr-reverse-trace-query/)
assert.match(panel, /data-edhr-reverse-trace-reset/)
assert.match(panel, /BLOCKED|queryResponse\.reason/)
assert.match(panel, /saveReverseTraceState/)
assert.match(panel, /readReverseTraceState/)
assert.match(state, /releaseApprovedTime/)
assert.match(panel, /releaseApprovedFrom/)
assert.match(panel, /releaseApprovedTo/)
assert.match(panel, /saved\.releaseApprovedTime/)
assert.match(panel, /@scroll\.capture="rememberScroll"/)
assert.match(panel, /@opened="restoreScroll"/)
assert.match(panel, /\.el-drawer__body/)
assert.match(history, /:restore-key="reverseTraceRestoreKey"/)
assert.match(history, /:history-list-state="queryParams"/)
assert.match(detail, /:restore-key="reverseTraceRestoreKey"/)
assert.match(detail, /reverseTraceReturn/)
assert.equal((panel.match(/<el-pagination\b/g) || []).length, 2)
assert.doesNotMatch(panel, /JSON\.parse|JSON\.stringify/)
assert.match(api, /\/catalog/)
assert.match(api, /\/query/)
assert.match(api, /\/evidence/)
for (const category of ['FIELD', 'PARAMETER', 'EQUIPMENT', 'PERSON', 'INSPECTION', 'MATERIAL']) {
  assert.match(api, new RegExp("'" + category + "'"))
}

console.log('edhr-batch-reverse-trace-static: PASS')
