const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const scriptPath = path.join(__dirname, 'edhr-full-chain-multi-user-real-flow.e2e.js')
const scriptText = fs.readFileSync(scriptPath, 'utf8')
const start = scriptText.indexOf('async function parseBusinessResponse')
const parseEnd = scriptText.indexOf('async function waitForApiResponse', start)
const parseBlock = scriptText.slice(start, parseEnd)
const waitStart = parseEnd
const waitEnd = scriptText.indexOf('async function clickVisibleButton', waitStart)
const waitBlock = scriptText.slice(waitStart, waitEnd)
const loginStart = scriptText.indexOf('async function login')
const loginEnd = scriptText.indexOf('async function browserAuth', loginStart)
const loginBlock = scriptText.slice(loginStart, loginEnd)
const tenantStart = scriptText.indexOf('async function waitForTenantRecognition')
const tenantEnd = scriptText.indexOf('async function clickVisibleButton', tenantStart)
const tenantBlock = scriptText.slice(tenantStart, tenantEnd)
const archiveStart = scriptText.indexOf('async function openArchiveTaskFromBoard')
const archiveEnd = scriptText.indexOf('async function generateArchiveAndPrint', archiveStart)
const archiveBlock = scriptText.slice(archiveStart, archiveEnd)

assert.ok(!parseBlock.includes('await response.finished()'), 'parseBusinessResponse 不应等待 response.finished() 后再读取 JSON body')
assert.ok(parseBlock.includes('throw new Error('), 'parseBusinessResponse 读取响应体失败时必须抛出带标签的新错误')
assert.ok(waitBlock.includes('const response = await page.waitForResponse'), 'waitForApiResponse 必须只通过 waitForResponse 捕获目标响应')
assert.ok(!waitBlock.includes("page.on('response'"), 'waitForApiResponse 不得同时注册 response 监听，避免同一响应体被抢读')
assert.ok(!waitBlock.includes('capturedBodyPromise'), 'waitForApiResponse 不得缓存同一响应体的第二条读取路径')
assert.ok(scriptText.includes('async function waitForTenantRecognition'), '主链路脚本必须显式等待租户识别成功')
assert.ok(!tenantBlock.includes('page.waitForResponse'), '租户选择已命中真实下拉项时，不应强依赖可能被缓存的租户识别网络请求')
assert.ok(!tenantBlock.includes('tenantInput.inputValue()'), 'Element Plus 选中租户后输入框 value 会清空，不应以 inputValue 判断')
assert.ok(tenantBlock.includes("'.el-select__placeholder span'"), '租户识别等待应验证 Element Plus 真实选中占位文本')
assert.ok(loginBlock.includes('tenantRecognitionPromise'), '登录前必须创建租户识别等待')
assert.ok(loginBlock.includes('selectLoginTenantByUi') && tenantBlock.includes("'.el-select-dropdown:visible .el-select-dropdown__item'"), '登录租户选择必须通过委托函数点击真实下拉项')
assert.ok(loginBlock.indexOf('await tenantRecognitionPromise') < loginBlock.indexOf('/admin-api/system/auth/login'), '必须先等租户识别成功，再等待登录响应')
assert.ok(archiveBlock.includes('/mes/pro/edhr-work-task/my-page'), '归档待办页面定位失败时必须读取真实 my-page 接口作为诊断证据')
assert.ok(archiveBlock.includes('visibleTableRowTexts'), '归档待办页面定位失败时必须输出当前可见表格行')
assert.ok(archiveBlock.includes('当前账号归档待办接口'), '归档待办失败信息必须说明当前账号接口返回，避免只给超时')
