const assert = require('assert/strict')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..', '..')
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

const api = read('src/api/mes/pro/edhr/nonconformanceReview.ts')
assert.match(api, /SOURCE_TYPE_PQC_SUBMISSION\s*=\s*'PQC_SUBMISSION'/)
assert.match(api, /SOURCE_TYPE_PQC_RELEASE\s*=\s*'PQC_RELEASE'/)
assert.match(api, /DISPOSITION_CONCESSION_RELEASE\s*=\s*'concession_release'/)
assert.match(api, /DISPOSITION_REWORK\s*=\s*'rework'/)
assert.match(api, /DISPOSITION_VOID\s*=\s*'void'/)
assert.match(api, /createNonconformanceReview/)
assert.match(api, /disposeNonconformanceReview/)
assert.match(api, /getPendingNonconformanceReviewPage/)

const page = read('src/views/mes/pro/edhr-nonconformance/NonconformanceReviewPage.vue')
assert.match(page, /UploadFile/)
assert.match(page, /让步放行/)
assert.match(page, /返工/)
assert.match(page, /作废/)
assert.match(page, /评审材料/)
assert.match(page, /评审意见/)
assert.match(page, /QA签名/)
assert.match(page, /提交不合格评审/)
assert.match(page, /冻结后禁止报工、PQC提交、PQC放行/)

const router = read('src/router/modules/remaining.ts')
assert.match(router, /MesProFeedbackEdhrNonconformanceReview/)
assert.match(router, /edhr-nonconformance-review/)

const batchApi = read('src/api/mes/pro/edhr/batchExecution.ts')
assert.match(batchApi, /EDHR_BATCH_STATUS_FROZEN\s*=\s*15/)

const batchDetail = read('src/views/mes/pro/edhr-batch/BatchExecutionDetailPage.vue')
assert.match(batchDetail, /SOURCE_TYPE_PQC_SUBMISSION/)
assert.match(batchDetail, /SOURCE_TYPE_PQC_RELEASE/)
assert.match(batchDetail, /openNonconformanceReviewEntry/)
assert.match(batchDetail, /name:\s*'MesProFeedbackEdhrNonconformanceReview'/)
assert.match(batchDetail, /不合格审查/)

const frontlinePanel = read('src/views/mes/pro/feedback/FrontlineFixedTemplatePanel.vue')
assert.match(frontlinePanel, /SOURCE_TYPE_PQC_SUBMISSION/)
assert.match(frontlinePanel, /openNonconformanceReviewEntry/)
assert.match(frontlinePanel, /name:\s*'MesProFeedbackEdhrNonconformanceReview'/)
assert.match(frontlinePanel, /不合格审查/)

const releasePage = read('src/views/mes/pro/edhr-release/ReleasePage.vue')
assert.match(releasePage, /SOURCE_TYPE_PQC_RELEASE/)
assert.match(releasePage, /openNonconformanceReviewEntry/)
assert.match(releasePage, /name:\s*'MesProFeedbackEdhrNonconformanceReview'/)
assert.match(releasePage, /不合格审查/)

const traceApi = read('src/api/mes/pro/edhr/domainTrace.ts')
assert.match(traceApi, /nonconformanceReviews/)

const tracePage = read('src/views/mes/pro/edhr/DomainTraceDetailPage.vue')
assert.match(tracePage, /不合格评审/)
assert.match(tracePage, /reviewMaterialUrl/)
assert.match(tracePage, /concession_release/)
assert.match(tracePage, /rework/)
assert.match(tracePage, /void/)

console.log('edhr-nonconformance-review-mvp-static: PASS')
