const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '../..')
const readSource = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')

const workTaskApi = readSource('src/api/mes/pro/edhr/workTask.ts')
const batchApi = readSource('src/api/mes/pro/edhr/batchExecution.ts')
const workTaskPage = readSource('src/views/mes/pro/edhr-work-task/WorkTaskBoardPage.vue')
const batchListPage = readSource('src/views/mes/pro/edhr-batch/BatchExecutionListPage.vue')
const batchDetailPage = readSource('src/views/mes/pro/edhr-batch/BatchExecutionDetailPage.vue')
const realFlow = readSource('tests/e2e/edhr-final-archive-work-task-real-flow.e2e.js')

assert.match(workTaskApi, /EDHR_WORK_TASK_TYPE_ARCHIVE\s*=\s*'ARCHIVE'/, '工作任务 API 必须导出 ARCHIVE 任务类型。')
assert.match(workTaskApi, /archiveCount:\s*number/, '工作任务统计必须包含待归档数量。')
assert.match(workTaskApi, /EdhrWorkTaskArchiveRuleReqVO/, '工作任务 API 必须声明最终归档责任规则请求类型。')
assert.match(workTaskApi, /EdhrWorkTaskCloseRuleReqVO/, '工作任务 API 必须声明批次关闭责任规则请求类型。')
assert.match(workTaskApi, /EdhrWorkTaskAssignmentRuleRespVO/, '工作任务 API 必须声明最终归档责任规则响应类型。')
assert.match(workTaskApi, /getEdhrRouteArchiveRule/, '工作任务 API 必须提供按路线查询归档责任规则的方法。')
assert.match(workTaskApi, /saveEdhrRouteArchiveRule/, '工作任务 API 必须提供保存归档责任规则的方法。')
assert.match(workTaskApi, /getEdhrRouteCloseRule/, '工作任务 API 必须提供按路线查询关闭责任规则的方法。')
assert.match(workTaskApi, /saveEdhrRouteCloseRule/, '工作任务 API 必须提供保存关闭责任规则的方法。')
assert.match(workTaskApi, /\/mes\/pro\/edhr-work-task\/route-archive-rule/, '归档责任规则 API 必须使用正式后端 route-archive-rule 接口。')
assert.match(workTaskApi, /\/mes\/pro\/edhr-work-task\/route-close-rule/, '关闭责任规则 API 必须使用正式后端 route-close-rule 接口。')
assert.match(workTaskPage, /EDHR_WORK_TASK_TYPE_ARCHIVE/, '工作任务看板必须导入 ARCHIVE 任务类型。')
assert.match(workTaskPage, /待归档/, '工作任务看板必须展示待归档统计或筛选文案。')
assert.match(workTaskPage, /最终归档/, '工作任务看板任务类型筛选必须包含最终归档。')
assert.match(workTaskPage, /archiveCount/, '工作任务看板必须渲染 archiveCount。')
assert.match(workTaskPage, /mes:pro-edhr-work-task-rule:update/, '工作任务看板必须按权限展示归档责任规则维护入口。')
assert.match(workTaskPage, /getEdhrRouteArchiveRule/, '工作任务看板必须能加载路线级归档责任规则。')
assert.match(workTaskPage, /saveEdhrRouteArchiveRule/, '工作任务看板必须能保存路线级归档责任规则。')
assert.match(workTaskPage, /getEdhrRouteCloseRule/, '工作任务看板必须能加载路线级关闭责任规则。')
assert.match(workTaskPage, /saveEdhrRouteCloseRule/, '工作任务看板必须能保存路线级关闭责任规则。')
assert.match(workTaskPage, /ProRouteApi\.getRouteSimpleList/, '归档责任规则维护必须使用正式工艺路线列表。')
assert.match(workTaskPage, /getSimpleUserList/, '归档责任规则维护必须使用正式用户精简列表。')
assert.match(workTaskPage, /关闭规则/, '工作任务看板必须提供关闭规则维护对话框或按钮。')
assert.match(workTaskPage, /归档规则/, '工作任务看板必须提供归档规则维护对话框或按钮。')
assert.doesNotMatch(workTaskPage, /mock|fixture|demo|defaultSuccess/i, '归档规则维护不得使用 mock、fixture、demo 或默认成功路径。')

assert.match(batchApi, /workTaskId:\s*number/, '批次归档生成 API 类型必须强制 workTaskId。')
assert.match(batchDetailPage, /archiveWorkTaskId/, '批次详情页必须解析归档待办 workTaskId。')
assert.match(batchDetailPage, /route\.query\.workTaskId/, '批次详情页必须从路由查询读取 workTaskId。')
assert.match(batchDetailPage, /assertArchiveWorkTaskId/, '批次详情页必须断言归档待办 workTaskId。')
assert.match(batchDetailPage, /workTaskId:\s*assertArchiveWorkTaskId\(\)/, '生成最终归档请求必须携带归档待办 workTaskId。')
assert.match(batchDetailPage, /canGenerateArchive[\s\S]*archiveWorkTaskId\.value/, '生成最终归档按钮必须受归档待办上下文约束。')
assert.match(batchListPage, /下载打印版 PDF/, '批次列表页下载入口必须明确为打印版 PDF。')
assert.match(batchDetailPage, /下载打印版 PDF/, '批次详情页下载入口必须明确为打印版 PDF。')
assert.match(batchListPage, /打印版 PDF 下载已开始/, '批次列表页下载提示必须明确为打印版 PDF。')
assert.match(batchDetailPage, /打印版 PDF 下载已开始/, '批次详情页下载提示必须明确为打印版 PDF。')
assert.match(batchDetailPage, /打印版 PDF 窗口已打开/, '批次详情页打印提示必须明确为打印版 PDF。')
assert.doesNotMatch(batchListPage, /generateEdhrBatchArchive|handleGenerateArchive|生成归档/, '批次列表页不得保留无归档待办上下文的生成归档入口。')
assert.doesNotMatch(batchDetailPage, /workTaskId:\s*Number\([^)]*\)\s*\|\|\s*undefined/, '批次详情页不得用 undefined 绕过 workTaskId 门禁。')
assert.doesNotMatch(batchDetailPage, /mock|fixture|demo|defaultSuccess/i, '归档待办前端不得使用 mock、fixture、demo 或默认成功路径。')

assert.match(realFlow, /discoverArchiveWorkTaskFromBoard/, '真实 E2E 必须能从工作任务看板发现真实 ARCHIVE/TODO 待办。')
assert.match(realFlow, /hasExplicitArchiveTarget/, '真实 E2E 必须区分显式目标和 UI 自动发现目标。')
assert.match(realFlow, /测试租户工作任务看板没有真实 ARCHIVE\/TODO 待办/, '缺少真实归档待办时必须明确 BLOCKED。')
assert.doesNotMatch(realFlow, /必须提供测试租户内真实 ARCHIVE\/TODO 工作任务 ID。/, '真实 E2E 不应强制手工注入 workTaskId。')

console.log('PASS: eDHR final archive work task static contract')
