const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

const root = path.resolve(__dirname, '../..')
const read = (relativePath) =>
  fs.readFileSync(path.join(root, relativePath), 'utf8').replace(/\r\n/g, '\n')

const reportApi = read('src/api/mes/pro/batchrecordreport/index.ts')
const permissionApi = read('src/api/mes/pro/edhr/processFormPermissionRule.ts')
const formListPage = read('src/views/mes/pro/batchrecordformlist/index.vue')
const rulesDialog = read('src/views/mes/pro/batchrecordformlist/BatchRecordCellRulesConfirmDialog.vue')
const executionPage = read('src/views/mes/pro/edhr/ExecutionPage.vue')
const feedbackApi = read('src/api/mes/pro/feedback/index.ts')
const routeFlowDesigner = read('src/views/mes/pro/route/RouteFlowGraphDesigner.vue')
const realFlowE2E = read('tests/e2e/edhr-visual-fill-config-real-flow.e2e.js')

const includes = (content, token, message) => assert.ok(content.includes(token), message)
const notIncludes = (content, token, message) => assert.ok(!content.includes(token), message)

includes(reportApi, 'BatchRecordReportAssistRowVO', '批记录规则 API 必须声明辅助行 VO。')
includes(reportApi, 'assistRows?: BatchRecordReportAssistRowVO[]', 'cell-rules 请求/响应必须携带 assistRows。')
includes(permissionApi, 'FillAssignment', '填写人 API 必须声明辅助行填写人分配合同。')
includes(permissionApi, 'fillAssignments', 'save-by-report 必须支持按辅助行提交 fillAssignments。')
notIncludes(permissionApi, 'fillRule: EdhrProcessFormCandidateRule\n}', '表单级填写配置不能只支持旧 fillRule 单规则。')

includes(formListPage, '>填写配置<', '表单列表入口文案必须是“填写配置”，不再只是“规则”。')
includes(formListPage, 'openTemplateAction(selectedReport, \'cellRules\')', '填写配置入口必须复用当前表单上下文。')
includes(formListPage, "if (action === 'cellRules') {\n    openCellRulesDialog(row)\n    return\n  }", '页面内点击填写配置必须直接打开弹窗，不得先修改同页 query 触发列表重载。')
includes(formListPage, 'BatchRecordCellRulesConfirmDialog', '填写配置必须复用现有单元格规则弹窗。')
includes(formListPage, 'reportId: normalizeRouteQueryText(route.query.reportId) || undefined', '填写配置深链必须把 reportId 传入列表请求，确保目标表单不在第一页时仍可打开。')

includes(rulesDialog, 'title="填写配置"', '规则弹窗标题必须升级为填写配置。')
includes(rulesDialog, ':fullscreen="true"', '填写配置弹窗右上角必须显示最大化/恢复按钮。')
includes(rulesDialog, ':default-fullscreen="true"', '填写配置弹窗必须默认最大化打开。')
includes(rulesDialog, 'height: clamp(520px, calc(100vh - 220px), 880px);', '填写配置编辑区高度必须跟随近全屏视口，并给弹窗页脚留出保存空间。')
includes(rulesDialog, 'activeConfigMode', '填写配置必须有显式模式状态，用于切换原表单配置和辅助表单映射。')
includes(rulesDialog, "label=\"辅助表单映射\"", '填写配置必须提供“辅助表单映射”模式入口。')
includes(rulesDialog, 'data-fill-config-panel="source-form"', '辅助表单映射模式必须保留左侧原表单区域。')
includes(rulesDialog, 'data-fill-config-panel="assist-preview"', '辅助表单映射模式必须提供中间辅助表单实时预览区域。')
includes(rulesDialog, 'data-fill-config-panel="mapping-control"', '辅助表单映射模式必须提供右侧蓝色映射控制栏。')
includes(rulesDialog, '辅助表单预览', '辅助表单映射模式中间栏必须显示辅助表单预览标题。')
includes(rulesDialog, '映射控制栏', '辅助表单映射模式右侧栏必须集中放置映射控制。')
includes(rulesDialog, 'assistGridPreviewRows', '辅助表单预览必须由当前填写人的 M*N 表格实时计算，不得静态占位。')
includes(rulesDialog, 'resolveAssistGridPreviewCell', '辅助表单预览必须按辅助格映射展示原单元格和字段类型。')
includes(rulesDialog, 'grid-template-columns: minmax(320px, 1fr) minmax(280px, 0.85fr) 360px;', '辅助表单映射模式必须使用原表单、辅助预览、控制栏三栏布局。')
includes(rulesDialog, 'background: #fff8d6;', '辅助表单预览区域必须使用黄色底色，和原表单形成直观区分。')
includes(rulesDialog, 'background: #eaf3ff;', '映射控制栏必须使用蓝色底色，承载辅助映射控件。')
includes(rulesDialog, '@media (max-width: 1180px)', '辅助表单映射模式必须提供窄屏响应式布局。')
includes(rulesDialog, 'assistGridRowCount', '蓝色控制栏必须能配置辅助表格行数。')
includes(rulesDialog, 'assistGridColumnCount', '蓝色控制栏必须能配置辅助表格列数。')
includes(rulesDialog, 'assistFillerUserIds', '蓝色控制栏必须能维护当前表单填写人集合。')
includes(rulesDialog, 'selectedAssistFillerUserId', '辅助表格必须按当前填写人切换。')
includes(rulesDialog, 'selectedAssistGridCellKey', '辅助映射必须先选中辅助表格单元格。')
includes(rulesDialog, 'data-assist-grid-cell', '辅助表单预览必须渲染可点击的 M*N 表格单元格。')
includes(rulesDialog, 'handleAssistGridCellClick', '点击辅助表格单元格必须设置当前映射目标。')
includes(rulesDialog, 'mapSourceCellToSelectedAssistGridCell', '点击原表单元格必须映射到当前辅助格。')
includes(rulesDialog, 'removeAssistGridCellMapping', '辅助格必须支持取消映射以释放原表单元格。')
includes(rulesDialog, 'sourceCellGridAssignmentMap', '原表单元格必须有全局映射索引以禁止多用户重复分配。')
includes(rulesDialog, 'isSourceCellDisabledForAssistMapping', '已分配原表单元格必须灰化禁点。')
includes(rulesDialog, 'assistRows', '弹窗必须维护 assistRows 状态。')
includes(rulesDialog, 'ASSIST_GRID_ROW_KEY_PREFIX', '保存时必须用稳定 rowKey 表达用户和辅助格位置。')
includes(rulesDialog, 'parseAssistGridRowKey', '读取已有 assistRows 时必须还原用户和辅助格位置。')
notIncludes(rulesDialog, '辅助行配置', '辅助映射模式不得继续暴露旧辅助行配置入口。')
notIncludes(rulesDialog, '辅助行填写人', '辅助映射模式不得继续暴露旧辅助行填写人入口。')
includes(rulesDialog, '下拉选项', '字段类型配置必须提供下拉选项编辑。')
includes(rulesDialog, 'selectionMode', '下拉框必须复用 STRING + selectionMode=single。')
includes(rulesDialog, 'options', '下拉框选项必须保存到 constraints.options。')
includes(rulesDialog, 'selectedRule.valueType === \'SIGNATURE\'', '签名类型必须有显式签名单元格提示/校验入口。')
includes(rulesDialog, 'EdhrProcessFormPermissionRuleApi.getByReport', '弹窗打开必须读取现有报表填写人配置。')
includes(rulesDialog, 'EdhrProcessFormPermissionRuleApi.saveByReport', '保存填写配置必须复用真实 save-by-report 接口。')
includes(rulesDialog, 'getSimpleUserList', '辅助表格填写人必须复用系统用户候选项。')
notIncludes(rulesDialog, 'getSimpleRoleList', '辅助表格按员工分配，不得继续读取角色候选项。')
includes(rulesDialog, 'fillAssignments: normalizedAssistAssignmentsForSave', '保存填写配置必须按辅助行提交 fillAssignments。')
includes(rulesDialog, 'const assistRowsForSave = normalizedAssistRowsForSave()', '保存前必须规范化辅助行。')
includes(rulesDialog, 'assistRows: assistRowsForSave', '保存单元格规则时必须同时提交 assistRows。')
notIncludes(rulesDialog, 'catch {}', '填写配置弹窗不能吞掉读取或保存错误。')

includes(feedbackApi, 'ProFeedbackEdhrAssistRowVO', '执行快照 API 类型必须声明 assistRows。')
includes(feedbackApi, 'assistRows?: ProFeedbackEdhrAssistRowVO[]', 'executionSnapshotJson 类型必须包含冻结辅助行。')
includes(executionPage, 'visibleAssistRowsFromExecutionQuery', '执行页必须优先使用 openTask 返回的当前用户 assistRows。')
includes(executionPage, 'snapshotAssistRows', '执行页必须能读取 executionSnapshotJson 冻结辅助行。')
includes(executionPage, 'assistRowsConfigured', '执行页必须区分未配置辅助模式。')
includes(executionPage, '未配置辅助模式', '缺少辅助行时必须展示明确状态。')
includes(executionPage, 'buildAssistFieldsFromAssistRows', '辅助模式字段清单必须由 assistRows 映射到快照字段。')
includes(executionPage, 'draftFieldValues[field.fieldIdentity]', '辅助模式必须复用现有 draftFieldValues。')
notIncludes(executionPage, 'assistDraftFieldValues', '辅助模式不得新增独立草稿对象。')

includes(routeFlowDesigner, 'BatchRecordReportApi', '工艺路线批记录表单选择必须复用现有批记录报表分页 API。')
includes(routeFlowDesigner, 'type BatchRecordReportVO', '工艺路线批记录表单选择必须使用正式报表元数据类型。')
assert.match(
  routeFlowDesigner,
  /PROCESS_DETAIL_EDITABLE_FIELD_KEYS[\s\S]*?'batchRecordFormNames'/,
  '草稿候选版本中的批记录表单字段必须可编辑。'
)
includes(
  routeFlowDesigner,
  'data-route-process-setting-field="batch-record-report"',
  '批记录表单字段明细必须提供逐工序报表选择器。'
)
includes(routeFlowDesigner, 'loadBatchRecordReportOptions', '批记录表单选择器必须支持从正式报表目录搜索。')
includes(
  routeFlowDesigner,
  'handleSelectedBatchRecordReportIdsChange',
  '批记录表单选择变化必须同步到当前工序草稿。'
)
includes(
  routeFlowDesigner,
  'selectedLegacyBatchRecords.value = resequenceLegacyBatchRecords(nextRecords)',
  '批记录表单选择必须写入正式 legacyBatchRecords/batchRecordReports 草稿链路。'
)
includes(routeFlowDesigner, 'latestVersionOnly: true', '批记录表单选择器只能查询最新版本报表。')
includes(routeFlowDesigner, "formSlotType: 'MAIN'", '逐工序批记录表单必须显式保存为 MAIN 正式批记录绑定。')
includes(routeFlowDesigner, 'const codeSuffix = reportCode && reportCode !== primaryLabel', '同名批记录表单选项必须展示报表编码以便唯一识别。')

includes(realFlowE2E, 'local-input.json', '真实 E2E 必须从本地未跟踪配置读取租户、账号和报表夹具。')
includes(realFlowE2E, 'timeout: 180000', '真实 E2E 必须为官方登录前置保留足够的真实页面冷启动时间。')
includes(realFlowE2E, 'const isMainRuntime = frontendPort === 8081 && backendPort === 48081', '真实 E2E 必须允许融合后的 int_main 主运行态 8081/48081。')
includes(realFlowE2E, 'const isWorktreeRuntime = frontendSlot >= 1 && frontendSlot <= 19 && frontendSlot === backendSlot', '真实 E2E 仍必须校验附加 worktree 前后端使用同一 slot。')
includes(realFlowE2E, 'frontend/backend ports must be either int_main 8081/48081 or paired int_main worktree slot 1..19', '真实 E2E 端口错误提示必须同时表达主运行态和附加 worktree 两种合法模式。')
includes(realFlowE2E, 'const parsed = JSON.parse', '真实 E2E 必须解析本地配置后显式规范化配置结构。')
includes(realFlowE2E, 'parsed.data && typeof parsed.data === \'object\'', '真实 E2E 必须兼容 data 包裹和顶层本地配置结构。')
includes(realFlowE2E, 'targetReportName', '真实 E2E 必须把目标表单名与批记录夹具名分开。')
includes(realFlowE2E, 'routeProductName', '真实 E2E 必须把路线产品名与任务批记录夹具名分开。')
includes(realFlowE2E, 'sourceRouteCode', '真实 E2E 必须从本地未跟踪配置读取明确的共享来源路线编码。')
includes(realFlowE2E, 'preferredRouteCode', '真实 E2E 必须从本地未跟踪配置读取明确的任务专用路线编码。')
includes(realFlowE2E, 'targetProcessName', '真实 E2E 必须从本地未跟踪配置读取目标工序名称。')
includes(realFlowE2E, "String(option.routeCode || '') === config.preferredRouteCode", '真实 E2E 创建批次时必须精确选择任务专用路线编码。')
notIncludes(realFlowE2E, "enabledRouteOptions.find((option) => String(option.routeCode || '').trim())", '真实 E2E 不得退化为任意第一条可用路线。')
includes(realFlowE2E, 'prepareTaskOwnedRouteThroughUi', '真实 E2E 必须通过页面准备任务专用路线副本。')
includes(realFlowE2E, 'copyTaskOwnedRouteThroughUi', '真实 E2E 必须通过工艺流程列表复制明确来源路线。')
includes(realFlowE2E, 'configureTargetBatchRecordReportThroughUi', '真实 E2E 必须在候选版本页面为目标工序选择正式批记录表单。')
includes(realFlowE2E, 'data-route-process-setting-field="batch-record-report"', '真实 E2E 必须操作逐工序批记录表单选择器。')
includes(realFlowE2E, "filter({ hasText: report.reportCode })", '真实 E2E 必须按报表编码精确选择目标报表，不能只按同名文案选择第一项。')
includes(realFlowE2E, 'data-flow-action="save-route-flow"', '真实 E2E 必须通过路线编辑页顶部保存提交候选草稿。')
includes(realFlowE2E, 'publishTaskOwnedRouteCandidateThroughUi', '真实 E2E 必须通过页面电子签名提交并发布候选版本。')
includes(realFlowE2E, 'completeRouteApprovalThroughUi', '候选版本进入审批时，真实 E2E 必须通过审批中心完成电子签名审核。')
includes(realFlowE2E, '审核确认', '真实 E2E 必须在审批中心完成审核确认，而不是在提交发布时伪造签名。')
includes(realFlowE2E, 'enableTaskOwnedRouteThroughUi', '真实 E2E 必须通过工艺流程列表精确启用任务路线。')
includes(realFlowE2E, 'cleanupTaskOwnedBatchThroughUi', '真实 E2E finally 必须通过页面作废任务自有批次。')
includes(realFlowE2E, 'const currentBatch = await fetchCommonJson(', '批次列表未命中时必须只读读取任务自有批次当前状态，避免已作废批次被列表排除后误报不可见。')
includes(realFlowE2E, 'if (Number(currentBatch?.status) === 60)', '批次已作废时 cleanup-only 必须幂等返回 already-voided，不再进入排除终态的列表页。')
includes(realFlowE2E, 'const targetBatch = targetRows[0]', '批次清理必须先通过批次列表页面响应定位任务自有批次。')
includes(realFlowE2E, "arg === '--cleanup-only'", '真实 E2E 必须提供显式 cleanup-only 模式恢复失败运行留下的任务数据。')
includes(realFlowE2E, 'async function runCleanupOnly()', 'cleanup-only 必须复用真实页面清理函数，不能改用 API-only 或直接 SQL。')
includes(realFlowE2E, "const previousEvidence = JSON.parse(fs.readFileSync(resultFile, 'utf8'))", 'cleanup-only 必须读取已有脱敏结果中的任务批次标识。')
includes(realFlowE2E, "'cleanup-result.json'", 'cleanup-only 必须写入独立结果文件，保留原始失败证据。')
includes(realFlowE2E, 'cleanupTaskOwnedRouteThroughUi', '真实 E2E finally 必须停用并删除任务专用路线。')
includes(realFlowE2E, 'configuredExistingWorkOrderCode', '真实 E2E 必须支持显式复用已有金蝶同步工单。')
includes(realFlowE2E, 'restoreVisualFillConfigFixture', '真实 E2E 复用既有报表时必须恢复原始填写配置。')
includes(realFlowE2E, 'assistRowsForRestore', '真实 E2E 恢复既有报表时必须显式区分清空辅助行和空数组校验。')
includes(realFlowE2E, 'assistRows: assistRowsForRestore', '真实 E2E 恢复无辅助行报表必须传 null 清除 edhrAssistRows。')
includes(realFlowE2E, 'batchRecordName: config.batchRecordName', '真实 E2E 导入和阻塞证据必须记录批记录夹具名。')
includes(realFlowE2E, 'projectName: config.routeProductName', '真实 E2E 项目编码必须按路线产品名创建或复用。')
includes(realFlowE2E, 'openVisualFillConfigDialog(page, fixtureReport)', '真实 E2E 必须用任务夹具报表打开填写配置。')
includes(realFlowE2E, 'reportId=${encodeURIComponent(targetReportId)}', '真实 E2E 必须用 reportId 深链确保目标表单进入列表。')
includes(realFlowE2E, "page.locator('.batch-record-form-preview__actions')", '真实 E2E 必须复用报表详情右侧正式操作区。')
includes(realFlowE2E, "targetRow.locator('td.el-table__cell').filter({ hasText: targetReportName }).first()", '真实 E2E 必须点击目标行的表单名称单元格，不能点击整行误触旧填写人按钮。')
notIncludes(realFlowE2E, 'await targetRow.click()', '真实 E2E 不得直接点击整行。')
includes(realFlowE2E, 'captureVisibleOverlayDiagnostics', '真实 E2E 必须采集点击前可见覆盖层诊断。')
includes(realFlowE2E, 'unexpected_overlay_before_visual_fill_config_click', '真实 E2E 点击填写配置前存在未知覆盖层时必须 fail fast。')
includes(realFlowE2E, 'unexpected_overlay_before_visual_fill_config_save', '真实 E2E 保存填写配置前存在额外覆盖层时必须 fail fast。')
includes(realFlowE2E, 'hasVisualFillEditor', '覆盖层诊断必须记录是否已经包含填写配置编辑器。')
includes(realFlowE2E, "getByRole('button', { name: '填写配置' }).click({ noWaitAfter: true })", '真实 E2E 点击同页 SPA 填写配置入口后必须由弹窗断言接管，不等待浏览器导航。')
includes(realFlowE2E, 'assert.equal(await visibleVisualFillDialogs.count(), 1', '真实 E2E 必须断言页面只打开一个填写配置编辑器。')
includes(realFlowE2E, "const visibleVisualFillDialogs = page.locator('.el-overlay:visible .batch-record-cell-rules-editor')", '真实 E2E 必须在可见填写配置弹窗内操作规则编辑器，不能误点页面背景编辑器。')
notIncludes(realFlowE2E, "page.locator('.batch-record-cell-rules-editor').first()", '真实 E2E 不能用全页第一个规则编辑器，否则弹窗遮罩会拦截背景元素点击。')
includes(realFlowE2E, "const firstRuleCellSelected = await firstRuleCell.getAttribute('aria-pressed')", '真实 E2E 必须先读取首个规则格选中状态。')
includes(realFlowE2E, "if (firstRuleCellSelected !== 'true')", '真实 E2E 只有首个规则格未选中时才能点击。')
includes(realFlowE2E, 'await firstRuleCell.click()', '真实 E2E 必须在首个规则格未选中时点击进入配置。')
includes(realFlowE2E, 'const [cellRulesResponse, assignmentResponse] = await Promise.all([', '真实 E2E 保存动作必须与两个保存响应在同一个 Promise.all 中收敛。')
includes(realFlowE2E, ".locator('.el-overlay:visible')", '真实 E2E 保存必须限定在可见弹窗 overlay 内，避免命中底层弹窗按钮。')
includes(realFlowE2E, "filter({ has: page.locator('.batch-record-cell-rules-editor') })", '真实 E2E 保存必须定位包含规则编辑器的弹窗 overlay。')
includes(realFlowE2E, "const saveButton = visualFillOverlay.getByRole('button', { name: '保存填写配置' })", '真实 E2E 必须通过规则弹窗内保存按钮触发真实保存动作。')
includes(realFlowE2E, 'ensureTaskOwnedWorkOrderForVisualFill', '真实 E2E 必须通过任务自有 ERP 工单生成员工待办。')
includes(realFlowE2E, '/erp/kingdee-sync/production-order/create', '真实 E2E 必须用正式 ERP 生产工单创建入口准备任务自有工单。')
includes(realFlowE2E, '/mes/pro/work-order/sync-kingdee', '真实 E2E 必须触发正式金蝶工单同步，不得调用 MES 手工工单创建。')
includes(realFlowE2E, '/mes/pro/edhr-batch-execution/open-or-create', '真实 E2E 必须创建或打开匹配路线的 eDHR 批次执行。')
includes(realFlowE2E, 'assertTargetReportRouteBinding', '真实 E2E 创建批次前必须确认当前激活路线已绑定目标批记录报表。')
includes(realFlowE2E, '/mes/pro/route/flow-config', '真实 E2E 必须通过正式路线批记录配置接口核对目标报表绑定。')
includes(realFlowE2E, 'task_owned_batch_route_missing_target_report_binding', '当前路线未绑定目标报表时必须在创建批次前 fail fast。')
includes(realFlowE2E, 'assertTargetReportBatchTask', '真实 E2E 创建批次后必须确认目标批记录任务真实生成。')
includes(realFlowE2E, 'task_owned_batch_execution_missing_target_report_task', '批次未生成目标报表任务时必须阻断员工辅助模式验证。')
includes(realFlowE2E, 'taskOwnedBatchExecution', '真实 E2E 结果必须记录任务自有批次执行证据。')
includes(realFlowE2E, 'use_configured_existing_work_order', '真实 E2E 使用既有工单时必须显式记录该正式夹具策略。')
includes(realFlowE2E, 'CODX-VFC-BATCH-', '真实 E2E 复用既有工单时仍必须创建任务自有批次编码。')
notIncludes(realFlowE2E, '/mes/pro/work-order/create', '真实 E2E 不得调用被禁止的 MES 手工工单创建接口。')
notIncludes(realFlowE2E, 'projectName: config.batchRecordName', '真实 E2E 不得再用批记录夹具名创建 DCC 项目编码。')
notIncludes(realFlowE2E, 'projectName: config.reportName', '真实 E2E 不得用目标表单名创建 DCC 项目编码。')
notIncludes(realFlowE2E, 'batchRecordName: config.reportName', '真实 E2E 不得把目标表单名写入批记录夹具证据。')
includes(realFlowE2E, 'redactSecretText', '真实 E2E 结果必须脱敏密码等秘密。')
notIncludes(realFlowE2E, 'EDHR_VISUAL_FILL_', '真实 E2E 不得再依赖 EDHR_VISUAL_FILL_* 环境变量。')

console.log('PASS: eDHR visual fill config static contract')
