const assert = require('node:assert/strict')
const { resolveProductionIdentity } = require('./edhr-ai-loop/coverage.cjs')
assert.throws(() => resolveProductionIdentity({}), /PRODUCTION_EMPLOYEE_ID/)
assert.throws(() => resolveProductionIdentity({ EDHR_E2E_PRODUCTION_EMPLOYEE_ID: '980023' }), /PRODUCTION_SIGNATURE_PASSWORD/)
assert.throws(() => resolveProductionIdentity({ EDHR_E2E_PRODUCTION_EMPLOYEE_ID: 'x', EDHR_E2E_PRODUCTION_SIGNATURE_PASSWORD: 'unit-secret' }), /PRODUCTION_EMPLOYEE_ID/)
assert.deepEqual(resolveProductionIdentity({ EDHR_E2E_PRODUCTION_EMPLOYEE_ID: '980023', EDHR_E2E_PRODUCTION_SIGNATURE_PASSWORD: 'unit-secret' }), { employeeId: '980023', signaturePassword: 'unit-secret' })
const source = require('node:fs').readFileSync('tests/e2e/edhr-ai-loop/runner.cjs','utf8')
assert.match(source, /data-frontline-production-employee-option="\$\{productionIdentity.employeeId\}"/)
assert.match(source, /data-production-submit-signature-password.*productionIdentity.signaturePassword/)
console.log('PASS: explicit production employee and matching signature credential, no administrator-password substitution')
