const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

const root = path.resolve(__dirname, '../..')
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

const reportApi = read('src/api/mes/pro/batchrecordreport/index.ts')
const permissionApi = read('src/api/mes/pro/edhr/processFormPermissionRule.ts')
const formListPage = read('src/views/mes/pro/batchrecordformlist/index.vue')
const rulesDialog = read('src/views/mes/pro/batchrecordformlist/BatchRecordCellRulesConfirmDialog.vue')
const executionPage = read('src/views/mes/pro/edhr/ExecutionPage.vue')
const feedbackApi = read('src/api/mes/pro/feedback/index.ts')
const realFlowE2E = read('tests/e2e/edhr-visual-fill-config-real-flow.e2e.js')

const includes = (content, token, message) => assert.ok(content.includes(token), message)
const notIncludes = (content, token, message) => assert.ok(!content.includes(token), message)

includes(reportApi, 'BatchRecordReportAssistRowVO', '批记录规则 API 必须声明辅助行 VO。')
includes(reportApi, 'assistRows?: BatchRecordReportAssistRowVO[]', 'cell-rules 请求/响应必须携带 assistRows。')
includes(permissionApi, 'FillAssignment', '填写人 API 必须声明辅助行填写人分配合同。')
includes(permissionApi, 'fillAssignments', 'save-by-report 必须支持按辅助行提交 fillAssignments。')
notIncludes(permissionApi, 'fillRule: EdhrProcessFormCandidateRule\n}', '表单级填写配置不能只支持旧 fillRule 单规则。')

includes(formListPage, '>填写配置<', '表单列表入口文案必须是“填写配置”，不再只是“规则”。')
includes(formListPage, 'openTemplateAction(selectedReport, \'cellRules\')', '填写配置入口必须复用当前表单上下文。')
includes(formListPage, 'BatchRecordCellRulesConfirmDialog', '填写配置必须复用现有单元格规则弹窗。')
includes(formListPage, 'reportId: normalizeRouteQueryText(route.query.reportId) || undefined', '填写配置深链必须把 reportId 传入列表请求，确保目标表单不在第一页时仍可打开。')

includes(rulesDialog, 'title="填写配置"', '规则弹窗标题必须升级为填写配置。')
includes(rulesDialog, '辅助行配置', '弹窗必须提供辅助行配置区域。')
includes(rulesDialog, '辅助行填写人', '填写配置弹窗必须把辅助行交给员工/角色填写。')
includes(rulesDialog, 'assistRows', '弹窗必须维护 assistRows 状态。')
includes(rulesDialog, 'selectedAssistRowKey', '弹窗必须支持选择当前辅助行。')
includes(rulesDialog, 'addAssistRowFromSelectedCell', '弹窗必须支持从当前单元格新增辅助行。')
includes(rulesDialog, 'assignSelectedCellToAssistRow', '弹窗必须支持把当前单元格归入指定辅助行。')
includes(rulesDialog, 'moveAssistRow', '弹窗必须支持辅助行上移/下移。')
includes(rulesDialog, 'removeAssistRow', '弹窗必须支持删除辅助行。')
includes(rulesDialog, '下拉选项', '字段类型配置必须提供下拉选项编辑。')
includes(rulesDialog, 'selectionMode', '下拉框必须复用 STRING + selectionMode=single。')
includes(rulesDialog, 'options', '下拉框选项必须保存到 constraints.options。')
includes(rulesDialog, 'selectedRule.valueType === \'SIGNATURE\'', '签名类型必须有显式签名单元格提示/校验入口。')
includes(rulesDialog, 'EdhrProcessFormPermissionRuleApi.getByReport', '弹窗打开必须读取现有报表填写人配置。')
includes(rulesDialog, 'EdhrProcessFormPermissionRuleApi.saveByReport', '保存填写配置必须复用真实 save-by-report 接口。')
includes(rulesDialog, 'getSimpleUserList', '辅助行填写人必须复用系统用户候选项。')
includes(rulesDialog, 'getSimpleRoleList', '辅助行填写人必须复用系统角色候选项。')
includes(rulesDialog, 'fillAssignments: normalizedAssistAssignmentsForSave', '保存填写配置必须按辅助行提交 fillAssignments。')
includes(rulesDialog, 'const assistRowsForSave = normalizedAssistRowsForSave()', '保存前必须规范化辅助行。')
includes(rulesDialog, 'assistRows: assistRowsForSave', '保存单元格规则时必须同时提交 assistRows。')
notIncludes(rulesDialog, 'catch {}', '填写配置弹窗不能吞掉读取或保存错误。')

includes(feedbackApi, 'ProFeedbackEdhrAssistRowVO', '执行快照 API 类型必须声明 assistRows。')
includes(feedbackApi, 'assistRows?: ProFeedbackEdhrAssistRowVO[]', 'executionSnapshotJson 类型必须包含冻结辅助行。')
includes(executionPage, 'visibleAssistRowsFromExecutionQuery', '执行页必须优先使用 openTask 返回的当前用户 assistRows。')
includes(executionPage, 'snapshotAssistRows', '执行页必须能读取 executionSnapshotJson 冻结辅助行。')
includes(executionPage, 'assistRowsConfigured', '执行页必须区分未配置辅助模式。')
includes(executionPage, '未配置辅助模式', '缺少辅助行时必须展示明确状态。')
includes(executionPage, 'buildAssistFieldsFromAssistRows', '辅助模式字段清单必须由 assistRows 映射到快照字段。')
includes(executionPage, 'draftFieldValues[field.fieldIdentity]', '辅助模式必须复用现有 draftFieldValues。')
notIncludes(executionPage, 'assistDraftFieldValues', '辅助模式不得新增独立草稿对象。')

includes(realFlowE2E, 'local-input.json', '真实 E2E 必须从本地未跟踪配置读取租户、账号和报表夹具。')
includes(realFlowE2E, 'const parsed = JSON.parse', '真实 E2E 必须解析本地配置后显式规范化配置结构。')
includes(realFlowE2E, 'parsed.data && typeof parsed.data === \'object\'', '真实 E2E 必须兼容 data 包裹和顶层本地配置结构。')
includes(realFlowE2E, 'targetReportName', '真实 E2E 必须把目标表单名与批记录夹具名分开。')
includes(realFlowE2E, 'routeProductName', '真实 E2E 必须把路线产品名与任务批记录夹具名分开。')
includes(realFlowE2E, 'configuredExistingWorkOrderCode', '真实 E2E 必须支持显式复用已有金蝶同步工单。')
includes(realFlowE2E, 'restoreVisualFillConfigFixture', '真实 E2E 复用既有报表时必须恢复原始填写配置。')
includes(realFlowE2E, 'assistRowsForRestore', '真实 E2E 恢复既有报表时必须显式区分清空辅助行和空数组校验。')
includes(realFlowE2E, 'assistRows: assistRowsForRestore', '真实 E2E 恢复无辅助行报表必须传 null 清除 edhrAssistRows。')
includes(realFlowE2E, 'batchRecordName: config.batchRecordName', '真实 E2E 导入和阻塞证据必须记录批记录夹具名。')
includes(realFlowE2E, 'projectName: config.routeProductName', '真实 E2E 项目编码必须按路线产品名创建或复用。')
includes(realFlowE2E, 'openVisualFillConfigDialog(page, fixtureReport)', '真实 E2E 必须用任务夹具报表打开填写配置。')
includes(realFlowE2E, 'reportId=${encodeURIComponent(targetReportId)}', '真实 E2E 必须用 reportId 深链确保目标表单进入列表。')
includes(realFlowE2E, "page.locator('.batch-record-form-preview__actions')", '真实 E2E 必须复用报表详情右侧正式操作区。')
includes(realFlowE2E, "page.locator('.el-overlay:visible .batch-record-cell-rules-editor').last()", '真实 E2E 必须在可见填写配置弹窗内操作规则编辑器，不能误点页面背景编辑器。')
notIncludes(realFlowE2E, "page.locator('.batch-record-cell-rules-editor').first()", '真实 E2E 不能用全页第一个规则编辑器，否则弹窗遮罩会拦截背景元素点击。')
includes(realFlowE2E, "firstRuleCell.getAttribute('aria-pressed')", '真实 E2E 必须先判断首个规则格是否已选中。')
notIncludes(realFlowE2E, 'await firstRuleCell.click()', '首个规则格已选中时不能无条件重复点击。')
includes(realFlowE2E, 'ensureTaskOwnedWorkOrderForVisualFill', '真实 E2E 必须通过任务自有 ERP 工单生成员工待办。')
includes(realFlowE2E, '/erp/kingdee-sync/production-order/create', '真实 E2E 必须用正式 ERP 生产工单创建入口准备任务自有工单。')
includes(realFlowE2E, '/mes/pro/work-order/sync-kingdee', '真实 E2E 必须触发正式金蝶工单同步，不得调用 MES 手工工单创建。')
includes(realFlowE2E, '/mes/pro/edhr-batch-execution/open-or-create', '真实 E2E 必须创建或打开匹配路线的 eDHR 批次执行。')
includes(realFlowE2E, 'taskOwnedBatchExecution', '真实 E2E 结果必须记录任务自有批次执行证据。')
includes(realFlowE2E, 'use_configured_existing_work_order', '真实 E2E 使用既有工单时必须显式记录该正式夹具策略。')
includes(realFlowE2E, 'CODX-VFC-BATCH-', '真实 E2E 复用既有工单时仍必须创建任务自有批次编码。')
notIncludes(realFlowE2E, '/mes/pro/work-order/create', '真实 E2E 不得调用被禁止的 MES 手工工单创建接口。')
notIncludes(realFlowE2E, 'projectName: config.batchRecordName', '真实 E2E 不得再用批记录夹具名创建 DCC 项目编码。')
notIncludes(realFlowE2E, 'projectName: config.reportName', '真实 E2E 不得用目标表单名创建 DCC 项目编码。')
notIncludes(realFlowE2E, 'batchRecordName: config.reportName', '真实 E2E 不得把目标表单名写入批记录夹具证据。')
includes(realFlowE2E, 'redactSecretText', '真实 E2E 结果必须脱敏密码等秘密。')
notIncludes(realFlowE2E, 'EDHR_VISUAL_FILL_', '真实 E2E 不得再依赖 EDHR_VISUAL_FILL_* 环境变量。')

console.log('PASS: eDHR visual fill config static contract')
