const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..', '..')
const page = fs.readFileSync(path.join(repoRoot, 'src/views/mes/pro/batchrecordformlist/index.vue'), 'utf8')

const assertIncludes = (content, token, message) => assert.ok(content.includes(token), message)
const assertNotIncludes = (content, token, message) => assert.ok(!content.includes(token), message)

assertIncludes(page, 'UnifiedListTemplate', '批记录表单页必须使用标准列表模板。')
assertIncludes(page, 'table-key="mes.pro.edhrBatch.recordFormList"', '标准列表必须使用稳定表格 key。')
assertIncludes(page, 'recordFormQuickFilterDefinitions', '列表必须保留快速过滤。')
assertIncludes(page, 'recordFormColumns', '列表必须接入显示字段配置。')
assertIncludes(page, '@header-dragend="handleRecordFormHeaderDragend"', '列表必须支持列宽拖拽持久化。')
assertIncludes(page, 'v-model:page="queryParams.pageNo"', '列表必须保留分页页码。')
assertIncludes(page, 'v-model:limit="queryParams.pageSize"', '列表必须保留分页页大小。')
assertIncludes(page, 'class="batch-record-form-preview"', '页面必须提供右侧表单预览区。')
assertIncludes(page, 'BatchRecordReportApi.getCellRules', '右侧表单预览必须读取单元格规则。')
assertIncludes(page, 'BatchRecordReportApi.getSignatureCellMarkers', '右侧表单预览必须读取签名位。')
assertIncludes(page, 'EdhrExecutionReadonlyForm', '右侧表单预览必须复用 eDHR 只读模板组件。')
assertIncludes(page, ':form-view-model="templatePreview.formViewModel"', '右侧表单预览必须传入只读视图模型。')
assertIncludes(page, 'fit-to-viewport', '右侧表单模板必须按视口自适应缩放。')
assertIncludes(page, 'embedded', '右侧表单模板嵌入页面时必须去掉额外外壳。')
assertIncludes(page, 'executionSnapshotJson: JSON.stringify({', '右侧表单模板必须构造执行快照。')
assertIncludes(page, 'buildTemplatePreviewCellValues', '右侧表单模板必须把填写格转换为预览占位值。')
assertIncludes(page, "value: '?'", '右侧表单模板预览必须用问号标识空填写格。')
assertIncludes(page, 'signatureCellMarkers: markerResp.markers || []', '右侧表单模板必须透传签名位。')
assertIncludes(page, 'openSimulate(selectedReport)', '右侧必须提供模拟填写入口。')
assertIncludes(page, "returnLabel: '返回批记录表单'", '模拟填写必须透传当前返回文案。')
assertIncludes(page, 'openTemplateAction(selectedReport, \'signature\')', '右侧必须保留签名入口。')
assertIncludes(page, 'openTemplateAction(selectedReport, \'cellRules\')', '右侧必须保留规则入口。')
assertIncludes(page, 'handleCellLinks(selectedReport)', '右侧必须保留单元格链接入口。')
assertIncludes(page, 'handleRename(selectedReport)', '右侧必须保留重命名操作。')
assertIncludes(page, 'handleDelete(selectedReport)', '右侧必须保留删除单报表操作。')
assertIncludes(page, 'openWordImportDialog', '页面必须保留 Word 导入入口。')
assertIncludes(page, 'deleteSelectedReports(candidates, true)', '批量删除必须支持显式解绑确认后的强制解绑删除。')
assertIncludes(page, 'route.query.reportId', '页面必须支持 reportId 查询参数定位目标表单。')
assertIncludes(page, 'pageSize: 20', '列表必须使用稳定默认页大小。')
assertNotIncludes(page, '/mes/pro/batch-record-template', '页面不得继续跳转旧模板配置 URL。')
assertNotIncludes(page, 'batch-record-toolbar-shell', '页面不应恢复旧顶部大工具栏。')
assertNotIncludes(page, 'catch {}', '页面不得静默吞掉错误。')

console.log('PASS: electronic batch record form list layout static contract')
