const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),vue=require('vue')
const {test}=require('node:test'),{parse,compileTemplate}=require('vue/compiler-sfc')
const root=path.resolve(__dirname,'../..'),filename=path.join(root,'src/views/mes/pro/feedback/FrontlineFixedTemplatePanel.vue')
const descriptor=parse(fs.readFileSync(filename,'utf8')).descriptor
const ast=ts.createSourceFile('frontline.ts',descriptor.scriptSetup.content,ts.ScriptTarget.Latest,true)
const wanted=new Set(['initialHandoffTask','initialHandoffLoading','initialHandoffInvalid','initialHandoffEpoch','initialHandoffPageMounted','hasInitialHandoffQuery','isInitialHandoffBlocked','initializeInitialHandoffSelection'])
const body=ast.statements.filter(s=>ts.isVariableStatement(s)&&s.declarationList.declarations.some(d=>wanted.has(d.name.getText(ast)))).map(s=>s.getText(ast)).join('\n')
assert.equal(ast.statements.filter(s=>ts.isVariableStatement(s)).flatMap(s=>[...s.declarationList.declarations]).filter(d=>wanted.has(d.name.getText(ast))).length,wanted.size)
const navigationCode=ts.transpileModule(fs.readFileSync(path.join(root,'src/utils/activeOrderHandoffNavigation.ts'),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText
const exportsNav={},moduleNav={exports:exportsNav};Function('exports','module','require','window',navigationCode)(exportsNav,moduleNav,()=>({}),{location:{origin:'http://localhost:8081'}})
const taskId='1900000000000000001',otherTaskId='1900000000000000002'
function task(mode='production',active='413',id=taskId){const pqc=mode==='pqc',type=pqc?'PQC_HANDOFF':'PRODUCTION_HANDOFF',source=pqc?'55':active,key=pqc?'pqcTaskId':'cycleId';return{id,activeOrderId:active,workOrderId:'274',routeProcessId:pqc?'91':undefined,taskType:type,sourceType:pqc?'PQC_INSPECTION_TASK':'ACTIVE_ORDER',sourceId:source,roundId:source,status:'TODO',actionUrl:(pqc?'/mes/pro/feedback/edhr-batch-pqc-fill':'/mes/pro/feedback/edhr-batch-production-fill')+'?activeOrderId='+active+'&'+key+'='+source+'&handoffTaskId='+id+'&roundId='+source+'&handoffType='+type}}
const query=t=>Object.fromEntries(new URL(t.actionUrl,'http://localhost:8081').searchParams)
const order=active=>({activeOrderId:Number(active),workOrderId:274,routeId:98})
function harness(mode='production',initial=task(mode)){
 const route=vue.reactive({query:query(initial)}),state=vue.reactive({}),selectedId=vue.ref(),calls=[],errors=[];let context={task:initial,current:true,processable:true};let orders=[order('414'),order('413')]
 let processes=mode==='pqc'?[{activeOrderId:413,qaProcessId:31,pqcTaskOptions:[{pqcTaskId:54,inspectionRuleKey:'FIRST'},{pqcTaskId:55,inspectionRuleKey:'PATROL_AM'}]}]:[{activeOrderId:413,routeProcessId:91,processId:15}]
 const values={ref:vue.ref,computed:vue.computed,route,deviceState:state,isPqcMode:vue.ref(mode==='pqc'),activePqcTaskOptionId:selectedId,payloadPreview:vue.ref(),employeeTemplateCode:vue.ref(),selectedPqcInspectionRuleKey:vue.ref(),currentLoginUserId:vue.ref(344),
 handoffNavigationContext:async id=>{calls.push(['context',id]);return typeof context==='function'?context(id):context},resolveActiveOrderHandoffTarget:exportsNav.resolveActiveOrderHandoffTarget,
 loadFrontlinePqcActiveOrders:async()=>{calls.push(['orders']);return orders},loadFrontlineProductionActiveOrders:async()=>{calls.push(['orders']);return orders},applyActiveOrderToContext:()=>{},
 selectFrontlineProductionActiveOrder:async(_,o)=>{calls.push(['order',o.activeOrderId]);state.selectedActiveOrder=o;return processes},selectFrontlinePqcActiveOrder:async(_,o)=>{calls.push(['order',o.activeOrderId]);state.selectedActiveOrder=o;return processes},
 handleSelectProcess:async p=>{calls.push(['process',p.routeProcessId]);state.selectedProcess=p;state.selectedEmployee={userId:342}},
 clearPqcExecutionSelection:()=>{selectedId.value=undefined},getPqcTaskOptions:p=>p.pqcTaskOptions,selectFrontlinePqcProcess:async(_,p)=>{calls.push(['qaProcess',p.qaProcessId]);state.selectedProcess=p},applyProcessToContext:()=>{},applyPqcTaskOptionToDraft:o=>{calls.push(['pqcTask',o.pqcTaskId]);selectedId.value=o.pqcTaskId},findCurrentLoginEmployee:()=>({userId:344}),handleSelectEmployee:async e=>{state.selectedEmployee=e},showFrontlineError:e=>errors.push(e.message||e)}
 const code=ts.transpileModule(body,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText
 const page=Function(...Object.keys(values),code+';return {initialHandoffTask,initialHandoffLoading,initialHandoffInvalid,hasInitialHandoffQuery,isInitialHandoffBlocked,initializeInitialHandoffSelection};')(...Object.values(values))
 return{page,route,state,selectedId,calls,errors,setContext:v=>context=v,setOrders:v=>orders=v,setProcesses:v=>processes=v}
}
test('真实父 SFC 可编译且保留独立本人 RETURN watcher，初始交接优先于泛用自动工单',()=>{
 assert.deepEqual(compileTemplate({source:descriptor.template.content,filename,id:'initial-handoff'}).errors,[])
 const mount=ast.statements.find(s=>ts.isExpressionStatement(s)&&s.expression.expression?.getText(ast)==='onMounted').getText(ast)
 assert.ok(mount.indexOf('if (hasInitialHandoffQuery.value)')<mount.indexOf('refreshPqcActiveOrdersAndEnsureSelection()'));assert.match(descriptor.scriptSetup.content,/returnTaskId !== undefined[\s\S]*\.openTask\(route.query\)/)
 assert.match(descriptor.scriptSetup.content,/isPqcSubmitBlocked = computed\([\s\S]*?isInitialHandoffBlocked.value/)
})
test('生产整单交接只定位冻结原周期正式路线，不采用列表第一条其他周期',async()=>{const h=harness();await h.page.initializeInitialHandoffSelection();assert.equal(h.state.selectedActiveOrder.activeOrderId,413);assert.deepEqual(h.calls.filter(c=>c[0]==='order'),[['order',413]]);assert.equal(h.state.selectedProcess.routeProcessId,91);assert.equal(h.page.isInitialHandoffBlocked.value,false)})
test('PQC交接定位准确source任务和规程工序，不采用同工序首个不同任务',async()=>{const h=harness('pqc');await h.page.initializeInitialHandoffSelection();assert.equal(h.selectedId.value,55);assert.deepEqual(h.calls.filter(c=>c[0]==='pqcTask'),[['pqcTask',55]]);assert.equal(h.state.selectedProcess.qaProcessId,31);assert.equal(h.page.isInitialHandoffBlocked.value,false)})
test('过期周期、DONE或错误类型链接清空旧选择且不读泛用订单',async()=>{for(const context of [{task:task(),current:false,processable:false},{task:{...task(),status:'DONE'},current:true,processable:false},{task:task('pqc'),current:true,processable:true}]){const h=harness();h.state.selectedActiveOrder=order('414');h.setContext(context);await h.page.initializeInitialHandoffSelection();assert.equal(h.state.selectedActiveOrder,undefined);assert.equal(h.page.isInitialHandoffBlocked.value,true);assert.equal(h.calls.filter(c=>c[0]==='orders').length,0);assert.match(h.errors[0],/已失效|不一致/)}})
test('改task/cycle/source额外参数或伪readOnly均不可选择任务',async()=>{for(const mutation of [{activeOrderId:'414'},{cycleId:'414'},{handoffTaskId:otherTaskId},{handoffReadOnly:'1'},{processId:'15'}]){const h=harness();Object.assign(h.route.query,mutation);await h.page.initializeInitialHandoffSelection();assert.equal(h.state.selectedActiveOrder,undefined);assert.equal(h.page.isInitialHandoffBlocked.value,true)}})
test('原周期不存在或原PQC任务缺失必须明确失败而不默认其他任务',async()=>{const h=harness();h.setOrders([order('414')]);await h.page.initializeInitialHandoffSelection();assert.equal(h.state.selectedActiveOrder,undefined);assert.match(h.errors[0],/本人正式/);const p=harness('pqc');p.setProcesses([{activeOrderId:413,qaProcessId:31,pqcTaskOptions:[{pqcTaskId:54,inspectionRuleKey:'FIRST'}]}]);await p.page.initializeInitialHandoffSelection();assert.equal(p.selectedId.value,undefined);assert.equal(p.state.selectedActiveOrder,undefined);assert.match(p.errors[0],/PQC任务/);assert.equal(p.page.isInitialHandoffBlocked.value,true)})
test('任务读取异常显式失败，旧选中工单不能继续提交',async()=>{const h=harness();h.setContext(()=>{throw Error('formal navigation failed')});h.state.selectedActiveOrder=order('414');await h.page.initializeInitialHandoffSelection();assert.deepEqual(h.errors,['formal navigation failed']);assert.equal(h.page.isInitialHandoffBlocked.value,true);assert.equal(h.state.selectedActiveOrder,undefined)})
test('异步A交接迟到不能覆盖已定位B原周期',async()=>{const h=harness();let resolve;const a=new Promise(ok=>resolve=ok),b=task('production','414',otherTaskId);h.setContext(id=>id===taskId?a:{task:b,current:true,processable:true});const first=h.page.initializeInitialHandoffSelection();h.route.query=query(b);h.setProcesses([{activeOrderId:414,routeProcessId:92,processId:16}]);const second=h.page.initializeInitialHandoffSelection();await second;resolve({task:task(),current:true,processable:true});await first;assert.equal(h.state.selectedActiveOrder.activeOrderId,414);assert.equal(h.page.initialHandoffTask.value.id,otherTaskId);assert.equal(h.page.isInitialHandoffBlocked.value,false)})
test('已定位后切错工单或PQC任务阻止提交',async()=>{const p=harness('pqc');await p.page.initializeInitialHandoffSelection();p.selectedId.value=54;assert.equal(p.page.isInitialHandoffBlocked.value,true);p.selectedId.value=55;p.state.selectedActiveOrder=order('414');assert.equal(p.page.isInitialHandoffBlocked.value,true)})
test('失效交接在真实签名打开与确认方法入口阻止业务动作',async()=>{
 const statements=ast.statements.filter(s=>ts.isVariableStatement(s)&&s.declarationList.declarations.some(d=>['handleValidate','handleConfirmPqcSubmit'].includes(d.name.getText(ast)))).map(s=>s.getText(ast)).join('\n')
 const errors=[],code=ts.transpileModule(statements,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText
 const handlers=Function('hasReturnNotification','isInitialHandoffBlocked','showFrontlineError',code+';return {handleValidate,handleConfirmPqcSubmit};')({value:false},{value:true},e=>errors.push(e))
 await handlers.handleValidate();await handlers.handleConfirmPqcSubmit();assert.equal(errors.length,2);assert.ok(errors.every(e=>e.includes('交接任务已失效')))
})
