const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')
const root = path.resolve(__dirname, '../..')
const page = fs.readFileSync(path.join(root, 'src/views/mes/pro/feedback/FrontlineFixedTemplatePanel.vue'), 'utf8')
assert.ok(!page.includes('data-frontline-input-batch-pending'), 'production UI must not render pending input batch hint')
assert.ok(!page.includes('输入物料批号将在订单完成时回填'), 'production UI must hide completion timing helper text')
const submit = fs.readFileSync(path.join(root, '../IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/feedback/frontline/MesProFrontlineFeedbackSubmitServiceImpl.java'), 'utf8')
assert.match(submit, /"batchEvidenceStatus", "PENDING_COMPLETION"/)
console.log('PASS: production hides input batch helper text while preserving completion status')
