const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const frontendRoot = path.resolve(__dirname, '../..')
const workspaceRoot = path.resolve(frontendRoot, '..')
const read = (relativePath) => fs.readFileSync(path.join(workspaceRoot, relativePath), 'utf8').replace(/\r\n/g, '\n')

const responseVo = read('IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/feedback/vo/frontline/MesFrontlineRuntimeConfigRespVO.java')
const controller = read('IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/feedback/MesFrontlineDeviceAccountController.java')
const context = read('IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/frontline/MesFrontlineProductionSubmitContext.java')
const runtime = read('IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/frontline/MesFrontlineRuntimeConfigServiceImpl.java')
const api = read('IntRuoyiFronted/src/api/mes/pro/feedback/index.ts')
const panel = read('IntRuoyiFronted/src/views/mes/pro/feedback/FrontlineFixedTemplatePanel.vue')

assert.match(responseVo, /private String deviceSelectionSnapshotJson;/)
assert.match(responseVo, /private String deviceSelectionSnapshotSha256;/)
assert.match(controller, /setDeviceSelectionSnapshotJson\(context\.deviceSelectionSnapshotJson\(\)\)/)
assert.match(controller, /setDeviceSelectionSnapshotSha256\(context\.deviceSelectionSnapshotSha256\(\)\)/)
assert.match(context, /String deviceSelectionSnapshotJson,\n\s*String deviceSelectionSnapshotSha256\)/)
assert.match(runtime, /deviceSelectionSnapshotJson\(\)/)
assert.match(runtime, /deviceSelectionSnapshotSha256\(\)/)
assert.match(api, /deviceSelectionSnapshotJson\?: string/)
assert.match(api, /deviceSelectionSnapshotSha256\?: string/)
assert.match(panel, /deviceSelectionSnapshotJson\?: string/)
assert.match(panel, /deviceSelectionSnapshotSha256\?: string/)
assert.match(panel, /snapshotContext\.deviceSelectionSnapshotJson/)
assert.match(panel, /snapshotContext\.deviceSelectionSnapshotSha256/)

console.log('PASS: frontline production submit context exposes device selection snapshot')
