const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const frontendRoot = path.resolve(__dirname, '..', '..')
const viewPath = path.join(frontendRoot, 'src/views/erp/finance/invoice-voucher-print/index.vue')
const loginApiPath = path.join(frontendRoot, 'src/api/login/index.ts')
const erpConfigApiPath = path.join(frontendRoot, 'src/api/erp/config/index.ts')
const erpConfigViewPath = path.join(frontendRoot, 'src/views/erp/config/index.vue')
const envTypesPath = path.join(frontendRoot, 'types/env.d.ts')
const prodEnvPath = path.join(frontendRoot, '.env.prod')
const testEnvPath = path.join(frontendRoot, '.env.test')

assert.ok(fs.existsSync(viewPath), `missing invoice voucher print assistant view: ${viewPath}`)

const viewSource = fs.readFileSync(viewPath, 'utf8')
const loginApiSource = fs.readFileSync(loginApiPath, 'utf8')
const erpConfigApiSource = fs.readFileSync(erpConfigApiPath, 'utf8')
const erpConfigViewSource = fs.readFileSync(erpConfigViewPath, 'utf8')
const envTypes = fs.readFileSync(envTypesPath, 'utf8')
const prodEnv = fs.readFileSync(prodEnvPath, 'utf8')
const testEnv = fs.readFileSync(testEnvPath, 'utf8')

assert.match(viewSource, /defineOptions\(\{\s*name:\s*'ErpInvoiceVoucherPrint'\s*\}\)/)
assert.match(viewSource, /VITE_INVOICE_VOUCHER_PRINT_ASSISTANT_URL/)
assert.match(viewSource, /createInvoiceVoucherPrintTicket/)
assert.match(viewSource, /getInvoiceVoucherPrintAssistantStatus/)
assert.match(viewSource, /startInvoiceVoucherPrintAssistant/)
assert.match(viewSource, /buildAssistantAccessUrl/)
assert.match(viewSource, /auth\/callback/)
assert.match(viewSource, /ticket/)
assert.match(viewSource, /assistantNeedsLaunch/)
assert.match(viewSource, /assistantStarting/)
assert.match(viewSource, /启动助手/)
assert.match(viewSource, /<iframe[\s\S]*:src="assistantAccessUrl"/)
assert.doesNotMatch(viewSource, /<iframe[\s\S]*:src="assistantUrl"/)
assert.match(viewSource, /发票凭证打印助手地址未配置/)
assert.match(viewSource, /发票凭证打印助手状态获取失败/)
assert.match(viewSource, /发票凭证打印助手启动失败/)
assert.doesNotMatch(viewSource, /fenbeitong-voucher/)
assert.doesNotMatch(viewSource, /分贝通凭证/)

assert.match(loginApiSource, /createInvoiceVoucherPrintTicket/)
assert.match(loginApiSource, /\/system\/auth\/invoice-voucher-print-ticket/)
assert.match(loginApiSource, /getInvoiceVoucherPrintAssistantStatus/)
assert.match(loginApiSource, /\/system\/auth\/invoice-voucher-print-assistant\/status/)
assert.match(loginApiSource, /startInvoiceVoucherPrintAssistant/)
assert.match(loginApiSource, /\/system\/auth\/invoice-voucher-print-assistant\/start/)
assert.match(erpConfigApiSource, /appId:\s*string/)
assert.match(erpConfigApiSource, /signedData:\s*string/)
assert.match(erpConfigApiSource, /timestamp:\s*string/)
assert.match(erpConfigViewSource, /v-model="formData\.appId"/)
assert.match(erpConfigViewSource, /v-model="formData\.signedData"/)
assert.match(erpConfigViewSource, /v-model="formData\.timestamp"/)
assert.match(erpConfigViewSource, /appId:\s*\[\{\s*required:\s*true/)
assert.match(erpConfigViewSource, /signedData:\s*\[\{\s*required:\s*true/)
assert.match(erpConfigViewSource, /timestamp:\s*\[\{\s*required:\s*true/)
assert.match(envTypes, /readonly VITE_INVOICE_VOUCHER_PRINT_ASSISTANT_URL: string/)
assert.match(prodEnv, /^VITE_INVOICE_VOUCHER_PRINT_ASSISTANT_URL=$/m)
assert.match(testEnv, /^VITE_INVOICE_VOUCHER_PRINT_ASSISTANT_URL=http:\/\/172\.30\.30\.58:18733\/$/m)
