const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), ts = require('typescript')
const { ref, reactive, computed, watch } = require('vue')
const deferred = () => { let resolve, reject; const promise = new Promise((a,b)=>{resolve=a;reject=b}); return {promise,resolve,reject} }
const tick = async () => { for(let i=0;i<8;i++) await Promise.resolve() }
function execute(relative, names, context, exports) {
 const text=fs.readFileSync(path.resolve(__dirname,'../..',relative),'utf8').match(/<script setup lang="ts">([\s\S]*?)<\/script>/)[1]
 const file=ts.createSourceFile('component.ts',text,ts.ScriptTarget.Latest,true)
 const selected=file.statements.filter(s=>ts.isVariableStatement(s)?s.declarationList.declarations.some(d=>names.includes(d.name.getText(file))):ts.isExpressionStatement(s)&&((names[0].endsWith('DialogVisible')&&s.getText(file).startsWith('watch(')&&s.getText(file).includes(names[0]))||s.getText(file).startsWith('onBeforeUnmount(')))
 const unmount=[];Object.assign(context,{ref,reactive,computed,watch,onBeforeUnmount:fn=>unmount.push(fn)})
 const script=selected.map(s=>s.getText(file)).join('\n')+'\nglobalThis.api={'+exports.join(',')+'}'
 vm.runInNewContext(ts.transpileModule(script,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.None}}).outputText,context)
 return {...context.api,unmount:()=>unmount.forEach(fn=>fn())}
}

const task=id=>({id:'task'+id,businessScopeId:id,batchExecutionId:'batch'+id})
const receipt=(id,status='PENDING_APPROVAL')=>({releaseTransactionId:id,releaseApprovalWorkTaskId:'task'+id,batchExecutionId:'batch'+id,version:1,releaseStatus:status,approvedAt:'now',approvedBy:1})
function harness(overrides={}) {
 const messages=[]
 const context={message:{error:x=>messages.push(x),success:x=>messages.push(x),warning:x=>messages.push(x)},route:{query:{}},loadError:ref(''),getList:async()=>{},canHandleManagerRelease:()=>true,resolveInactionReasonLabel:()=> 'blocked',requireJsonLongId:v=>v,requireNonNegativeVersion:()=>{},requirePositiveVersion:()=>{},resolveManagerReleaseStatusLabel:v=>v,resolveErrorMessage:(e,d)=>e?.message||d,resolvePqcProductionReleaseFailure:e=>e?.blockers?e:undefined,getEdhrRelease:async id=>receipt(id),reviewApprovalTask:async()=>{},getEdhrStage5ReleaseSnapshot:async()=>{},...overrides}
 const names=['managerReleaseDialogVisible','managerReleaseLoading','managerReleaseSubmitting','managerReleaseTask','managerReleaseReceipt','managerReleaseSnapshot','managerReleaseBlockers','managerReleaseUncertainMessage','managerReleaseLockedTransactionIds','managerReleaseFormRef','managerReleaseForm','managerReleaseDialogGeneration','captureManagerReleaseContext','resetManagerReleaseDialog','requireManagerReleaseTaskContext','assertManagerReleaseReceiptMatchesTask','assertManagerReleaseApprovalResult','openManagerReleaseDialog','recoverUncertainManagerReleaseApproval','refreshManagerReleaseListAfterSuccess','loadStage5ReleaseSnapshot','submitManagerReleaseApproval']
 const h=execute('src/views/mes/pro/edhr-work-task/WorkTaskBoardPage.vue',names,context,names.filter(n=>!['managerReleaseDialogGeneration','captureManagerReleaseContext'].includes(n)))
 h.managerReleaseFormRef.value={validate:async()=>{},clearValidate:()=>{}}
 return {...h,messages,context}
}
for(const same of [false,true]) test(`manager late read ignores ${same?'same-order reopen':'other-order switch'}`,async()=>{const d=deferred();let count=0;const h=harness({getEdhrRelease:id=>++count===1?d.promise:Promise.resolve(receipt(id))});const p=h.openManagerReleaseDialog(task('A'));h.managerReleaseDialogVisible.value=false;await h.openManagerReleaseDialog(task(same?'A':'B'));d.resolve(receipt('A','RELEASED'));await p;assert.equal(h.managerReleaseReceipt.value.releaseStatus,'PENDING_APPROVAL')})
test('manager late load error/finally do not block newer pending load',async()=>{const a=deferred(),b=deferred();let n=0;const h=harness({getEdhrRelease:()=>++n===1?a.promise:b.promise});const p=h.openManagerReleaseDialog(task('A'));h.managerReleaseDialogVisible.value=false;const q=h.openManagerReleaseDialog(task('B'));a.reject(Error('old'));await p;assert.equal(h.managerReleaseUncertainMessage.value,'');assert.equal(h.managerReleaseLoading.value,true);b.resolve(receipt('B'));await q})
test('manager late write response does not read or mutate current dialog',async()=>{const d=deferred();const calls=[];const h=harness({reviewApprovalTask:()=>d.promise,getEdhrRelease:async id=>{calls.push(id);return receipt(id)}});await h.openManagerReleaseDialog(task('A'));const p=h.submitManagerReleaseApproval();await tick();h.managerReleaseDialogVisible.value=false;await h.openManagerReleaseDialog(task('B'));h.managerReleaseForm.signaturePassword='new';d.resolve();await p;assert.deepEqual(calls,['A','B']);assert.equal(h.managerReleaseForm.signaturePassword,'new');assert.equal(h.messages.length,0)})
test('manager old submit error does not overwrite current error/blockers',async()=>{const d=deferred();const h=harness({reviewApprovalTask:()=>d.promise});await h.openManagerReleaseDialog(task('A'));const p=h.submitManagerReleaseApproval();await tick();h.managerReleaseDialogVisible.value=false;await h.openManagerReleaseDialog(task('B'));d.reject({blockers:[{reason:'old'}]});await p;assert.equal(h.managerReleaseBlockers.value.length,0);assert.equal(h.messages.length,0)})
test('manager normal success and current load errors visible',async()=>{let n=0;const h=harness({getEdhrRelease:async id=>receipt(id,++n===1?'PENDING_APPROVAL':'RELEASED')});await h.openManagerReleaseDialog(task('A'));await h.submitManagerReleaseApproval();assert.equal(h.managerReleaseReceipt.value.releaseStatus,'RELEASED');assert.ok(h.messages.length);const bad=harness({getEdhrRelease:async()=>{throw Error('current')}});await bad.openManagerReleaseDialog(task('A'));assert.equal(bad.managerReleaseUncertainMessage.value,'current')})
test('manager unmount invalidates read',async()=>{const d=deferred();const h=harness({getEdhrRelease:()=>d.promise});const p=h.openManagerReleaseDialog(task('A'));h.unmount();d.resolve(receipt('A'));await p;assert.equal(h.managerReleaseReceipt.value,null)})

test('manager late recovery error does not lock another session',async()=>{const d=deferred();let reads=0;const h=harness({reviewApprovalTask:async()=>{throw Error('network')},getEdhrRelease:id=>++reads===2?d.promise:Promise.resolve(receipt(id))});await h.openManagerReleaseDialog(task('A'));const p=h.submitManagerReleaseApproval();await tick();h.managerReleaseDialogVisible.value=false;await h.openManagerReleaseDialog(task('B'));d.reject(Error('late receipt'));await p;assert.equal(h.managerReleaseLockedTransactionIds.size,0);assert.equal(h.managerReleaseUncertainMessage.value,'');assert.equal(h.messages.length,0)})
test('manager late post-write receipt does not replace newer session',async()=>{const d=deferred();let reads=0;const h=harness({getEdhrRelease:id=>++reads===2?d.promise:Promise.resolve(receipt(id))});await h.openManagerReleaseDialog(task('A'));const p=h.submitManagerReleaseApproval();await tick();h.managerReleaseDialogVisible.value=false;await h.openManagerReleaseDialog(task('B'));d.resolve(receipt('A','RELEASED'));await p;assert.equal(h.managerReleaseReceipt.value.releaseTransactionId,'B');assert.equal(h.messages.length,0)})
test('manager late stage snapshot cannot populate another dialog',async()=>{const d=deferred();let reads=0;const h=harness({route:{query:{simulationRunId:'run'}},getEdhrRelease:async id=>receipt(id,++reads===2?'RELEASED':'PENDING_APPROVAL'),getEdhrStage5ReleaseSnapshot:()=>d.promise});await h.openManagerReleaseDialog(task('A'));const p=h.submitManagerReleaseApproval();await tick();h.managerReleaseDialogVisible.value=false;await h.openManagerReleaseDialog(task('B'));d.resolve({releaseStatus:'RELEASED',releaseReceiptId:1,releaseDecisionId:2,fourMaterialEvidence:[1,2,3,4]});await p;assert.equal(h.managerReleaseSnapshot.value,null);assert.equal(h.managerReleaseReceipt.value.releaseTransactionId,'B');assert.equal(h.messages.length,0)})
test('manager actual list statistics ignore expired owner',async()=>{const d=deferred();let current=true;const context={loading:ref(false),loadError:ref(''),list:ref([]),total:ref(0),stats:reactive({todo:1}),activeTab:ref('candidate'),buildQuery:()=>({}),resolveMyPageStatus:()=>'',getEdhrWorkTaskCandidateTodoPage:async()=>({list:[1],total:1}),getEdhrWorkTaskStats:()=>d.promise,resolveErrorMessage:e=>e.message};const h=execute('src/views/mes/pro/edhr-work-task/WorkTaskBoardPage.vue',['getList','workTaskListSequence','refreshStats'],context,['getList']);const p=h.getList(()=>current);await tick();current=false;d.resolve({todo:99});await p;assert.equal(context.stats.todo,1)})

test('manager old submit does not clear new same-order submitting state',async()=>{const a=deferred(),b=deferred();let writes=0;const h=harness({reviewApprovalTask:()=>++writes===1?a.promise:b.promise});await h.openManagerReleaseDialog(task('A'));const p=h.submitManagerReleaseApproval();await tick();h.managerReleaseDialogVisible.value=false;await h.openManagerReleaseDialog(task('A'));const q=h.submitManagerReleaseApproval();await tick();a.reject({blockers:[{reason:'old'}]});await p;assert.equal(h.managerReleaseSubmitting.value,true);assert.equal(h.managerReleaseBlockers.value.length,0);b.reject({blockers:[{reason:'current'}]});await q;assert.equal(h.managerReleaseSubmitting.value,false);assert.equal(h.managerReleaseBlockers.value[0].reason,'current');assert.equal(h.messages.length,1)})
test('manager switch during validation prevents obsolete submission',async()=>{const d=deferred();let writes=0;const h=harness({reviewApprovalTask:async()=>writes++});await h.openManagerReleaseDialog(task('A'));h.managerReleaseFormRef.value.validate=()=>d.promise;const p=h.submitManagerReleaseApproval();h.managerReleaseDialogVisible.value=false;await h.openManagerReleaseDialog(task('B'));d.resolve();await p;assert.equal(writes,0)})

test('manager duplicate clicks during validation produce one write',async()=>{const d=deferred(),write=deferred();let writes=0;const h=harness({reviewApprovalTask:()=>{writes++;return write.promise}});await h.openManagerReleaseDialog(task('A'));h.managerReleaseFormRef.value.validate=()=>d.promise;const first=h.submitManagerReleaseApproval(),second=h.submitManagerReleaseApproval();d.resolve();await tick();assert.equal(writes,1);write.reject({blockers:[{reason:'finished'}]});await Promise.all([first,second])})
