const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '../..')
const api = fs.readFileSync(path.join(root, 'src/api/mes/pro/edhr/deviation.ts'), 'utf8')
const list = fs.readFileSync(path.join(root, 'src/views/mes/pro/edhr-deviation/index.vue'), 'utf8')
const detail = fs.readFileSync(path.join(root, 'src/views/mes/pro/edhr-deviation/DeviationDetail.vue'), 'utf8')
const tabs = fs.readFileSync(path.join(root, 'src/views/mes/pro/edhr-batch/EdhrBatchRecordTabs.vue'), 'utf8')
const batchDetail = fs.readFileSync(path.join(root, 'src/views/mes/pro/edhr-batch/BatchExecutionDetailPage.vue'), 'utf8')
const activeOrderDetail = fs.readFileSync(path.join(root, 'src/views/mes/pro/edhr-batch/BatchExecutionActiveOrderDetailPage.vue'), 'utf8')
const routes = fs.readFileSync(path.join(root, 'src/router/modules/remaining.ts'), 'utf8')

assert.match(api, /\/mes\/pro\/edhr-deviation\/page/)
assert.match(api, /\/mes\/pro\/edhr-deviation\/get/)
assert.match(api, /getDeviationHandling/)
assert.match(api, /createDeviation/)
assert.match(api, /saveDeviationHandling/)
assert.match(api, /signDeviationHandling/)
assert.match(api, /closeDeviationHandling/)
assert.match(api, /batch-options/)
assert.match(api, /batch-options-by-active-order/)
assert.match(list, /UnifiedListTemplate/)
assert.match(list, /发起偏差/)
assert.match(list, /签名并发起/)
assert.match(list, /全部/)
assert.match(list, /未处理/)
assert.match(list, /已处理/)
assert.match(list, /没有偏差/)
assert.match(list, /偏差详情加载失败|偏差查询失败/)
assert.match(detail, /尚未填写处理内容/)
assert.match(detail, /开始处理/)
assert.match(detail, /v-hasPermi="\['mes:pro-edhr-deviation:handle'\]"/)
assert.match(detail, /startHandling/)
assert.match(detail, /normalizeOptionalJson/)
assert.match(detail, /investigationMembersJson:\s*normalizeOptionalJson/)
assert.match(detail, /capaAttachmentsJson:\s*normalizeOptionalJson/)
assert.match(detail, /closeReason/)
assert.match(detail, /nonconformanceReviewId/)
assert.match(detail, /initiatorSignatureId/)
assert.match(detail, /initiatorContentHash/)
assert.match(detail, /唯一处理记录/)
assert.match(detail, /signatureEvidence/)
assert.match(detail, /保存处理/)
assert.match(detail, /签署当前节点/)
assert.match(detail, /常规关闭/)
assert.match(detail, /actorDisplayName/)
assert.match(detail, /timeEvidenceId/)
assert.match(detail, /evidenceHash/)
assert.match(detail, /signatureHistory/)
assert.match(detail, /SUPERSEDED_INVALID|validityStatus/)
assert.match(detail, /revisionHistory/)
assert.match(detail, /偏差处理记录加载失败，请重试/)
assert.match(list, /没有偏差查询权限|登录状态已失效/)
assert.match(fs.readFileSync(path.join(root, 'src/views/mes/pro/edhr/components/DeviationTracePane.vue'), 'utf8'), /重试/)
assert.doesNotMatch(detail, /catch \{ handling\.value = undefined \}/)
assert.match(tabs, /label="偏差"/)
assert.match(activeOrderDetail, /activeOrderId/)
assert.match(activeOrderDetail, /batch-options-by-active-order|getDeviationBatchOptionsByActiveOrder/)
assert.match(batchDetail, /正式批记录详情主视图/)
assert.match(batchDetail, /mainViewTab === 'deviation'/)
assert.match(tabs, /deviation: '\/mes\/pro\/feedback\/edhr-deviation'/)
assert.match(routes, /pro\/feedback\/edhr-deviation/)

console.log('PASS: eDHR deviation P3 frontend static contract')
