const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '../..')
const api = fs.readFileSync(path.join(root, 'src/api/mes/pro/edhr/nonconformanceReview.ts'), 'utf8')
const detail = fs.readFileSync(path.join(root, 'src/views/mes/pro/edhr-deviation/DeviationDetail.vue'), 'utf8')
assert.match(api, /SOURCE_TYPE_DEVIATION/)
assert.match(api, /createCriticalDeviationReview/)
assert.match(api, /create-from-critical-deviations/)
assert.match(api, /deviationIds: EdhrRouteId\[\]/)
assert.match(detail, /发起不合格审批/)
assert.match(detail, /createCriticalDeviationReview/)
assert.match(detail, /ncrCreateVisible/)
assert.match(detail, /signaturePassword/)
assert.match(detail, /detail\.status === 'OPEN' && detail\.level === 'CRITICAL'/)
assert.match(detail, /mes:pro-edhr-nonconformance-review:deviation-create/)
assert.doesNotMatch(detail, /验证合格|默认合格/)
console.log('PASS: eDHR critical deviation NCR P4 frontend contract')
