const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const source = fs.readFileSync(path.resolve(__dirname, '../../src/views/mes/pro/production-release/PqcProductionReleasePage.vue'), 'utf8')
const marker = source.indexOf('data-pqc-production-release-detail')
assert.ok(marker >= 0, 'PQC release needs a detail action')
assert.ok(marker < source.indexOf('data-pqc-production-release-approve'), 'Detail precedes release')
assert.match(source, /@click="openActiveOrderDetail\(row\)"/)
assert.match(source, /:disabled="!hasActiveOrderDetail\(row\)"/)
const start = source.indexOf('const openActiveOrderDetail =')
const end = source.indexOf('\nconst ', start + 1)
assert.ok(start >= 0 && end > start)
const handler = source.slice(start, end)
assert.match(handler, /getPqcProductionReleaseOrderDetail\(row.applicationId\)/)
assert.doesNotMatch(handler, /router\.push|router\.replace|getTeamLeaderActiveOrderDetail/)
assert.match(source, /data-pqc-production-release-detail-back/)
assert.match(source, /ActiveOrderSubmissionDetailPanel/)
console.log('PASS: PQC-owned inline detail and return preserve list context')
