const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

const frontendRoot = path.resolve(__dirname, '../..')
const backendRoot = path.resolve(frontendRoot, '../IntRuoyiBackend')
const read = (relativePath) => fs.readFileSync(path.resolve(frontendRoot, relativePath), 'utf8')
const readBackend = (relativePath) => fs.readFileSync(path.resolve(backendRoot, relativePath), 'utf8')

const releaseApi = read('src/api/mes/pro/productionRelease/index.ts')
const releasePage = read('src/views/mes/pro/production-release/PqcProductionReleasePage.vue')
const detailPanel = read('src/views/mes/pro/processpool/components/ActiveOrderSubmissionDetailPanel.vue')
const teamLeaderApi = read('src/api/mes/pro/processpool/teamLeader.ts')
const approveReq = readBackend('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/productionrelease/vo/MesPqcProductionReleaseApproveReqVO.java')
const approveCommand = readBackend('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/productionrelease/pqc/MesPqcProductionReleaseApproveCommand.java')
const activeOrder = readBackend('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/dal/dataobject/pro/processpool/team/MesProcessPoolActiveOrderDO.java')
const detail = readBackend('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesTeamLeaderActiveOrderDetail.java')
const udiPolicy = readBackend('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/productionrelease/pqc/MesPqcProductionReleaseUdiPolicy.java')
const pqcService = readBackend('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/productionrelease/pqc/MesPqcProductionReleaseServiceImpl.java')
const detailService = readBackend('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesTeamLeaderActiveOrderDetailServiceImpl.java')
const detailController = readBackend('yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/controller/admin/pro/processpool/team/MesProcessPoolTeamLeaderController.java')

assert.match(approveReq, /udiControlDocumentNo/)
assert.match(approveReq, /@NotBlank[\s\S]*udiControlDocumentNo/)
assert.match(approveCommand, /udiControlDocumentNo/)
assert.match(activeOrder, /udiControlDocumentNo/)
assert.match(detail, /udiControlDocumentNo/)
assert.match(udiPolicy, /MAX_LENGTH = 128/)
assert.match(udiPolicy, /requireNormalized/)
assert.match(pqcService, /requireUdiControlDocumentNo/)
assert.match(pqcService, /writeUdiControlDocumentNo/)
assert.match(pqcService, /decisionPayloadHash\([\s\S]*udiControlDocumentNo/)
assert.match(detailService, /setUdiControlDocumentNo\(activeOrder\.getUdiControlDocumentNo\(\)\)/)
assert.match(detailController, /setUdiControlDocumentNo\(detail\.getUdiControlDocumentNo\(\)\)/)
assert.match(releaseApi, /udiControlDocumentNo: string/)
assert.match(releasePage, /label="UDI编号"/)
assert.doesNotMatch(releasePage, /线下 UDI 文件编号/)
assert.match(releasePage, /data-pqc-production-release-udi-document-no/)
assert.match(releasePage, /releaseForm\.udiControlDocumentNo\.trim\(\)/)
assert.match(releasePage, /udiControlDocumentNo:/)
assert.match(detailPanel, /<th>UDI编号<\/th>/)
assert.doesNotMatch(detailPanel, /线下 UDI 文件编号/)
assert.match(detailPanel, /未填写/)
assert.match(teamLeaderApi, /udiControlDocumentNo\?: string/)
const rejectContract = releaseApi.slice(
  releaseApi.indexOf('export interface MesPqcProductionReleaseRejectReqVO'),
  releaseApi.indexOf('export interface MesPqcProductionReleaseDecisionRespVO')
)
assert.doesNotMatch(rejectContract, /udiControlDocumentNo/)

console.log('PASS: PQC release UDI frontend/backend contract')
