const fs = require('node:fs')
const assert = require('node:assert/strict')
const page = fs.readFileSync('src/views/mes/pro/edhr-work-task/WorkTaskBoardPage.vue', 'utf8')
const submit = page.slice(page.indexOf('const submitManagerReleaseApproval ='), page.indexOf('const openTask ='))
assert.match(submit, /reviewApprovalTask\(/, 'Manager release must invoke the real password signature workflow')
assert.match(page, /v-model="managerReleaseForm.signaturePassword"/, 'Manager release requires a password input')
assert.doesNotMatch(page, /v-model="managerReleaseForm.signoffEvidenceHash"/, 'Signature hashes must not be entered manually')
assert.doesNotMatch(page, /managerReleaseForm\.signoffEvidenceHash/, 'Signature evidence must come from the approval center')
assert.match(submit, /getEdhrRelease\(/, 'Read authoritative release receipt after the signature workflow')
console.log('PASS: manager release password signature entry')
