const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const frontendRoot = path.resolve(__dirname, '../..')
const workspaceRoot = path.resolve(frontendRoot, '..')
const pagePath = path.join(frontendRoot, 'src/views/mes/pro/processpool/TeamLeaderWorkbenchPage.vue')
const apiPath = path.join(frontendRoot, 'src/api/mes/pro/processpool/teamLeader.ts')
const mapperPath = path.join(workspaceRoot, 'IntRuoyiBackend/yudao-module-mes/src/main/resources/mapper/pro/processpool/MesProProcessPoolTimelineReadMapper.xml')
const commandPath = path.join(workspaceRoot, 'IntRuoyiBackend/yudao-module-mes/src/main/java/cn/iocoder/yudao/module/mes/service/pro/processpool/team/MesReportAllocationCommandService.java')

const page = fs.readFileSync(pagePath, 'utf8')
const api = fs.readFileSync(apiPath, 'utf8')
const mapper = fs.readFileSync(mapperPath, 'utf8')
const command = fs.readFileSync(commandPath, 'utf8')

assert.match(page, /data-production-report-reject-event-id/)
assert.match(page, /canRejectProductionSubmission[\s\S]*row\.reportAllocations[\s\S]*released/)
assert.match(page, /reviewDialogMode = ref<'REVIEW' \| 'ALLOCATION' \| 'REJECTION'>/)
assert.match(page, /if \(reviewDialogMode\.value === 'REJECTION'\) return '驳回生产报工'/)
assert.match(page, /reviewStatus: 'REJECTED'/)
assert.match(page, /reviewTeamLeaderSubmission\(\{[\s\S]*reviewStatus: 'REJECTED'/)
assert.match(page, /reviewForm\.reviewStatus === 'REJECTED'[\s\S]*驳回生产报工必须填写驳回原因|退回复核必须填写复核说明/)
assert.match(page, /productionHistory\.reject-v1/)
assert.match(page, /label="处理结果"/)
assert.match(page, /label="处理说明"/)
assert.match(page, /reviewDialogMode !== 'ALLOCATION'/)
assert.match(page, /isProductionLeader\.value &&[\s\S]*reviewDialogMode\.value === 'REJECTION'/)
assert.match(api, /reviewStatus: SubmissionReviewStatus/)
assert.match(mapper, /allocationView == 'WORKBENCH'[\s\S]*latest_submission_review\.review_status[\s\S]*REJECTED/)
assert.match(command, /rejectProductionSubmission\(/)
assert.match(command, /SOURCE_SUBMISSION_REJECTED/)
assert.match(command, /quantityFragmentService\.rebuildForVersion\(event, rejectedVersion, List\.of\(\)\)/)
assert.match(command, /completionService\.reconcileAffectedAllocations\(event, current\)/)
assert.match(command, /REPORT_ALLOCATION_RELEASED_LOCKED/)

console.log('PASS production-report-rejection-static')
