const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '../..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const parent = read('src/views/showroom-admin/index.vue')
const target = read('src/views/showroom-admin/assignment/AssignmentWorkbench.vue')
const entry = read('src/views/Profile/components/ProfileWorkbench.vue')
assert.match(entry, /name: 'ShowroomAdminAssignment'[\s\S]*assignmentId: requireNavigationId/)
assert.match(parent, /<AssignmentWorkbench[\s\S]*:route-assignment-id="route.query.assignmentId"/)
assert.match(target, /watch\(\(\) => props.routeAssignmentId[\s\S]*immediate: true/)
const exactBranch = target.slice(target.indexOf('if (routeIdentity !== undefined) {'),
  target.indexOf('const page = await request.get'))
assert.match(exactBranch, /typeof routeIdentity !== 'string'/)
assert.match(exactBranch, /await loadAssignmentDetail\(routeIdentity\)/)
assert.match(exactBranch, /rows.value = \[detail\]/)
assert.match(exactBranch, /setCurrentRow\(detail\)/)
assert.doesNotMatch(exactBranch, /rows.value\[0\]|\/assignment\/page/)
assert.match(target, /url: '\/showroom\/assignment\/get', params: \{ id: requestedId \}/)
assert.match(target, /String\(detail.assignmentId\) !== requestedId/)
assert.match(target, /generation !== selectionGeneration/)
assert.match(target, /generation !== listGeneration/)
assert.match(target, /loadError.value = resolved.message/)
assert.match(target, /pageSize: 20/)
console.log('PASS: exact showroom task navigation static contract (runtime unverified)')
