const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = process.cwd()
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8').replace(/\r\n/g, '\n')

const qaPage = read('src/views/mes/pro/processpool/QaRegulationPage.vue')
const configPanel = read('src/views/mes/pro/processpool/PqcItemEquipmentConfigPanel.vue')
const qaApi = read('src/api/mes/qc/template/index.ts')
const teamLeaderApi = read('src/api/mes/pro/processpool/teamLeader.ts')
const pqcWorkbench = read('src/views/mes/pro/processpool/PqcLeaderWorkbenchPage.vue')
const teamLeaderWorkbench = read('src/views/mes/pro/processpool/TeamLeaderWorkbenchPage.vue')

assert.match(qaPage, /<el-tab-pane label="检验设备" name="equipment"/)
assert.match(qaPage, /<PqcItemEquipmentConfigPanel[\s\S]*:dcc-project-code-id="Number\(selectedDccProjectCode\.id\)"/)
assert.doesNotMatch(qaPage, /<PqcItemEquipmentConfigPanel[\s\S]*selectedProjectName/)
assert.match(configPanel, /defineProps<\{[\s\S]*dccProjectCodeId: number[\s\S]*projectName: string/)
assert.doesNotMatch(configPanel, /selectedProjectName|projectOptions|data-pqc-item-equipment-project-select/)
assert.match(configPanel, /getPqcItemEquipmentItems\(props\.dccProjectCodeId\)/)
assert.match(configPanel, /item\.dccProjectCodeId === props\.dccProjectCodeId/)
assert.match(configPanel, /new Map<string, PqcItemEquipmentItemVO>\(\)/)
assert.match(configPanel, /itemCode: selectedItemCode\.value/)
assert.match(qaApi, /getPqcItemEquipmentItems: async \(\s*dccProjectCodeId: number\s*\)/)
assert.match(qaApi, /getPqcItemEquipmentConfig: async \(itemCode: string\)/)
assert.match(qaApi, /savePqcItemEquipmentConfig: async/)
assert.doesNotMatch(teamLeaderApi, /PqcItemEquipmentItemVO|getPqcItemEquipmentItems|savePqcItemEquipmentConfig/)
assert.doesNotMatch(pqcWorkbench, /show-pqc-equipment-tab/)
assert.doesNotMatch(teamLeaderWorkbench, /PqcItemEquipmentConfigPanel|data-pqc-leader-module-tab-equipment/)

console.log('PASS: QA owns the tenant PQC equipment configuration tab and exact project context')
