const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '../..')
const page = fs.readFileSync(path.join(root, 'src/views/system/backup-plan/index.vue'), 'utf8')
const api = fs.readFileSync(path.join(root, 'src/api/system/backupPlan/index.ts'), 'utf8')

assert.match(api, /fullSchedule:\s*string/, '计划 API 必须包含每周全量计划。')
assert.match(api, /incrementalSchedule:\s*string/, '计划 API 必须包含每日增量计划。')
assert.match(api, /retentionSource:\s*string/, '保存计划请求必须携带保存期限来源。')
assert.match(api, /qualityApprovalRef:\s*string/, '保存计划请求必须携带质量批准引用。')
assert.match(api, /backupNow\s*=\s*\(backupKind:\s*BackupKind\)/, '立即备份必须显式传 FULL 或 INCREMENTAL。')
assert.match(api, /params:\s*\{\s*backupKind\s*\}/, '立即备份请求必须携带 backupKind。')
assert.match(api, /\/infra\/backup-plan\/evidence\/export/, '必须调用后端证据导出接口。')
assert.match(api, /responseType:\s*'blob'/, '证据导出必须按 blob 下载。')

assert.match(page, /每周全量备份/, '页面必须显示全量计划。')
assert.match(page, /周一至周六增量备份/, '页面必须显示周日全量替代后的增量计划。')
assert.match(page, /保存期限来源/, '页面必须展示保存期限来源。')
assert.match(page, /质量批准引用/, '页面必须展示质量批准引用。')
assert.match(page, /立即全量备份/, '页面必须有明确的全量动作。')
assert.match(page, /立即增量备份/, '页面必须有明确的增量动作。')
assert.match(page, /导出审查证据/, '页面必须有一键证据导出。')
assert.match(page, /icon="ep:download"/, '证据导出按钮必须使用下载图标。')
assert.match(page, /handleBackupNow\('FULL'\)/, '全量按钮必须提交 FULL。')
assert.match(page, /handleBackupNow\('INCREMENTAL'\)/, '增量按钮必须提交 INCREMENTAL。')
assert.match(page, /backupNow\(backupKind\)/, '处理函数必须把所选类型传给 API。')
assert.match(api, /backupKind\?:\s*'FULL'\s*\|\s*'INCREMENTAL'/, '历史响应必须暴露真实备份类型。')
assert.match(api, /baseBackupId\?:\s*string/, '历史响应必须暴露全量基线。')
assert.match(api, /parentBackupId\?:\s*string/, '历史响应必须暴露直接父点。')
assert.match(page, /label="备份链"/, '历史列表必须展示备份链。')
assert.match(page, /formatBackupChain/, '备份链必须由后端权威字段展示。')
assert.match(page, /system:backup-plan:evidence-export/, '证据导出必须受独立权限控制。')
assert.match(page, /downloadBackupEvidence/, '页面必须通过统一 API 下载证据。')
assert.match(page, /备份审查证据导出失败/, '导出失败必须明确显示，不得静默。')
assert.match(page, /retentionSource:\s*scheduleForm\.retentionSource/, '保存计划必须提交保存期限来源。')
assert.match(page, /qualityApprovalRef:\s*scheduleForm\.qualityApprovalRef/, '保存计划必须提交质量批准引用。')
