const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '../..')
const page = fs.readFileSync(path.join(root, 'src/views/mes/pro/processpool/TeamLeaderWorkbenchPage.vue'), 'utf8')
const api = fs.readFileSync(path.join(root, 'src/api/mes/pro/processpool/teamLeader.ts'), 'utf8')
assert.match(page, /data-team-leader-push-pqc-stage3/)
const start = page.indexOf('const handlePushGeneratedPqcRelease =')
assert.ok(start >= 0, 'P3 handler is required')
const end = page.indexOf('\nconst ', start + 1)
assert.ok(end > start)
const handler = page.slice(start, end)
assert.match(handler, /pushGeneratedTeamLeaderActiveOrderRelease\(/)
assert.match(handler, /assertActiveOrderReleaseApplicationReceipt\(/)
assert.match(handler, /await loadActiveOrders\(\)/)
assert.doesNotMatch(handler, /simulateStage|applyWithNoReplenishmentConfirmation|router\.push|router\.replace/)
assert.match(api, /active-order\/release\/push-generated/)
console.log('PASS: P3 pushes existing P2 records without simulation or navigation')
