const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const frontendRoot = path.resolve(__dirname, '../..')
const readUtf8 = (file) => fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n')
const page = readUtf8(path.join(frontendRoot, 'src/views/mes/pro/processpool/TeamLeaderWorkbenchPage.vue'))
const api = readUtf8(path.join(frontendRoot, 'src/api/mes/pro/processpool/teamLeader.ts'))

assert.match(page, /一键清理生产数据/, '生产组长工作台必须提供一键清理生产数据按钮。')
assert.match(page, /data-team-leader-data-cleanup/, '一键清理按钮和确认弹窗必须提供稳定测试属性。')
assert.match(page, /v-hasPermi=\"\['mes:pro-process-pool-team-leader:maintain'\]\"/, '清理按钮必须受生产组长维护权限保护。')
assert.match(page, /handleTeamLeaderDataCleanup/, '页面必须通过正式清理处理函数提交请求。')
assert.match(page, /活跃订单.*报工管理\/历史.*批次执行/, '确认文案必须明确列出全部清理范围。')
assert.match(page, /生产放行申请.*生产放行事务/, '确认文案必须明确生产放行链路会被纳入清理。')
assert.match(page, /不需要逐单上传订单号/, '确认文案必须说明后端自动解析范围，不要求逐单上传。')
assert.match(api, /previewTeamLeaderDataCleanup/, '前端 API 必须提供清理预检请求。')
assert.match(api, /executeTeamLeaderDataCleanup/, '前端 API 必须提供清理执行请求。')
assert.match(api, /releaseApplicationCount: number/, '前端 API 必须接收生产放行申请清理数量。')
assert.match(api, /releaseTransactionCount: number/, '前端 API 必须接收生产放行事务清理数量。')
assert.match(api, /active-order\/data-cleanup\/preview/, '预检 API 路径必须绑定生产组长工作台。')
assert.match(api, /active-order\/data-cleanup\/execute/, '执行 API 路径必须绑定生产组长工作台。')

console.log('PASS: team leader data cleanup static contract')
