const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '../..')
const unifiedListTemplatePath = path.join(root, 'src/components/UnifiedListTemplate/index.vue')
const multiFilterComponentPath = path.join(root, 'src/components/TableMultiFilter/index.vue')
const multiFilterFieldPath = path.join(root, 'src/components/TableMultiFilter/MultiFilterField.vue')
const multiFilterHookPath = path.join(root, 'src/hooks/web/useTableMultiFilter.ts')

assert.equal(fs.existsSync(unifiedListTemplatePath), true, '统一列表模板组件必须存在。')
assert.equal(fs.existsSync(multiFilterComponentPath), true, '多维度筛选组件必须存在。')
assert.equal(fs.existsSync(multiFilterFieldPath), true, '多维度筛选字段组件必须存在。')
assert.equal(fs.existsSync(multiFilterHookPath), true, '多维度筛选 hook 必须存在。')

const unifiedListTemplateSource = fs.readFileSync(unifiedListTemplatePath, 'utf8')
const multiFilterComponentSource = fs.readFileSync(multiFilterComponentPath, 'utf8')
const multiFilterFieldSource = fs.readFileSync(multiFilterFieldPath, 'utf8')
const multiFilterHookSource = fs.readFileSync(multiFilterHookPath, 'utf8')

assert.match(unifiedListTemplateSource, /import TableMultiFilter from '@\/components\/TableMultiFilter\/index\.vue'/, '标准列表模板必须导入多维度筛选组件。')
assert.match(unifiedListTemplateSource, /showMultiFilter/, '标准列表模板必须提供多维度筛选开关。')
assert.match(unifiedListTemplateSource, /multiFilterDefinitions/, '标准列表模板必须接收多维度筛选定义。')
assert.match(unifiedListTemplateSource, /multiFilterState/, '标准列表模板必须接收多维度筛选状态。')
assert.match(unifiedListTemplateSource, /<TableMultiFilter[\s\S]*:filter-definitions="multiFilterDefinitions"/, '标准列表模板必须把筛选定义传入多维度筛选组件。')
assert.match(unifiedListTemplateSource, /@update:state="\$emit\('update:multiFilterState', \$event\)"/, '标准列表模板必须透传多维度筛选状态更新。')
assert.match(unifiedListTemplateSource, /@query="\$emit\('multi-filter-query'\)"/, '标准列表模板必须透传多维度查询事件。')
assert.match(unifiedListTemplateSource, /@reset="\$emit\('multi-filter-reset'\)"/, '标准列表模板必须透传多维度重置事件。')
assert.match(unifiedListTemplateSource, /@remove="\$emit\('multi-filter-remove', \$event\)"/, '标准列表模板必须透传单项筛选清除事件。')

assert.match(multiFilterComponentSource, /name:\s*'TableMultiFilter'/, '多维度筛选组件必须声明稳定组件名。')
assert.match(multiFilterComponentSource, /<el-popover[\s\S]*更多筛选/, '多维度筛选组件必须提供更多筛选入口。')
assert.match(multiFilterComponentSource, /table-multi-filter__chips/, '多维度筛选组件必须显示已选条件标签。')
assert.match(multiFilterComponentSource, /clearAllConditions/, '多维度筛选组件必须支持一键清空筛选。')
assert.match(multiFilterComponentSource, /removeCondition/, '多维度筛选组件必须支持清除单个筛选条件。')
assert.doesNotMatch(multiFilterComponentSource, /localStorage|sessionStorage/, '多维度筛选组件不得使用本地存储兜底。')

assert.match(multiFilterFieldSource, /type === 'multiSelect'/, '多维度筛选字段必须支持多选下拉。')
assert.match(multiFilterFieldSource, /type === 'dateRange'/, '多维度筛选字段必须支持日期范围。')
assert.match(multiFilterFieldSource, /type === 'numberRange'/, '多维度筛选字段必须支持数字范围。')
assert.match(multiFilterFieldSource, /type === 'autocomplete'/, '多维度筛选字段必须支持自动补全。')
assert.match(multiFilterFieldSource, /updateRangeValue/, '多维度筛选字段必须独立更新范围起止值。')

assert.match(multiFilterHookSource, /export type ListMultiFilterFieldType = 'text' \| 'select' \| 'multiSelect' \| 'dateRange' \| 'autocomplete' \| 'numberRange'/, '多维度筛选字段类型必须覆盖文本、单选、多选、日期范围、自动补全和数字范围。')
assert.match(multiFilterHookSource, /export interface ListMultiFilterDefinition/, '多维度筛选 hook 必须导出筛选定义类型。')
assert.match(multiFilterHookSource, /export interface ListMultiFilterCondition/, '多维度筛选 hook 必须导出条件类型。')
assert.match(multiFilterHookSource, /conditions:\s*ListMultiFilterCondition\[\]/, '多维度筛选状态必须使用条件数组。')
assert.match(multiFilterHookSource, /queryParamKeys\?: \[string, string\]/, '多维度筛选定义必须支持范围字段映射到正式 query 起止参数。')
assert.match(multiFilterHookSource, /queryParams\.pageNo = 1/, '多维度筛选查询和重置必须回到第一页。')
assert.match(multiFilterHookSource, /delete queryParamTarget\.multiFilters/, '多维度筛选必须清理旧 multiFilters 参数。')
assert.match(multiFilterHookSource, /unmappedConditions/, '没有正式 queryParamKey 的条件必须进入显式 multiFilters，不得静默丢失。')
assert.doesNotMatch(multiFilterHookSource, /localStorage|sessionStorage/, '多维度筛选 hook 不得使用本地存储兜底。')
assert.doesNotMatch(multiFilterHookSource, /catch\s*\(/, '多维度筛选 hook 不得吞异常或降级。')

console.log('PASS: unified list template multi-filter static contract')
