CREATE TABLE IF NOT EXISTS "mdm_enterprise" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "enterprise_code" varchar(64) NOT NULL,
    "name" varchar(255) NOT NULL,
    "type" varchar(32) NOT NULL,
    "status" varchar(32) NOT NULL,
    "revision" int NOT NULL DEFAULT 1,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_mdm_enterprise_tenant_code" UNIQUE ("tenant_id", "enterprise_code")
);

CREATE INDEX IF NOT EXISTS "idx_mdm_enterprise_tenant_type_status"
    ON "mdm_enterprise" ("tenant_id", "type", "status");

CREATE TABLE IF NOT EXISTS "mdm_user_company_scope" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "company_id" bigint NOT NULL,
    "status" varchar(32) NOT NULL,
    "revision" int NOT NULL DEFAULT 1,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_mdm_user_company_scope_tenant_user_company"
        UNIQUE ("tenant_id", "user_id", "company_id")
);

CREATE INDEX IF NOT EXISTS "idx_mdm_user_company_scope_tenant_company_status"
    ON "mdm_user_company_scope" ("tenant_id", "company_id", "status");

CREATE TABLE IF NOT EXISTS "mdm_role_company_scope" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "role_id" bigint NOT NULL,
    "company_id" bigint NOT NULL,
    "status" varchar(32) NOT NULL,
    "revision" int NOT NULL DEFAULT 1,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_mdm_role_company_scope_tenant_role_company"
        UNIQUE ("tenant_id", "role_id", "company_id")
);

CREATE INDEX IF NOT EXISTS "idx_mdm_role_company_scope_tenant_company_status"
    ON "mdm_role_company_scope" ("tenant_id", "company_id", "status");
