package cn.iocoder.yudao.module.dcc.signature.service.review;

public enum SignatureGovernanceReviewBlockerCode {

    REVIEW_OWNER_MISSING,
    PERIOD_RULE_MISSING,
    DATA_SOURCE_MISSING,
    DATA_SOURCE_PERMISSION_MISSING,
    SAMPLE_PROJECTION_MISSING,
    REVIEW_SIGNATURE_STRATEGY_MISSING,
    SNAPSHOT_MISSING,
    REVIEW_SIGNATURE_MISSING,
    REQUIRED_REMEDIATION_MISSING,
    OPEN_REMEDIATION,
    OVERDUE_REMEDIATION,
    PENDING_REMEDIATION_REVIEW
}
