package cn.iocoder.yudao.module.dcc.signature.core;

public enum SignatureGovernanceBlockerCode {

    OWNER_MISSING,
    OBJECT_LOCK_MISSING,
    VERSIONING_MISSING,
    DEFAULT_RETENTION_MISSING,
    RECOVERY_RUNTIME_MISSING,
    SAMPLE_DCC_SIGNATURE_MISSING,
    SAMPLE_EDHR_ARCHIVE_MISSING,
    QUALITY_APPROVAL_MISSING,
    POLICY_SOURCE_MISSING,
    MODULE_ADAPTER_MISSING,
    REVIEW_SIGNATURE_STRATEGY_MISSING,
    TEST_TENANT_MISSING
}
