CREATE TABLE IF NOT EXISTS `dcc_file_directory` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `sort` INT NOT NULL DEFAULT 0,
  `remark` VARCHAR(255) NULL,
  `access_rule_manually_bound` TINYINT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_directory_access_rule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `directory_id` BIGINT NOT NULL,
  `subject_type` VARCHAR(32) NOT NULL,
  `subject_id` BIGINT NOT NULL,
  `can_query` TINYINT NOT NULL DEFAULT 0,
  `can_preview` TINYINT NOT NULL DEFAULT 0,
  `can_download` TINYINT NOT NULL DEFAULT 0,
  `active` TINYINT NOT NULL DEFAULT 1,
  `change_reason` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_file_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `parent_id` BIGINT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `sort` INT NOT NULL DEFAULT 0,
  `source` VARCHAR(32) NOT NULL,
  `remark` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `lifecycle_stage` VARCHAR(32) NOT NULL,
  `file_type_taxonomy_id` BIGINT NULL,
  `distribution_required` TINYINT NOT NULL DEFAULT 0,
  `training_required` TINYINT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_file_category_tenant_code` UNIQUE (`tenant_id`, `code`),
  KEY `idx_dcc_file_category_taxonomy` (`tenant_id`, `file_type_taxonomy_id`, `deleted`)
);

CREATE TABLE IF NOT EXISTS `dcc_file_category_match_rule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT NOT NULL,
  `match_text` VARCHAR(255) NOT NULL,
  `match_type` VARCHAR(32) NOT NULL DEFAULT 'CONTAINS',
  `weight` INT NOT NULL DEFAULT 0,
  `active` TINYINT NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_file_category_match_rule_unique` (`tenant_id`, `category_id`, `match_text`, `match_type`, `deleted`),
  KEY `idx_dcc_file_category_match_rule_category` (`tenant_id`, `category_id`, `active`, `deleted`)
);

CREATE TABLE IF NOT EXISTS `dcc_file_type_taxonomy` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT NOT NULL DEFAULT 0,
  `level_no` TINYINT NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `sort` INT NOT NULL DEFAULT 0,
  `remark` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_file_type_taxonomy_tenant_code_deleted` UNIQUE (`tenant_id`, `code`, `deleted`),
  CONSTRAINT `uk_dcc_file_type_taxonomy_sibling_name_deleted` UNIQUE (`tenant_id`, `parent_id`, `name`, `deleted`),
  KEY `idx_dcc_file_type_taxonomy_parent` (`tenant_id`, `parent_id`, `deleted`)
);

CREATE TABLE IF NOT EXISTS `dcc_file_category_permission_rule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT NOT NULL,
  `action_type` VARCHAR(32) NOT NULL,
  `subject_type` VARCHAR(32) NOT NULL,
  `subject_id` BIGINT NOT NULL,
  `scope_type` VARCHAR(32) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_category_view_matrix_rule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT NOT NULL,
  `excel_file_name` VARCHAR(255) NULL,
  `excel_row_no` INT NULL,
  `excel_column_letter` VARCHAR(16) NULL,
  `subject_label` VARCHAR(255) NULL,
  `subject_top_header` VARCHAR(128) NULL,
  `subject_sub_header` VARCHAR(128) NULL,
  `marker` VARCHAR(8) NULL,
  `scope_type` VARCHAR(32) NOT NULL,
  `subject_type` VARCHAR(32) NOT NULL,
  `subject_id` BIGINT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_file_category_distribution_rule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT NOT NULL,
  `department_id` BIGINT NOT NULL,
  `distribution_medium` VARCHAR(32) NOT NULL DEFAULT 'PUBLIC_FOLDER',
  `active` TINYINT NOT NULL DEFAULT 1,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_category_distribution_department` UNIQUE (`category_id`, `department_id`)
);

CREATE TABLE IF NOT EXISTS `dcc_file_category_training_rule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT NOT NULL,
  `department_id` BIGINT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_admin_full_config_managed_scope` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_codes_json` LONGTEXT NOT NULL,
  `directory_paths_json` LONGTEXT NOT NULL,
  `approval_position_codes_json` LONGTEXT NOT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_admin_full_config_scope_tenant` UNIQUE (`tenant_id`)
);

CREATE TABLE IF NOT EXISTS `dcc_category_directory_binding` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT NOT NULL,
  `directory_id` BIGINT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_category_directory_binding` UNIQUE (`category_id`, `directory_id`)
);

CREATE TABLE IF NOT EXISTS `dcc_approval_position` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `source` VARCHAR(32) NOT NULL,
  `remark` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_approval_position_tenant_code` UNIQUE (`tenant_id`, `code`)
);

CREATE TABLE IF NOT EXISTS `dcc_position_assignment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `position_id` BIGINT NOT NULL,
  `assignment_type` VARCHAR(32) NOT NULL,
  `system_post_id` BIGINT NULL,
  `user_id` BIGINT NULL,
  `role_id` BIGINT NULL,
  `post_id` BIGINT NULL,
  `department_id` BIGINT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `change_reason` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_category_approval_route` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT NOT NULL,
  `version_no` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `effective_time` DATETIME NULL,
  `remark` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_category_approval_route_node` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `route_id` BIGINT NOT NULL,
  `stage_no` INT NOT NULL,
  `stage_code` VARCHAR(64) NULL,
  `stage_name` VARCHAR(128) NOT NULL,
  `stage_order` INT NULL,
  `candidate_source_type` VARCHAR(32) NOT NULL,
  `candidate_source_id` BIGINT NULL,
  `candidate_source_ids` VARCHAR(1000) NULL,
  `approve_method` VARCHAR(32) NOT NULL,
  `approve_ratio` INT NULL,
  `require_all_approvals` TINYINT NOT NULL DEFAULT 0,
  `required` TINYINT NOT NULL DEFAULT 1,
  `sort` INT NOT NULL DEFAULT 0,
  `stage_type` VARCHAR(32) NULL,
  `subject_label` VARCHAR(255) NULL,
  `marker` VARCHAR(32) NULL,
  `subject_type` VARCHAR(32) NULL,
  `subject_id` BIGINT NULL,
  `subject_name` VARCHAR(255) NULL,
  `subject_department_path` VARCHAR(500) NULL,
  `rule_remark` VARCHAR(255) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_master` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_id` BIGINT NOT NULL,
  `directory_id` BIGINT NULL,
  `file_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `file_number` VARCHAR(64) NOT NULL,
  `current_active_controlled_file_id` BIGINT NULL,
  `status` VARCHAR(32) NOT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_controlled_file_master_chain` UNIQUE (`category_id`, `directory_id`, `file_name`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `master_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  `directory_id` BIGINT NOT NULL,
  `source_file_id` BIGINT NOT NULL,
  `original_file_id` BIGINT NOT NULL,
  `drawing_pdf_file_id` BIGINT NULL,
  `training_record_file_id` BIGINT NULL,
  `published_file_id` BIGINT NULL,
  `stamped_file_id` BIGINT NULL,
  `file_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `title` VARCHAR(256) NOT NULL,
  `file_number` VARCHAR(64) NOT NULL,
  `product_master_id` BIGINT NULL,
  `product_code` VARCHAR(255) NULL,
  `product_name` VARCHAR(255) NULL,
  `dcc_project_code_id` BIGINT NULL,
  `project_code_recognition_type` VARCHAR(32) NULL,
  `project_code_recognition_text` VARCHAR(255) NULL,
  `project_code_recognized_by` BIGINT NULL,
  `project_code_recognized_time` DATETIME NULL,
  `file_type_taxonomy_id` BIGINT NULL,
  `file_type_level1` VARCHAR(64) NULL,
  `file_type_level2` VARCHAR(128) NULL,
  `file_type_level3` VARCHAR(128) NULL,
  `file_type_level4` VARCHAR(128) NULL,
  `file_type_level5` VARCHAR(128) NULL,
  `need_training` BIT NOT NULL DEFAULT 0,
  `process_type` VARCHAR(32) NOT NULL DEFAULT 'CONTROLLED_FILE',
  `change_type` VARCHAR(32) NOT NULL DEFAULT 'NEW',
  `version_no` VARCHAR(64) NOT NULL,
  `effective_date` DATE NULL,
  `remark` VARCHAR(1024) NULL,
  `status` VARCHAR(64) NOT NULL,
  `submitter_id` BIGINT NOT NULL,
  `requester_id` BIGINT NOT NULL,
  `process_instance_id` VARCHAR(64) NULL,
  `process_definition_key` VARCHAR(128) NULL,
  `submitted_time` DATETIME NULL,
  `approved_time` DATETIME NULL,
  `published_time` DATETIME NULL,
  `rejected_time` DATETIME NULL,
  `stamped_time` DATETIME NULL,
  `obsoleted_by` BIGINT NULL,
  `obsoleted_time` DATETIME NULL,
  `obsolete_reason` VARCHAR(255) NULL,
  `superseded_by_file_id` BIGINT NULL,
  `reject_reason` VARCHAR(255) NULL,
  `finalization_error` VARCHAR(500) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_dcc_controlled_file_project_code` (`tenant_id`, `dcc_project_code_id`),
  KEY `idx_dcc_controlled_file_taxonomy` (`tenant_id`, `file_type_taxonomy_id`, `deleted`),
  KEY `idx_dcc_controlled_file_type_level` (`tenant_id`, `file_type_level1`, `file_type_level2`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_route_snapshot` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `controlled_file_id` BIGINT NOT NULL,
  `route_version_no` INT NOT NULL,
  `stage_no` INT NOT NULL,
  `stage_code` VARCHAR(64) NULL,
  `stage_name` VARCHAR(128) NULL,
  `stage_order` INT NULL,
  `candidate_source_type` VARCHAR(32) NOT NULL,
  `candidate_source_id` BIGINT NULL,
  `candidate_source_ids` VARCHAR(1000) NULL,
  `resolved_user_ids` VARCHAR(1000) NULL,
  `approve_method` VARCHAR(32) NOT NULL,
  `approve_ratio` INT NULL,
  `require_all_approvals` TINYINT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_external_file_review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `controlled_file_id` BIGINT NOT NULL,
  `external_source` VARCHAR(128) NOT NULL,
  `external_owner` VARCHAR(128) NOT NULL,
  `review_reason` VARCHAR(500) NOT NULL,
  `participant_user_ids` VARCHAR(500) NOT NULL,
  `review_conclusion` VARCHAR(64) NULL,
  `conclusion_comment` VARCHAR(1000) NULL,
  `output_file_id` BIGINT NULL,
  `closed_time` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_signature` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `controlled_file_id` BIGINT NOT NULL,
  `revision_id` BIGINT NULL,
  `version_no` VARCHAR(64) NULL,
  `task_id` VARCHAR(64) NOT NULL,
  `actor_id` BIGINT NOT NULL,
  `actor_username_snapshot` VARCHAR(64) NULL,
  `actor_nickname_snapshot` VARCHAR(64) NULL,
  `actor_dept_id_snapshot` BIGINT NULL,
  `actor_dept_name_snapshot` VARCHAR(128) NULL,
  `actor_post_names_snapshot` VARCHAR(512) NULL,
  `actor_role_names_snapshot` VARCHAR(512) NULL,
  `signature_purpose` VARCHAR(128) NULL,
  `authorization_basis` VARCHAR(500) NULL,
  `authentication_method` VARCHAR(64) NULL,
  `record_version_snapshot` VARCHAR(64) NULL,
  `record_hash_snapshot` VARCHAR(128) NULL,
  `client_ip_snapshot` VARCHAR(64) NULL,
  `user_agent_snapshot` VARCHAR(512) NULL,
  `snapshot_status` VARCHAR(32) NULL,
  `action_type` VARCHAR(32) NOT NULL,
  `meaning_code` VARCHAR(64) NULL,
  `meaning_label` VARCHAR(128) NULL,
  `signature_mode` VARCHAR(32) NOT NULL,
  `password_verified` TINYINT NOT NULL DEFAULT 0,
  `comment` VARCHAR(500) NULL,
  `signed_at` DATETIME NULL,
  `source_file_id` BIGINT NULL,
  `source_file_hash` VARCHAR(128) NULL,
  `source_file_hash_algorithm` VARCHAR(32) NULL,
  `source_file_hash_status` VARCHAR(32) NULL,
  `controlled_copy_file_id` BIGINT NULL,
  `controlled_copy_hash` VARCHAR(128) NULL,
  `controlled_copy_hash_algorithm` VARCHAR(32) NULL,
  `controlled_copy_hash_status` VARCHAR(32) NULL,
  `signature_image_id` BIGINT NULL,
  `signature_image_version_no` INT NULL,
  `signature_image_file_id` BIGINT NULL,
  `signature_image_file_url` VARCHAR(512) NULL,
  `signature_image_sha256` VARCHAR(128) NULL,
  `signature_image_content_type` VARCHAR(128) NULL,
  `signature_image_file_size` BIGINT NULL,
  `signature_image_status_snapshot` VARCHAR(32) NULL,
  `signature_image_verified_status` VARCHAR(32) NULL,
  `evidence_payload_version` VARCHAR(32) NULL,
  `evidence_key_version` VARCHAR(64) NULL,
  `evidence_hash` VARCHAR(128) NULL,
  `evidence_hash_algorithm` VARCHAR(32) NULL,
  `evidence_status` VARCHAR(32) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_electronic_signature_failure_audit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `target_user_id` BIGINT NOT NULL,
  `controlled_file_id` BIGINT NULL,
  `revision_id` BIGINT NULL,
  `task_id` VARCHAR(128) NOT NULL,
  `action_type` VARCHAR(64) NOT NULL,
  `meaning_code` VARCHAR(64) NULL,
  `failure_type` VARCHAR(64) NOT NULL,
  `failure_message` VARCHAR(1000) NULL,
  `failed_at` DATETIME NOT NULL,
  `remote_ip` VARCHAR(64) NULL,
  `user_agent` VARCHAR(512) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_approval_print_template` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `template_file_id` BIGINT NOT NULL,
  `template_file_name` VARCHAR(255) NOT NULL,
  `template_file_content_type` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `remark` VARCHAR(500) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_electronic_signature_image` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `version_no` INT NOT NULL,
  `file_id` BIGINT NOT NULL,
  `file_url` VARCHAR(512) NOT NULL,
  `storage_path` VARCHAR(512) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `content_type` VARCHAR(128) NOT NULL,
  `file_size` BIGINT NOT NULL,
  `sha256` VARCHAR(128) NOT NULL,
  `image_status` VARCHAR(32) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `uploaded_by` BIGINT NOT NULL,
  `uploaded_at` DATETIME NOT NULL,
  `enabled_at` DATETIME NULL,
  `disabled_at` DATETIME NULL,
  `disable_reason` VARCHAR(500) NULL,
  `referenced_count` INT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_electronic_signature_authorization` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `electronic_signature_enabled` TINYINT NOT NULL DEFAULT 1,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_distribution` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `controlled_file_id` BIGINT NOT NULL,
  `department_id` BIGINT NOT NULL,
  `distribution_medium` VARCHAR(32) NOT NULL DEFAULT 'PUBLIC_FOLDER',
  `status` VARCHAR(32) NOT NULL,
  `acknowledged_by` BIGINT NULL,
  `acknowledged_at` DATETIME NULL,
  `recovered_by` BIGINT NULL,
  `recovered_at` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_distribution_recipient` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `distribution_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `message_job_id` BIGINT NULL,
  `read_at` DATETIME NULL,
  `acknowledged_at` DATETIME NULL,
  `ack_comment` VARCHAR(1000) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_training` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `controlled_file_id` BIGINT NOT NULL,
  `department_id` BIGINT NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_training_assignment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `training_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `message_job_id` BIGINT NULL,
  `status` VARCHAR(32) NOT NULL,
  `acknowledged_at` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_training_progress` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `controlled_file_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `required_view_seconds` INT NOT NULL DEFAULT 600,
  `accumulated_view_seconds` INT NOT NULL DEFAULT 0,
  `first_viewed_at` DATETIME NULL,
  `last_viewed_at` DATETIME NULL,
  `acknowledged_at` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_training_view_session` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `training_progress_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `client_session_id` VARCHAR(64) NOT NULL,
  `started_at` DATETIME NOT NULL,
  `last_heartbeat_at` DATETIME NULL,
  `ended_at` DATETIME NULL,
  `accumulated_seconds` INT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_message_job` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `business_type` VARCHAR(32) NOT NULL,
  `business_id` BIGINT NOT NULL,
  `template_code` VARCHAR(64) NOT NULL,
  `recipient_user_id` BIGINT NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `error_message` VARCHAR(500) NULL,
  `sent_at` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_nas_transfer_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `operator_user_id` BIGINT NOT NULL,
  `template_category_id` BIGINT NOT NULL,
  `dcc_project_code_id` BIGINT NULL,
  `product_master_id` BIGINT NULL,
  `effective_date` DATE NOT NULL,
  `selected_nas_paths_json` LONGTEXT NOT NULL,
  `source_type` VARCHAR(32) NOT NULL DEFAULT 'NAS',
  `expected_file_count` BIGINT NOT NULL DEFAULT 0,
  `expected_total_bytes` BIGINT NOT NULL DEFAULT 0,
  `uploaded_file_count` BIGINT NOT NULL DEFAULT 0,
  `uploaded_total_bytes` BIGINT NOT NULL DEFAULT 0,
  `upload_completed_at` DATETIME NULL,
  `status` VARCHAR(32) NOT NULL,
  `next_check_at` DATETIME NULL,
  `last_run_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `last_failure_message` VARCHAR(512) NULL,
  `failure_report_path` VARCHAR(512) NULL,
  `failure_report_generated_at` VARCHAR(64) NULL,
  `failure_report_error` VARCHAR(512) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_nas_transfer_task_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `parent_item_id` BIGINT NULL,
  `item_type` VARCHAR(16) NOT NULL,
  `nas_path` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `item_name` VARCHAR(255) NOT NULL,
  `source_file_id` BIGINT NULL,
  `status` VARCHAR(32) NOT NULL,
  `attempt_count` INT NOT NULL DEFAULT 0,
  `failure_stage` VARCHAR(32) NULL,
  `last_error` VARCHAR(512) NULL,
  `resolved_directory_id` BIGINT NULL,
  `resolved_category_id` BIGINT NULL,
  `directory_outcome` VARCHAR(16) NULL,
  `category_outcome` VARCHAR(16) NULL,
  `preview_download_only` BIT NOT NULL DEFAULT 0,
  `last_attempt_at` DATETIME NULL,
  `completed_at` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_local_folder_upload_chunk` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT NOT NULL,
  `relative_path` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `file_size` BIGINT NOT NULL,
  `chunk_index` INT NOT NULL,
  `total_chunks` INT NOT NULL,
  `chunk_size` BIGINT NOT NULL,
  `chunk_sha256` VARCHAR(64) NOT NULL,
  `chunk_temp_path` VARCHAR(1024) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'COMPLETED',
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_obsolete_audit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `controlled_file_id` BIGINT NOT NULL,
  `operator_id` BIGINT NOT NULL,
  `obsolete_reason` VARCHAR(255) NOT NULL,
  `status_before` VARCHAR(32) NOT NULL,
  `status_after` VARCHAR(32) NOT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_stamp` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `controlled_file_id` BIGINT NOT NULL,
  `stamp_type` VARCHAR(32) NOT NULL,
  `template_id` VARCHAR(64) NOT NULL,
  `renderer_type` VARCHAR(32) NOT NULL,
  `stamp_text` VARCHAR(255) NULL,
  `output_format` VARCHAR(32) NOT NULL,
  `page_positions_json` VARCHAR(2000) NULL,
  `source_file_id` BIGINT NOT NULL,
  `output_file_id` BIGINT NULL,
  `status` VARCHAR(32) NOT NULL,
  `error_message` VARCHAR(500) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_access_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `controlled_file_id` BIGINT NULL,
  `access_event_id` BIGINT NULL,
  `access_event_code` VARCHAR(64) NULL,
  `watermark_trace_code` VARCHAR(64) NULL,
  `file_version_no` VARCHAR(64) NULL,
  `user_id` BIGINT NOT NULL,
  `action_type` VARCHAR(32) NOT NULL,
  `purpose` VARCHAR(64) NULL,
  `result` VARCHAR(32) NOT NULL,
  `failure_code` VARCHAR(64) NULL,
  `reason` VARCHAR(255) NULL,
  `source_ip` VARCHAR(64) NULL,
  `request_id` VARCHAR(128) NULL,
  `user_agent` VARCHAR(512) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_access_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `access_event_code` VARCHAR(64) NOT NULL,
  `controlled_file_id` BIGINT NOT NULL,
  `file_version_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `access_type` VARCHAR(32) NOT NULL,
  `purpose` VARCHAR(64) NOT NULL,
  `result` VARCHAR(32) NOT NULL,
  `failure_code` VARCHAR(64) NULL,
  `failure_reason` VARCHAR(500) NULL,
  `source_ip` VARCHAR(64) NULL,
  `user_agent` VARCHAR(512) NULL,
  `request_id` VARCHAR(128) NULL,
  `occurred_at` DATETIME NOT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_watermark_trace` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `trace_code` VARCHAR(64) NOT NULL,
  `access_event_id` BIGINT NOT NULL,
  `access_event_code` VARCHAR(64) NOT NULL,
  `controlled_file_id` BIGINT NOT NULL,
  `file_number` VARCHAR(64) NOT NULL,
  `file_version_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `user_identifier` VARCHAR(64) NULL,
  `user_display_name` VARCHAR(128) NULL,
  `dept_id` BIGINT NULL,
  `dept_name` VARCHAR(128) NULL,
  `tenant_name` VARCHAR(128) NULL,
  `privacy_mode` VARCHAR(32) NOT NULL,
  `watermark_payload_json` LONGTEXT NOT NULL,
  `issued_at` DATETIME NOT NULL,
  `expires_at` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_upload_policy` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `policy_code` VARCHAR(64) NOT NULL,
  `scope_type` VARCHAR(32) NOT NULL,
  `category_id` BIGINT NULL,
  `purpose` VARCHAR(64) NULL,
  `max_bytes` BIGINT NOT NULL,
  `enabled` BIT NOT NULL,
  `priority` INT NOT NULL,
  `policy_version` VARCHAR(64) NOT NULL,
  `effective_from` DATETIME NULL,
  `effective_to` DATETIME NULL,
  `change_reason` VARCHAR(500) NOT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_temporary_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `upload_ticket` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(128) NOT NULL,
  `purpose` VARCHAR(64) NOT NULL,
  `uploader_id` BIGINT NOT NULL,
  `original_file_name` VARCHAR(255) NOT NULL,
  `content_type` VARCHAR(255) NULL,
  `file_size` BIGINT NOT NULL,
  `file_sha256` VARCHAR(128) NOT NULL,
  `storage_file_id` BIGINT NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `bound_controlled_file_id` BIGINT NULL,
  `bound_time` DATETIME NULL,
  `cleanup_status` VARCHAR(32) NOT NULL,
  `cleanup_reason` VARCHAR(500) NULL,
  `cleanup_time` DATETIME NULL,
  `request_id` VARCHAR(128) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_download_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `download_request_id` VARCHAR(64) NOT NULL,
  `access_event_id` BIGINT NOT NULL,
  `access_event_code` VARCHAR(64) NOT NULL,
  `controlled_file_id` BIGINT NOT NULL,
  `file_version_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `policy_version` VARCHAR(64) NOT NULL,
  `encryption_status` VARCHAR(32) NOT NULL,
  `encryption_policy_version` VARCHAR(64) NULL,
  `artifact_id` VARCHAR(128) NULL,
  `cipher_file_ref` VARCHAR(255) NULL,
  `plain_sha256` VARCHAR(128) NULL,
  `cipher_sha256` VARCHAR(128) NULL,
  `failure_code` VARCHAR(64) NULL,
  `failure_reason` VARCHAR(500) NULL,
  `requested_at` DATETIME NOT NULL,
  `encrypted_at` DATETIME NULL,
  `returned_at` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_protection_download_request` (`tenant_id`, `download_request_id`)
);

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `transfer_task_id` bigint DEFAULT NULL,
  `snapshot_key` char(64) NOT NULL,
  `server` varchar(255) NOT NULL,
  `share` varchar(255) NOT NULL,
  `root_paths_json` longtext NOT NULL,
  `status` varchar(32) NOT NULL,
  `normalization_version` varchar(32) NOT NULL,
  `total_directory_count` bigint NOT NULL DEFAULT 0,
  `snapshotted_directory_count` bigint NOT NULL DEFAULT 0,
  `failed_directory_count` bigint NOT NULL DEFAULT 0,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `failure_code` varchar(64) DEFAULT NULL,
  `failure_message` varchar(1024) DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_nas_acl_snapshot_key` UNIQUE (`tenant_id`, `snapshot_key`)
);

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_directory_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `snapshot_id` bigint NOT NULL,
  `transfer_task_id` bigint DEFAULT NULL,
  `transfer_task_item_id` bigint DEFAULT NULL,
  `dcc_directory_id` bigint DEFAULT NULL,
  `parent_snapshot_id` bigint DEFAULT NULL,
  `depth` int NOT NULL DEFAULT 0,
  `nas_path` varchar(1024) NOT NULL,
  `path_hash` char(64) NOT NULL,
  `item_name` varchar(255) NOT NULL,
  `descriptor_id` bigint DEFAULT NULL,
  `collect_status` varchar(32) NOT NULL,
  `failure_code` varchar(64) DEFAULT NULL,
  `failure_message` varchar(1024) DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_nas_acl_dir_snapshot_path` UNIQUE (`snapshot_id`, `path_hash`)
);

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_descriptor` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `descriptor_hash` char(64) NOT NULL,
  `owner_sid` varchar(184) DEFAULT NULL,
  `group_sid` varchar(184) DEFAULT NULL,
  `control_flags` varchar(128) DEFAULT NULL,
  `dacl_present` TINYINT NOT NULL DEFAULT 0,
  `dacl_protected` TINYINT NOT NULL DEFAULT 0,
  `sacl_present` TINYINT NOT NULL DEFAULT 0,
  `raw_descriptor_sha256` char(64) DEFAULT NULL,
  `raw_descriptor_blob` BLOB DEFAULT NULL,
  `normalized_descriptor_json` longtext NOT NULL,
  `capture_capability` varchar(32) NOT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_nas_acl_descriptor_hash` UNIQUE (`tenant_id`, `descriptor_hash`)
);

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_ace` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `descriptor_id` bigint NOT NULL,
  `ace_index` int NOT NULL,
  `ace_hash` char(64) NOT NULL,
  `ace_type` varchar(32) NOT NULL,
  `ace_flags` int DEFAULT NULL,
  `access_mask` bigint NOT NULL,
  `trustee_sid` varchar(184) NOT NULL,
  `trustee_sid_hash` char(64) NOT NULL,
  `inherited` TINYINT NOT NULL DEFAULT 0,
  `inheritance_flags` varchar(128) DEFAULT NULL,
  `propagation_flags` varchar(128) DEFAULT NULL,
  `object_type_guid` varchar(64) DEFAULT NULL,
  `inherited_object_type_guid` varchar(64) DEFAULT NULL,
  `raw_ace_json` longtext NOT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_nas_acl_ace_order` UNIQUE (`descriptor_id`, `ace_index`)
);

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_identity_mapping` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sid` varchar(184) NOT NULL,
  `sid_hash` char(64) NOT NULL,
  `domain_name` varchar(128) DEFAULT NULL,
  `account_name` varchar(128) DEFAULT NULL,
  `account_display_name` varchar(255) DEFAULT NULL,
  `account_type` varchar(32) NOT NULL,
  `mapping_status` varchar(32) NOT NULL,
  `dcc_subject_type` varchar(32) DEFAULT NULL,
  `dcc_subject_id` bigint DEFAULT NULL,
  `mapping_method` varchar(32) DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `mapped_by_user_id` bigint DEFAULT NULL,
  `block_reason` varchar(512) DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_nas_acl_identity_sid` UNIQUE (`tenant_id`, `sid_hash`)
);

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_restore_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `snapshot_id` bigint NOT NULL,
  `transfer_task_id` bigint DEFAULT NULL,
  `plan_key` char(64) NOT NULL,
  `target_model` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `semantic_policy_version` varchar(64) DEFAULT NULL,
  `identity_mapping_version` varchar(64) DEFAULT NULL,
  `validation_summary_json` longtext DEFAULT NULL,
  `created_by_user_id` bigint NOT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `failure_code` varchar(64) DEFAULT NULL,
  `failure_message` varchar(1024) DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_nas_acl_restore_plan_key` UNIQUE (`tenant_id`, `plan_key`)
);

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_restore_plan_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `directory_snapshot_id` bigint NOT NULL,
  `transfer_task_item_id` bigint DEFAULT NULL,
  `dcc_directory_id` bigint DEFAULT NULL,
  `dcc_category_id` bigint DEFAULT NULL,
  `source_descriptor_id` bigint NOT NULL,
  `planned_operations_hash` char(64) DEFAULT NULL,
  `planned_operations_json` longtext DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `block_reason` varchar(1024) DEFAULT NULL,
  `expected_after_hash` varchar(128) DEFAULT NULL,
  `actual_after_hash` varchar(128) DEFAULT NULL,
  `verified_at` datetime DEFAULT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_nas_acl_restore_item_dir` UNIQUE (`plan_id`, `directory_snapshot_id`)
);

CREATE TABLE IF NOT EXISTS `dcc_nas_acl_restore_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `plan_id` bigint NOT NULL,
  `plan_item_id` bigint NOT NULL,
  `attempt_no` int NOT NULL,
  `action_type` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `before_hash` varchar(128) DEFAULT NULL,
  `expected_after_hash` varchar(128) DEFAULT NULL,
  `actual_after_hash` varchar(128) DEFAULT NULL,
  `request_payload_hash` char(64) DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` varchar(1024) DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `operator_user_id` bigint NOT NULL,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_nas_acl_restore_log_attempt` UNIQUE (`plan_item_id`, `attempt_no`, `action_type`)
);

CREATE TABLE IF NOT EXISTS `dcc_project_code` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `doc_control_no` VARCHAR(64) NULL,
  `project_name` VARCHAR(255) NOT NULL,
  `project_code` VARCHAR(64) NOT NULL DEFAULT '',
  `category` VARCHAR(128) NULL,
  `commissioned_production` VARCHAR(128) NULL,
  `project_leader` VARCHAR(128) NULL,
  `project_engineer` VARCHAR(128) NULL,
  `storage_location` VARCHAR(128) NULL,
  `priority` VARCHAR(64) NULL,
  `status` VARCHAR(32) NOT NULL,
  `last_import_batch_id` BIGINT NULL,
  `associated_file_count` BIGINT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_project_code_tenant_project` UNIQUE (`tenant_id`, `project_name`, `project_code`)
);

CREATE TABLE IF NOT EXISTS `dcc_project_code_alias_mapping` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_code_id` BIGINT NOT NULL,
  `alias_text` VARCHAR(255) NOT NULL,
  `normalized_alias_text` VARCHAR(255) NOT NULL,
  `alias_source` VARCHAR(32) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `active` BIT NOT NULL DEFAULT 1,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `uk_dcc_project_alias_tenant_text` UNIQUE (`tenant_id`, `normalized_alias_text`, `alias_source`, `project_code_id`)
);

CREATE TABLE IF NOT EXISTS `dcc_project_code_import_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(32) NOT NULL,
  `total_count` INT NOT NULL DEFAULT 0,
  `create_count` INT NOT NULL DEFAULT 0,
  `update_count` INT NOT NULL DEFAULT 0,
  `disable_count` INT NOT NULL DEFAULT 0,
  `unchanged_count` INT NOT NULL DEFAULT 0,
  `failure_count` INT NOT NULL DEFAULT 0,
  `confirmed_at` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_project_code_import_row` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT NOT NULL,
  `row_no` INT NOT NULL,
  `doc_control_no` VARCHAR(64) NULL,
  `project_name` VARCHAR(255) NULL,
  `project_code` VARCHAR(64) NOT NULL DEFAULT '',
  `category` VARCHAR(128) NULL,
  `commissioned_production` VARCHAR(128) NULL,
  `project_leader` VARCHAR(128) NULL,
  `project_engineer` VARCHAR(128) NULL,
  `storage_location` VARCHAR(128) NULL,
  `priority` VARCHAR(64) NULL,
  `current_status` VARCHAR(32) NULL,
  `import_action` VARCHAR(32) NOT NULL,
  `failure_reason` VARCHAR(500) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_project_code_assignment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `assignment_no` VARCHAR(64) NOT NULL,
  `project_code_id` BIGINT NOT NULL,
  `scope_mode` VARCHAR(32) NOT NULL,
  `assignee_user_id` BIGINT NOT NULL,
  `assigned_by` BIGINT NOT NULL,
  `assigned_time` DATETIME NOT NULL,
  `expire_time` DATETIME NULL,
  `status` VARCHAR(32) NOT NULL,
  `assignment_reason` VARCHAR(512) NULL,
  `file_count` INT NOT NULL DEFAULT 0,
  `changed_file_count` INT NOT NULL DEFAULT 0,
  `changed_field_count` INT NOT NULL DEFAULT 0,
  `revoked_by` BIGINT NULL,
  `revoked_time` DATETIME NULL,
  `revoke_reason` VARCHAR(512) NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_pc_assignment_no` (`tenant_id`, `assignment_no`, `deleted`)
);

CREATE TABLE IF NOT EXISTS `dcc_project_code_assignment_file` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `assignment_id` BIGINT NOT NULL,
  `project_code_id` BIGINT NOT NULL,
  `controlled_file_id` BIGINT NOT NULL,
  `master_id` BIGINT NULL,
  `file_number_snapshot` VARCHAR(128) NULL,
  `file_name_snapshot` VARCHAR(512) NULL,
  `category_id_snapshot` BIGINT NULL,
  `directory_id_snapshot` BIGINT NULL,
  `initial_file_type_level1` VARCHAR(64) NULL,
  `initial_file_type_level2` VARCHAR(128) NULL,
  `initial_file_type_level3` VARCHAR(128) NULL,
  `initial_file_type_level4` VARCHAR(128) NULL,
  `initial_file_type_level5` VARCHAR(128) NULL,
  `changed` BIT NOT NULL DEFAULT 0,
  `changed_field_count` INT NOT NULL DEFAULT 0,
  `last_changed_time` DATETIME NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_pc_assignment_file` (`tenant_id`, `assignment_id`, `controlled_file_id`, `deleted`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_metadata_change` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `assignment_id` BIGINT NULL,
  `project_code_id` BIGINT NULL,
  `controlled_file_id` BIGINT NOT NULL,
  `master_id` BIGINT NULL,
  `operator_user_id` BIGINT NOT NULL,
  `source` VARCHAR(32) NOT NULL,
  `request_id` VARCHAR(64) NULL,
  `change_reason` VARCHAR(512) NULL,
  `changed_field_count` INT NOT NULL DEFAULT 0,
  `before_snapshot_json` LONGTEXT NULL,
  `after_snapshot_json` LONGTEXT NULL,
  `changed_time` DATETIME NOT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_metadata_change_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `change_id` BIGINT NOT NULL,
  `assignment_id` BIGINT NULL,
  `project_code_id` BIGINT NULL,
  `controlled_file_id` BIGINT NOT NULL,
  `operator_user_id` BIGINT NOT NULL,
  `field_name` VARCHAR(64) NOT NULL,
  `field_label` VARCHAR(64) NOT NULL,
  `old_value_text` VARCHAR(1024) NULL,
  `new_value_text` VARCHAR(1024) NULL,
  `old_value_json` LONGTEXT NULL,
  `new_value_json` LONGTEXT NULL,
  `changed_time` DATETIME NOT NULL,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `creator` VARCHAR(64) NULL,
  `updater` VARCHAR(64) NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_batch_recognition_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `operator_user_id` bigint NOT NULL,
  `recognition_type` varchar(32) NOT NULL DEFAULT 'BASIC_INFO',
  `scope_type` varchar(16) NOT NULL COMMENT 'CURRENT or GLOBAL',
  `recognition_version_snapshot` varchar(64) NOT NULL,
  `directory_id` bigint DEFAULT NULL,
  `directory_path_snapshot` varchar(512) DEFAULT NULL,
  `keyword` varchar(255) DEFAULT NULL,
  `status_filter` varchar(32) DEFAULT NULL,
  `category_id` bigint DEFAULT NULL,
  `overwrite_existing` bit(1) NOT NULL DEFAULT 0,
  `existing_record_policy` varchar(32) NOT NULL DEFAULT 'SKIP_ALL_EXISTING',
  `sync_file_name_title` bit(1) NOT NULL DEFAULT 1,
  `worker_count` int NOT NULL DEFAULT 1,
  `candidate_ids_json` longtext NOT NULL,
  `status` varchar(16) NOT NULL,
  `total_count` bigint NOT NULL DEFAULT 0,
  `processed_count` bigint NOT NULL DEFAULT 0,
  `success_count` bigint NOT NULL DEFAULT 0,
  `failed_count` bigint NOT NULL DEFAULT 0,
  `skipped_existing_count` bigint NOT NULL DEFAULT 0,
  `unclassified_count` bigint NOT NULL DEFAULT 0,
  `ambiguous_count` bigint NOT NULL DEFAULT 0,
  `conflict_count` bigint NOT NULL DEFAULT 0,
  `remaining_count` bigint NOT NULL DEFAULT 0,
  `last_failure_message` varchar(2048) DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  `active_recognition_type` varchar(32) GENERATED ALWAYS AS (
    CASE
      WHEN `deleted` = 0 AND `status` IN ('WAITING', 'RUNNING') THEN `recognition_type`
      ELSE NULL
    END
  ),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_batch_recognition_task_active_type` (`tenant_id`, `active_recognition_type`),
  KEY `idx_dcc_batch_recognition_task_type_status` (`recognition_type`, `status`, `id`),
  KEY `idx_dcc_batch_recognition_task_status` (`status`, `id`),
  KEY `idx_dcc_batch_recognition_task_operator` (`operator_user_id`, `create_time`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_recognition_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `controlled_file_id` bigint NOT NULL,
  `recognition_scope` varchar(32) NOT NULL,
  `recognition_method` varchar(32) NOT NULL,
  `recognition_version` varchar(64) NOT NULL,
  `status` varchar(16) NOT NULL,
  `matched_project_code_id` bigint DEFAULT NULL,
  `matched_project_alias_id` bigint DEFAULT NULL,
  `matched_project_alias_text` varchar(255) DEFAULT NULL,
  `matched_project_alias_source` varchar(32) DEFAULT NULL,
  `recognized_product_code` varchar(255) DEFAULT NULL,
  `recognized_product_name` varchar(255) DEFAULT NULL,
  `match_type` varchar(32) DEFAULT NULL,
  `match_text` varchar(255) DEFAULT NULL,
  `failure_stage` varchar(64) DEFAULT NULL,
  `failure_code` varchar(64) DEFAULT NULL,
  `failure_message` varchar(2048) DEFAULT NULL,
  `file_type_taxonomy_id` bigint DEFAULT NULL,
  `file_type_level1` varchar(64) DEFAULT NULL,
  `file_type_level2` varchar(128) DEFAULT NULL,
  `file_type_level3` varchar(128) DEFAULT NULL,
  `file_type_level4` varchar(128) DEFAULT NULL,
  `file_type_level5` varchar(128) DEFAULT NULL,
  `batch_task_id` bigint DEFAULT NULL,
  `recognized_by` bigint DEFAULT NULL,
  `recognized_time` datetime DEFAULT NULL,
  `source_file_id` bigint DEFAULT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_file_recognition_record_biz`
    (`controlled_file_id`, `recognition_scope`, `recognition_method`, `recognition_version`),
  KEY `idx_dcc_file_recognition_record_batch` (`tenant_id`, `batch_task_id`),
  KEY `idx_dcc_recognition_record_taxonomy` (`tenant_id`, `file_type_taxonomy_id`, `deleted`)
);

CREATE TABLE IF NOT EXISTS `dcc_controlled_file_recognition_claim` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `controlled_file_id` bigint NOT NULL,
  `recognition_scope` varchar(32) NOT NULL,
  `claimed_by` bigint NOT NULL,
  `claim_task_id` bigint DEFAULT NULL,
  `claimed_at` datetime NOT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dcc_file_recognition_claim_scope`
    (`controlled_file_id`, `recognition_scope`)
);
