-- D isolated H2 fixture mirrors the existing system notification schema and its tenant/business key.
CREATE TABLE IF NOT EXISTS system_notify_message (
 id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL, user_type VARCHAR(16) NOT NULL, business_key VARCHAR(255),
 template_id BIGINT NOT NULL, template_code VARCHAR(128) NOT NULL, template_nickname VARCHAR(128) NOT NULL,
 template_content VARCHAR(2048) NOT NULL, template_type INT NOT NULL, template_params VARCHAR(4096) NOT NULL,
 read_status BIT NOT NULL, read_time VARCHAR(64), creator VARCHAR(64) DEFAULT '',
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updater VARCHAR(64) DEFAULT '',
 update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted BIT NOT NULL DEFAULT FALSE,
 tenant_id BIGINT NOT NULL,
 CONSTRAINT uk_dcc_test_platform_business_key UNIQUE(tenant_id,business_key)
);
