-- G49 isolated H2 table definitions from the existing system test schema; no actual DB.

CREATE TABLE IF NOT EXISTS "system_users" (
    "id" bigint not null GENERATED BY DEFAULT AS IDENTITY,
    "username" varchar(30) not null,
    "canonical_username" varchar(64) not null,
    "password" varchar(100) not null default '',
    "password_update_time" timestamp default null,
    "password_credential_status" varchar(32) not null default 'ACTIVE',
    "nickname" varchar(30) not null,
    "remark" varchar(500) default null,
    "dept_id" bigint default null,
    "post_ids" varchar(255) default null,
    "email" varchar(50) default '',
    "mobile" varchar(11) default '',
    "sex" tinyint default '0',
    "avatar" varchar(100) default '',
    "status" tinyint not null default '0',
    "login_failure_count" int not null default 0,
    "login_failure_window_start_time" timestamp default null,
    "login_locked" tinyint not null default 0,
    "login_locked_time" timestamp default null,
    "lifecycle_document_type" varchar(32) default null,
    "lifecycle_document_no" varchar(64) default null,
    "lifecycle_document_time" timestamp default null,
    "lifecycle_effective_time" timestamp default null,
    "lifecycle_deactivated_time" timestamp default null,
    "login_ip" varchar(50) default '',
    "login_date" timestamp default null,
    "creator" varchar(64) default '',
    "create_time" timestamp not null default current_timestamp,
    "updater" varchar(64) default '',
    "update_time" timestamp not null default current_timestamp,
    "deleted" bit not null default false,
    "tenant_id" bigint not null default  '0',
    primary key ("id"),
    unique ("tenant_id", "canonical_username")
) comment '用户信息表';

CREATE TABLE IF NOT EXISTS "system_notify_message" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "user_type" varchar NOT NULL,
    "business_key" varchar(255) DEFAULT NULL,
    "template_id" bigint NOT NULL,
    "template_code" varchar NOT NULL,
    "template_nickname" varchar NOT NULL,
    "template_content" varchar NOT NULL,
    "template_type" int NOT NULL,
    "template_params" varchar NOT NULL,
    "read_status" bit NOT NULL,
    "read_time" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint not null default  '0',
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_system_notify_message_tenant_business_key" UNIQUE ("tenant_id", "business_key")
) COMMENT '站内信消息表';

DELETE FROM system_notify_message;

DELETE FROM system_users;