package cn.iocoder.yudao.module.erp.dal.dataobject.kingdee.event;

import cn.iocoder.yudao.framework.mybatis.core.dataobject.BaseDO;
import com.baomidou.mybatisplus.annotation.KeySequence;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.time.LocalDateTime;

/**
 * ERP Kingdee K3Cloud event callback DO.
 */
@TableName("erp_kingdee_event_callback")
@KeySequence("erp_kingdee_event_callback_seq")
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ErpKingdeeEventCallbackDO extends BaseDO {

    public static final int STATUS_PENDING = 0;

    @TableId
    private Long id;

    /**
     * Idempotency key, for example PRD_MO:evt-001.
     */
    private String eventKey;
    /**
     * Event id generated by the BOS plugin.
     */
    private String eventId;
    /**
     * Kingdee FormId, for example PRD_MO.
     */
    private String sourceFormId;
    /**
     * Kingdee FID.
     */
    private String sourceFid;
    /**
     * Kingdee bill number.
     */
    private String sourceBillNo;
    /**
     * Kingdee operation key, for example Save/Audit/Submit.
     */
    private String operation;
    /**
     * Business event time from Kingdee.
     */
    private LocalDateTime eventTime;
    /**
     * Callback HMAC signature.
     */
    private String signature;
    /**
     * Callback nonce.
     */
    private String nonce;
    /**
     * Callback timestamp header.
     */
    private String callbackTimestamp;
    /**
     * Processing status.
     */
    private Integer status;
    /**
     * Failure detail for later async processing.
     */
    private String failureMessage;
    /**
     * Raw request body.
     */
    private String rawPayload;

}
