DROP TABLE IF EXISTS controlled_content_transition_audit;
DROP TABLE IF EXISTS controlled_content_version_ref;

CREATE TABLE controlled_content_version_ref (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    content_type VARCHAR(64) NOT NULL,
    content_key VARCHAR(128) NOT NULL,
    native_master_id BIGINT NOT NULL,
    native_version_id BIGINT NOT NULL,
    version_no VARCHAR(64) NOT NULL,
    canonical_status VARCHAR(64) NOT NULL,
    domain_status VARCHAR(128),
    source_version_ref_id BIGINT,
    source_native_version_id BIGINT,
    successor_version_ref_id BIGINT,
    successor_native_version_id BIGINT,
    active_unique_flag TINYINT,
    open_candidate_unique_flag TINYINT,
    approval_process_instance_id VARCHAR(128),
    last_transition_time TIMESTAMP,
    creator VARCHAR(64),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64),
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_controlled_content_active UNIQUE
        (tenant_id, content_type, content_key, active_unique_flag),
    CONSTRAINT uk_controlled_content_open_candidate UNIQUE
        (tenant_id, content_type, content_key, open_candidate_unique_flag)
);

CREATE TABLE controlled_content_transition_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    version_ref_id BIGINT NOT NULL,
    content_type VARCHAR(64) NOT NULL,
    content_key VARCHAR(128) NOT NULL,
    from_status VARCHAR(64),
    to_status VARCHAR(64) NOT NULL,
    domain_from_status VARCHAR(128),
    domain_to_status VARCHAR(128),
    action VARCHAR(64) NOT NULL,
    event_key VARCHAR(256),
    actor_id BIGINT,
    reason VARCHAR(1024),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_registration_projection_test_failure
        CHECK (NOT (action = 'PUBLISH' AND reason = 'FORCE_ROLLBACK')),
    CONSTRAINT uk_controlled_content_transition_event UNIQUE
        (version_ref_id, action, event_key)
);

CREATE TRIGGER registration_projection_post_write_drift
    BEFORE UPDATE ON controlled_content_version_ref
    FOR EACH ROW
    CALL 'cn.iocoder.yudao.module.system.service.controlledcontent.ControlledContentRegistrationProjectionTransactionTest$PostWriteProjectionDriftTrigger';
