import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = process.cwd()
const readText = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

test('showroom hall list table component exists and uses real hall row columns', () => {
  const componentPath = 'src/views/showroom-admin/components/HallListTable.vue'
  assert.ok(fs.existsSync(path.join(root, componentPath)), 'HallListTable.vue should exist')
  const source = readText(componentPath)

  assert.match(source, /defineOptions\(\{ name: 'HallListTable' \}\)/)
  assert.match(source, /展柜名称/)
  assert.match(source, /展柜编码/)
  assert.match(source, /描述/)
  assert.match(source, /展项数量/)
  assert.match(source, /操作/)
  assert.match(source, /新增展柜/)
  assert.match(source, /查询/)
  assert.match(source, /重置/)
  assert.match(source, /编辑/)
  assert.match(source, /维护展项/)
  assert.match(source, /删除/)
  assert.match(source, /defineEmits/)
  assert.match(source, /create/)
  assert.match(source, /search/)
  assert.match(source, /delete/)
  assert.match(source, /hallId/)
  assert.match(source, /hallCode/)
  assert.match(source, /nameEn/)
  assert.match(source, /descriptionEn/)
  assert.match(source, /productMappings/)
  assert.match(source, /productMappings\.length/)
  assert.match(source, /row-key="hallId"/)
  assert.match(source, /mapping/)
  assert.match(source, /normalize/)
  assert.match(source, /normalizeRequiredString\(row, 'nameEn'/)
  assert.match(source, /normalizeRequiredString\(row, 'descriptionEn'/)
  assert.doesNotMatch(source, /展柜产品排序/)
  assert.doesNotMatch(source, /排序明细|映射排序/)
  assert.doesNotMatch(source, /mappingOrderSummary/)
  assert.doesNotMatch(source, /<el-table-column[^>]+displayOrder/)
  assert.doesNotMatch(source, /8 个展柜/)
  assert.doesNotMatch(source, /normalizeRequiredNumber\(row, 'id'/)
  assert.doesNotMatch(source, /normalizeRequiredString\(row, 'code'/)
  assert.doesNotMatch(source, /normalizeRequiredNumber\(row, 'productCount'/)
  assert.doesNotMatch(source, /normalizeRequiredString\(row, 'updateTime'/)
  assert.doesNotMatch(source, /normalizeStatus\(row\.status/)
  assert.doesNotMatch(source, /label="状态"/)
  assert.doesNotMatch(source, /label="更新时间"/)
  assert.doesNotMatch(source, /drag/i)
  assert.doesNotMatch(source, /封面/)
  assert.doesNotMatch(source, /推荐位/)
  assert.doesNotMatch(source, /上下线/)
})
