import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = process.cwd()
const readText = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

test('showroom product basic dialog fixes ownership to 瑛泰医疗 instead of exposing multiple company choices', () => {
  const source = readText('src/views/showroom-admin/index.vue')
  const contractsSource = readText('src/views/showroom-admin/product/contracts.ts')

  assert.match(source, /buildShowroomCompanyOptions/)
  assert.match(source, /applyFixedProductOwner/)
  assert.match(source, /companyCurrent/)
  assert.match(source, /return \['product', 'assignment', 'narration'\]\.includes\(activeSection\.value\)/)
  assert.match(source, /companyId/)
  assert.match(source, /瑛泰医疗/)
  assert.doesNotMatch(source, /label="所属公司ID"/)
  assert.doesNotMatch(source, /placeholder="请选择公司"/)
  assert.doesNotMatch(source, /v-for="option in productCompanyOptions"/)
  assert.doesNotMatch(source, /throw new Error\('未找到瑛泰医疗所属公司映射'\)/)
  assert.match(source, /label="产品归属\/类型"/)
  assert.match(source, /targetMarket/)
  assert.match(source, /pipelineLayout/)
  assert.match(source, /indicationContent/)
  assert.match(source, /coreSellingPoints/)
  assert.match(source, /modelSpecification/)
  assert.match(source, /coverImage/)
  assert.match(source, /UploadImg/)
  assert.match(contractsSource, /SHOWROOM_PRODUCT_OWNER_LABEL/)
  assert.match(contractsSource, /buildShowroomCompanyOptions/)
  assert.match(source, /<el-form-item label="BU"/)
  assert.match(source, /<el-form-item label="在售国家"/)
  assert.match(source, /<el-form-item label="Countries on Sale"/)
  assert.match(contractsSource, /label: 'BU'/)
  assert.match(contractsSource, /label: '在售国家'/)
  assert.match(contractsSource, /labelEn: 'Countries on Sale'/)
  assert.doesNotMatch(source, /<el-form-item label="管线布局"/)
  assert.doesNotMatch(source, /<el-form-item label="核心卖点"/)
  assert.doesNotMatch(source, /<el-form-item label="Pipeline Layout"/)
  assert.doesNotMatch(source, /<el-form-item label="Core Selling Points"/)
  assert.match(source, /确认按当前筛选条件批量补齐产品最新版本的中英文在售国家/)
  assert.match(source, /一键在售国家已完成/)
  assert.match(source, /语言在售国家/)
  assert.doesNotMatch(source, /中英文核心卖点|中英文卖点|语言卖点|一键卖点/)
  assert.doesNotMatch(contractsSource, /label: '管线布局'/)
  assert.doesNotMatch(contractsSource, /label: '核心卖点'/)
  assert.doesNotMatch(contractsSource, /labelEn: 'Pipeline Layout'/)
  assert.doesNotMatch(contractsSource, /labelEn: 'Core Selling Points'/)
})

test('showroom product detail dialog keeps only advanced fields and removes duplicated basic fields', () => {
  const source = readText('src/views/showroom-admin/product/ProductDetailDialog.vue')

  assert.match(source, /注册证/)
  assert.match(source, /临床效果/)
  assert.match(source, /FIM状态/)
  assert.doesNotMatch(source, /<el-form-item label="产品编码"/)
  assert.doesNotMatch(source, /<el-form-item label="中文名称"/)
  assert.doesNotMatch(source, /<el-form-item label="英文名称"/)
  assert.doesNotMatch(source, /<el-form-item label="所属公司"/)
  assert.doesNotMatch(source, /<el-form-item label="产品归属\/类型"/)
  assert.doesNotMatch(source, /<el-form-item label="生命周期"/)
  assert.doesNotMatch(source, /<el-form-item label="目标市场"/)
  assert.doesNotMatch(source, /<el-form-item label="BU"/)
  assert.doesNotMatch(source, /<el-form-item label="适应症"/)
  assert.doesNotMatch(source, /<el-form-item label="在售国家"/)
  assert.doesNotMatch(source, /<el-form-item label="型号规格"/)
})

test('showroom product list fixes ownership display to 瑛泰医疗 and removes dynamic company filter', () => {
  const source = readText('src/views/showroom-admin/components/ProductListTable.vue')

  assert.match(source, /瑛泰医疗/)
  assert.match(source, /ownerTypeText/)
  assert.doesNotMatch(source, /placeholder="所属公司ID"/)
  assert.doesNotMatch(source, /companyOptions/)
  assert.doesNotMatch(source, /companyNameById/)
})
