import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = process.cwd()
const readText = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8')

test('system nas api exposes get save and test endpoints', () => {
  const source = readText('src/api/system/nas/index.ts')
  const workflowSource = readText('src/api/dcc/controlledFile/workflow.ts')

  assert.match(source, /NasConfigVO/)
  assert.match(source, /port\?:\s*number/)
  assert.match(source, /domain\?:\s*string/)
  assert.match(source, /NasConfigTestRespVO/)
  assert.match(source, /NasFileListRespVO/)
  assert.match(source, /NasFileItemVO/)
  assert.match(source, /getNasConfig/)
  assert.match(source, /saveNasConfig/)
  assert.match(source, /testNasConfig/)
  assert.match(source, /listNasFiles/)
  assert.match(source, /\/infra\/file\/nas-config'/)
  assert.match(source, /\/infra\/file\/nas-config\/test'/)
  assert.match(source, /\/infra\/file\/nas-files'/)
  assert.match(workflowSource, /export type ControlledFileNasTransferSourceType\s*=\s*'NAS'\s*\|\s*'LOCAL_FOLDER'\s*\|\s*'NAS_UNCONTROLLED_IMPORT'/)
  assert.match(workflowSource, /sourceType:\s*ControlledFileNasTransferSourceType/)
  assert.match(workflowSource, /export interface ControlledFileNasTransferReqVO\s*\{[\s\S]*dccProjectCodeId:\s*number[\s\S]*productMasterId\?:\s*null/)
  assert.match(workflowSource, /LOCAL_FOLDER_IMPORT_REQUEST_TIMEOUT\s*=\s*0/)
  assert.match(workflowSource, /LOCAL_FOLDER_IMPORT_CHUNK_BYTES\s*=\s*32 \* 1024 \* 1024/)
  assert.match(workflowSource, /createLocalFolderImportSession/)
  assert.match(workflowSource, /uploadLocalFolderImportBatch/)
  assert.match(workflowSource, /getLocalFolderImportUploadState/)
  assert.match(workflowSource, /uploadLocalFolderImportChunk/)
  assert.match(workflowSource, /completeLocalFolderImportSession/)
  assert.match(workflowSource, /\/dcc\/controlled-files\/local-folder-import\/sessions'/)
  assert.match(workflowSource, /\/dcc\/controlled-files\/local-folder-import\/sessions\/\$\{taskId\}\/batches/)
  assert.match(workflowSource, /\/dcc\/controlled-files\/local-folder-import\/sessions\/\$\{taskId\}\/upload-state/)
  assert.match(workflowSource, /\/dcc\/controlled-files\/local-folder-import\/sessions\/\$\{taskId\}\/chunks/)
  assert.match(workflowSource, /\/dcc\/controlled-files\/local-folder-import\/sessions\/\$\{taskId\}\/complete/)
  assert.match(workflowSource, /headersType:\s*'multipart\/form-data'/)
  assert.doesNotMatch(workflowSource, /LOCAL_FOLDER_IMPORT_MAX_SIZE_BYTES/)
  assert.doesNotMatch(workflowSource, /本地文件夹导入大小超过/)
})

test('system nas page renders parameter form plus save and test actions', () => {
  const source = readText('src/views/system/nas/index.vue')

  assert.match(source, /defineOptions\(\{ name: 'SystemNasManagement' \}\)/)
  assert.match(source, /CardTitle title="NAS 管理"/)
  assert.match(source, /NAS 服务器/)
  assert.match(source, /NAS 端口/)
  assert.match(source, /共享名/)
  assert.match(source, /用户名/)
  assert.match(source, /密码/)
  assert.match(source, /show-password/)
  assert.match(source, /测试连接/)
  assert.match(source, /保存/)
  assert.match(source, /刷新目录/)
  assert.match(source, /选择/)
  assert.match(source, /导入文件夹/)
  assert.match(source, /导出/)
  assert.match(source, /转移/)
  assert.ok(
    source.indexOf('导入文件夹') > source.indexOf("{{ selectionMode ? '取消选择' : '选择' }}") &&
      source.indexOf('导入文件夹') < source.indexOf('导出'),
    '导入文件夹按钮必须位于选择与导出之间'
  )
  assert.match(source, /目录结构/)
  assert.match(source, /type="file"/)
  assert.match(source, /webkitdirectory/)
  assert.match(source, /multiple/)
  assert.match(source, /localFolderInputRef/)
  assert.match(source, /getNasConfig/)
  assert.match(source, /saveNasConfig/)
  assert.match(source, /testNasConfig/)
  assert.match(source, /listNasFiles/)
  assert.match(source, /v-if="shouldShowDomainField"/)
  assert.match(source, /shouldShowOptionalField/)
  assert.match(source, /补充连接参数/)
  assert.match(source, /补充端口 \/ 域/)
  assert.match(source, /shouldShowOptionalFields/)
  assert.match(source, /shouldShowPortField/)
  assert.match(source, /shouldShowDomainField/)
  assert.match(source, /buildNasConfigPayload/)
  assert.match(source, /validateField\(fieldsToValidate\)/)
  assert.match(source, /port:\s*shouldShowPortField\.value \? formData\.value\.port : undefined/)
  assert.match(source, /domain:\s*shouldShowDomainField\.value \? formData\.value\.domain\?\.trim\(\) \|\| undefined : undefined/)
  assert.match(source, /handleTest/)
  assert.match(source, /handleRefreshDirectory/)
  assert.match(source, /loadNasNode/)
  assert.match(source, /handleToggleSelectionMode/)
  assert.match(source, /handleTriggerLocalFolderImport/)
  assert.match(source, /handleLocalFolderSelected/)
  assert.match(source, /validateLocalFolderFiles/)
  assert.match(source, /buildLocalFolderImportSessionPayload/)
  assert.match(source, /getLocalFolderImportUploadState/)
  assert.match(source, /validateLocalFolderUploadStateMatchesSelection/)
  assert.match(source, /buildLocalFolderImportChunkFormData/)
  assert.match(source, /uploadLocalFolderImportChunks/)
  assert.match(source, /handleSubmitLocalFolderImport/)
  assert.match(source, /createLocalFolderImportSession/)
  assert.match(source, /uploadLocalFolderImportChunk/)
  assert.match(source, /completeLocalFolderImportSession/)
  assert.match(source, /handleExportSelection/)
  assert.match(source, /handleOpenTransferDialog/)
  assert.match(source, /handleSubmitTransfer/)
  assert.match(source, /getNasTransferTaskState/)
  assert.match(source, /scheduleTransferTaskPolling/)
  assert.match(source, /clearLastTransferTaskId/)
  assert.match(source, /clearStaleNasTransferTask/)
  assert.match(source, /isNasTransferTaskNotFoundError/)
  assert.match(source, /localStorage\.removeItem\(NAS_TRANSFER_LAST_TASK_ID_KEY\)/)
  assert.match(source, /最近 NAS 转移任务已不存在，请重新发起转移/)
  assert.match(source, /confirmTransferBeforeSubmit/)
  assert.match(source, /closeTransferDialogOnRouteLeave/)
  assert.match(source, /onBeforeRouteLeave/)
  assert.match(source, /transferDialog\.visible\s*=\s*false/)
  assert.match(source, /if\s*\(isTransferTaskActive\(result\.status\)\)\s*\{\s*transferDialog\.visible\s*=\s*true/s)
  assert.match(source, /testResult/)
  assert.match(source, /directoryTree/)
  assert.match(source, /directorySummary/)
  assert.match(source, /directorySkipped/)
  assert.match(source, /selectionMode/)
  assert.match(source, /selectedDirectoryPaths/)
  assert.match(source, /transferDialog/)
  assert.match(source, /canRefreshDirectory/)
  assert.match(source, /hasCompleteNasConfig/)
  assert.match(source, /hasConfiguredPort/)
  assert.match(source, /testResult\.value\?\.type === 'success' \|\| hasCompleteNasConfig\.value/)
  assert.match(source, /\blazy\b/)
  assert.match(source, /:load="loadNasNode"/)
  assert.match(source, /:show-checkbox="selectionMode"/)
  assert.match(source, /check-strictly/)
  assert.match(source, /部分目录已跳过/)
  assert.match(source, /已跳过目录/)
  assert.match(source, /导出功能暂未开放/)
  assert.match(source, /导入文件夹到 DCC/)
  assert.match(source, /转移到 DCC/)
  assert.match(source, /sourceType === 'LOCAL_FOLDER'/)
  assert.match(source, /sourceType !== 'LOCAL_FOLDER'/)
  assert.match(source, /本地文件夹导入任务已创建/)
  assert.match(source, /本地导入不采集 NAS 权限快照/)
  assert.match(source, /webkitRelativePath/)
  assert.match(source, /formData\.append\('relativePath'/)
  assert.match(source, /formData\.append\('fileName'/)
  assert.match(source, /formData\.append\('chunkSha256'/)
  assert.match(source, /formData\.append\('chunk'/)
  assert.match(source, /if\s*\(file\.size <= 0\)\s*\{\s*return 1\s*\}/)
  assert.match(source, /rootDirectoryName/)
  assert.match(source, /本地文件夹为空，无法导入/)
  assert.doesNotMatch(source, /本地文件夹包含空文件/)
  assert.match(source, /上传进度/)
  assert.match(source, /分片上传/)
  assert.match(source, /已上传文件/)
  assert.match(source, /expectedFileCount/)
  assert.match(source, /uploadedFileCount/)
  assert.match(source, /uploadedTotalBytes/)
  assert.match(source, /sessionCreatedAt/)
  assert.doesNotMatch(source, /LOCAL_FOLDER_IMPORT_MAX_SIZE_BYTES/)
  assert.doesNotMatch(source, /LOCAL_FOLDER_IMPORT_MAX_SIZE_LABEL/)
  assert.doesNotMatch(source, /本地文件夹导入大小超过/)
  assert.doesNotMatch(source, /C:\\\\/)
  assert.match(source, /开始转移确认/)
  assert.match(source, /ElMessageBox\.confirm/)
  assert.match(source, /NAS_TRANSFER_CONFIRM_MODAL_CLASS/)
  assert.match(source, /modalClass:\s*NAS_TRANSFER_CONFIRM_MODAL_CLASS/)
  assert.match(source, /nas-transfer-confirm-message-box-overlay/)
  assert.match(source, /z-index:\s*3200\s*!important/)
  assert.match(source, /不会预先递归统计整棵子树数量/)
  assert.match(source, /确认后将直接开始后台转移/)
  assert.match(source, /确认后将按分片上传，断开后可继续同一任务/)
  assert.match(source, /上传完成后将触发后台导入/)
  assert.doesNotMatch(source, /splitLocalFolderFilesIntoBatches/)
  assert.doesNotMatch(source, /buildLocalFolderImportBatchFormData/)
  assert.doesNotMatch(source, /uploadLocalFolderImportBatches/)
  assert.doesNotMatch(source, /uploadLocalFolderImportBatch/)
  assert.match(source, /模板类别/)
  assert.match(source, /DCC 项目/)
  assert.match(source, /getProjectCodePage/)
  assert.match(source, /DCC_PROJECT_CODE_STATUS_ENABLE/)
  assert.match(source, /projectCodeOptions/)
  assert.match(source, /productMasterId/)
  assert.match(source, /请选择 DCC 项目/)
  assert.doesNotMatch(source, /DCC 产品缺少启用且带 DCC 产品码的产品/)
  assert.match(source, /productMasterId:\s*null/)
  assert.match(source, /find\(\(item\) => item\.name === '其他'\)/)
  assert.match(source, /DCC 模板类别缺少启用的“其他”/)
  assert.match(source, /selectedTransferCategory/)
  assert.match(source, /自动落位未分类/)
  assert.match(source, /系统将自动落位到未分类目录/)
  assert.doesNotMatch(source, /DCC_TEMPLATE_CATEGORY_DIRECTORY_REQUIRED_MESSAGE/)
  assert.doesNotMatch(source, /当前 DCC 模板类别未绑定受控目录，请先在 DCC 文件类别维护目录绑定/)
  assert.doesNotMatch(source, /validateTransferCategoryDirectoryBinding/)
  assert.doesNotMatch(source, /find\(\(item\) => item\.name === '产品技术要求'\) \|\|/)
  assert.match(source, /生效日期/)
  assert.match(source, /文件名称=源文件名/)
  assert.match(source, /文件编号=去扩展名文件名/)
  assert.match(source, /初始版本=V1\.0/)
  assert.match(source, /转移任务/)
  assert.match(source, /任务正在后台执行/)
  assert.match(source, /NAS 转移任务已创建/)
  assert.match(source, /LOCAL_FOLDER/)
  assert.doesNotMatch(source, /可选，默认留空/)
  assert.match(source, /v-hasPermi="\['infra:nas:test'\]"/)
  assert.match(source, /v-hasPermi="\['infra:nas:update'\]"/)
  assert.match(source, /v-hasPermi="\['infra:nas:query'\]"/)
  assert.match(source, /:disabled="!canRefreshDirectory"/)
  assert.match(source, /:disabled="!selectionMode \|\| !selectedDirectoryPaths\.length"/)
  assert.doesNotMatch(source, /getNasDirectoryTree/)
})
