package cn.iocoder.yudao.module.mes.service.pro.batchrecord;

import cn.iocoder.yudao.module.mes.dal.dataobject.pro.batchrecord.MesProBatchRecordExecutionSignatureDO;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.RENDER_SOURCE_VERSION;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.RenderData;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.FILE_TIME_FORMATTER;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.jsonValue;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.requireRenderData;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.safeFileToken;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.sha256;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.sourceJson;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.utf8;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.value;

@Component
public class ExcelExecutionArchiveRenderer implements MesProBatchRecordExecutionArchiveRenderer {

    private static final String ARTIFACT_TYPE = "EXCEL";
    private static final String CONTENT_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

    @Override
    public String getArtifactType() {
        return ARTIFACT_TYPE;
    }

    @Override
    public MesProBatchRecordExecutionArchiveRenderResult render(MesProBatchRecordExecutionArchiveRenderContext context) {
        RenderData data = requireRenderData(context);
        byte[] content = renderWorkbook(data);
        String sha256 = sha256(content);
        return MesProBatchRecordExecutionArchiveRenderResult.builder()
                .fileName(fileName(data))
                .contentType(CONTENT_TYPE)
                .fileSize((long) content.length)
                .sha256(sha256)
                .renderSourceVersion(RENDER_SOURCE_VERSION)
                .content(content)
                .build();
    }

    private byte[] renderWorkbook(RenderData data) {
        try (Workbook workbook = new XSSFWorkbook(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            writeSummary(workbook.createSheet("Summary"), data);
            writeRecord(workbook.createSheet("Record"), data);
            writeSignatures(workbook.createSheet("Signatures"), data);
            writeManifest(workbook.createSheet("Manifest"), data);
            workbook.write(out);
            return out.toByteArray();
        } catch (IOException ex) {
            throw new IllegalStateException("Failed to render EDHR archive Excel workbook", ex);
        }
    }

    private void writeSummary(Sheet sheet, RenderData data) {
        int row = 0;
        row = writePair(sheet, row, "Render Source Version", RENDER_SOURCE_VERSION);
        row = writePair(sheet, row, "Generated By", data.context().getGeneratedBy());
        row = writePair(sheet, row, "Generated At", data.context().getGeneratedAt());
        row = writePair(sheet, row, "Execution ID", data.execution().getId());
        row = writePair(sheet, row, "Execution Code", data.execution().getExecutionCode());
        row = writePair(sheet, row, "Work Order", data.execution().getWorkOrderCode());
        row = writePair(sheet, row, "Batch Code", data.execution().getBatchCode());
        row = writePair(sheet, row, "Template Code", data.execution().getTemplateCode());
        row = writePair(sheet, row, "Template Name", data.execution().getTemplateName());
        writePair(sheet, row, "Status", data.execution().getStatus());
        autosize(sheet, 2);
    }

    private void writeRecord(Sheet sheet, RenderData data) {
        int row = 0;
        row = writePair(sheet, row, "Execution Snapshot JSON", jsonValue(data.executionSnapshot()));
        writePair(sheet, row, "Cell Values JSON", jsonValue(data.cellValues()));
        autosize(sheet, 2);
    }

    private void writeSignatures(Sheet sheet, RenderData data) {
        Row header = sheet.createRow(0);
        writeCells(header, "ID", "Execution ID", "Actor ID", "Action Type", "Signature Mode",
                "Password Verified", "Signed At", "Selected Signed At", "Display Signed At",
                "Signature Time Mode", "Selected Time Zone", "Selected Time Reason", "Selected Time Audit Hash",
                "Comment");
        int rowIndex = 1;
        for (MesProBatchRecordExecutionSignatureDO signature : data.signatures()) {
            Row row = sheet.createRow(rowIndex++);
            writeCells(row,
                    signature.getId(),
                    signature.getExecutionId(),
                    signature.getActorId(),
                    signature.getActionType(),
                    signature.getSignatureMode(),
                    signature.getPasswordVerified(),
                    signature.getSignedAt(),
                    signature.getSelectedSignedAt(),
                    signature.getSignatureDisplayAt(),
                    signature.getSignatureTimeMode(),
                    signature.getSelectedTimeZone(),
                    signature.getSelectedTimeReason(),
                    signature.getSelectedTimeAuditHash(),
                    signature.getComment());
        }
        autosize(sheet, 14);
    }

    private void writeManifest(Sheet sheet, RenderData data) {
        int row = 0;
        row = writePair(sheet, row, "Render Source Version", RENDER_SOURCE_VERSION);
        row = writePair(sheet, row, "Execution Snapshot Hash", data.context().getExecutionSnapshotHash());
        row = writePair(sheet, row, "Cell Values Hash", data.context().getCellValuesHash());
        row = writePair(sheet, row, "Signature Hash", data.context().getSignatureHash());
        row = writePair(sheet, row, "Approval Snapshot ID", data.context().getApprovalSnapshotId());
        row = writePair(sheet, row, "Approval Snapshot Hash", data.context().getApprovalSnapshotHash());
        row = writePair(sheet, row, "Source Payload Hash", sha256(utf8(sourceJson(data))));
        row = writePair(sheet, row, "Artifact Type", ARTIFACT_TYPE);
        row = writePair(sheet, row, "Content Type", CONTENT_TYPE);
        writePair(sheet, row, "Generated At", data.context().getGeneratedAt());
        autosize(sheet, 2);
    }

    private int writePair(Sheet sheet, int rowIndex, String key, Object value) {
        Row row = sheet.createRow(rowIndex);
        row.createCell(0).setCellValue(key);
        row.createCell(1).setCellValue(value(value));
        return rowIndex + 1;
    }

    private void writeCells(Row row, Object... values) {
        for (int i = 0; i < values.length; i++) {
            Cell cell = row.createCell(i);
            cell.setCellValue(value(values[i]));
        }
    }

    private void autosize(Sheet sheet, int columns) {
        for (int i = 0; i < columns; i++) {
            sheet.autoSizeColumn(i);
        }
    }

    private String fileName(RenderData data) {
        return "EDHR-" + safeFileToken(data.execution().getExecutionCode())
                + "-" + data.context().getGeneratedAt().format(FILE_TIME_FORMATTER) + ".xlsx";
    }
}
