package cn.iocoder.yudao.module.mes.service.pro.batchrecord;

import cn.hutool.core.util.StrUtil;
import cn.iocoder.yudao.module.mes.dal.dataobject.pro.batchrecord.MesProBatchRecordExecutionSignatureDO;
import cn.iocoder.yudao.module.mes.dal.dataobject.pro.batchrecord.MesProBatchRecordExecutionAttachmentDO;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType0Font;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.RENDER_SOURCE_VERSION;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.RenderData;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.FILE_TIME_FORMATTER;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.jsonValue;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.requireRenderData;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.safeFileToken;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.sha256;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.shortText;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.sourceJson;
import static cn.iocoder.yudao.module.mes.service.pro.batchrecord.ExecutionArchiveRendererSupport.value;

@Component
public class PdfExecutionArchiveRenderer implements MesProBatchRecordExecutionArchiveRenderer {

    private static final String ARTIFACT_TYPE = "PDF";
    private static final String CONTENT_TYPE = "application/pdf";
    private static final String FONT_PATH = "C:/Windows/Fonts/simhei.ttf";
    private static final float MARGIN = 48F;
    private static final float FONT_SIZE = 10F;
    private static final float TITLE_FONT_SIZE = 16F;
    private static final float LEADING = 14F;
    private static final int WRAP_CHARS = 96;
    private static final DateTimeFormatter DISPLAY_TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Override
    public String getArtifactType() {
        return ARTIFACT_TYPE;
    }

    @Override
    public MesProBatchRecordExecutionArchiveRenderResult render(MesProBatchRecordExecutionArchiveRenderContext context) {
        RenderData data = requireRenderData(context);
        byte[] content = renderPdf(data);
        String sha256 = sha256(content);
        return MesProBatchRecordExecutionArchiveRenderResult.builder()
                .fileName(fileName(data))
                .contentType(CONTENT_TYPE)
                .fileSize((long) content.length)
                .sha256(sha256)
                .renderSourceVersion(RENDER_SOURCE_VERSION)
                .content(content)
                .build();
    }

    private byte[] renderPdf(RenderData data) {
        try (PDDocument document = new PDDocument(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            File fontFile = new File(FONT_PATH);
            if (!fontFile.isFile()) {
                throw new IllegalStateException("EDHR archive PDF font is missing: " + FONT_PATH);
            }
            PDType0Font font = PDType0Font.load(document, fontFile);
            PdfWriter writer = new PdfWriter(document, font);
            writer.writeTitle("EDHR Execution Archive");
            for (String line : lines(data)) {
                writer.writeLine(line);
            }
            writer.close();
            document.save(out);
            return out.toByteArray();
        } catch (IOException ex) {
            throw new IllegalStateException("Failed to render EDHR archive PDF", ex);
        }
    }

    private List<String> lines(RenderData data) {
        List<String> lines = new ArrayList<>();
        lines.add("Render Source Version: " + RENDER_SOURCE_VERSION);
        lines.add("Generated By: " + data.context().getGeneratedBy());
        lines.add("Generated At: " + data.context().getGeneratedAt());
        lines.add("Execution ID: " + value(data.execution().getId()));
        lines.add("Execution Code: " + value(data.execution().getExecutionCode()));
        lines.add("Work Order: " + value(data.execution().getWorkOrderCode()));
        lines.add("Batch Code: " + value(data.execution().getBatchCode()));
        lines.add("Template: " + value(data.execution().getTemplateName()));
        lines.add("Status: " + value(data.execution().getStatus()));
        lines.add("Execution Snapshot Hash: " + data.context().getExecutionSnapshotHash());
        lines.add("Cell Values Hash: " + data.context().getCellValuesHash());
        lines.add("Signature Hash: " + data.context().getSignatureHash());
        lines.add("Attachment Manifest Head Hash: " + value(data.context().getAttachmentManifestHeadHash()));
        lines.add("Approval Snapshot ID: " + data.context().getApprovalSnapshotId());
        lines.add("Approval Snapshot Hash: " + data.context().getApprovalSnapshotHash());
        lines.add("Form Slot Manifest: " + jsonValue(data.context().getFormSlotManifest()));
        lines.add("");
        lines.add("Execution Snapshot:");
        lines.add(shortText(jsonValue(data.executionSnapshot()), 3600));
        lines.add("");
        lines.add("Cell Values:");
        lines.add(shortText(jsonValue(data.cellValues()), 3600));
        lines.add("");
        lines.add("Signatures:");
        for (MesProBatchRecordExecutionSignatureDO signature : data.signatures()) {
            lines.add("ID=" + value(signature.getId())
                    + ", Action=" + value(signature.getActionType())
                    + ", Meaning=" + value(signatureMeaning(signature.getActionType()))
                    + ", Signer=" + value(resolveSignerName(signature))
                    + ", Purpose=" + value(resolveSignaturePurpose(signature))
                    + ", Mode=" + value(signature.getSignatureMode())
                    + ", PasswordVerified=" + value(signature.getPasswordVerified())
                    + ", SignedAt=" + formatDateTime(signature.getSignedAt())
                    + ", Comment=" + value(signature.getComment()));
            lines.add("  SelectedSignedAt=" + formatDateTime(signature.getSelectedSignedAt()));
            lines.add("  DisplaySignedAt=" + formatDateTime(firstNonNull(signature.getSignatureDisplayAt(),
                    signature.getSelectedSignedAt(), signature.getSignedAt())) + displayTimeZone(signature));
            lines.add("  SignatureTimeMode=" + value(signature.getSignatureTimeMode()));
            lines.add("  SelectedTimeZone=" + value(signature.getSelectedTimeZone()));
            lines.add("  SelectedTimeReason=" + value(signature.getSelectedTimeReason()));
            lines.add("  SelectedTimeAuditHash=" + value(signature.getSelectedTimeAuditHash()));
            lines.add("  RecordHash=" + value(resolveRecordHash(signature)));
        }
        lines.add("");
        lines.add("Attachments:");
        if (data.attachments().isEmpty()) {
            lines.add("None");
        }
        for (MesProBatchRecordExecutionAttachmentDO attachment : data.attachments()) {
            lines.add("ID=" + value(attachment.getId())
                    + ", Field=" + value(attachment.getFieldKey())
                    + ", Path=" + value(attachment.getFieldPath())
                    + ", Label=" + value(attachment.getFieldLabel())
                    + ", Type=" + value(attachment.getAttachmentType())
                    + ", Group=" + value(attachment.getAttachmentGroupKey())
                    + ", File=" + value(attachment.getFileName())
                    + ", ContentType=" + value(attachment.getContentType())
                    + ", Size=" + value(attachment.getFileSize())
                    + ", SHA256=" + value(attachment.getSha256())
                    + ", AttachmentHash=" + value(attachment.getAttachmentHash()));
        }
        lines.add("");
        lines.add("Source Payload Hash: " + sha256(ExecutionArchiveRendererSupport.utf8(sourceJson(data))));
        return lines;
    }

    private String signatureMeaning(String actionType) {
        return switch (String.valueOf(actionType)) {
            case MesProBatchRecordExecutionSignatureService.ACTION_FIELD_CHANGE -> "字段变更";
            case MesProBatchRecordExecutionSignatureService.ACTION_FORM_REVIEW -> "表单复核";
            case MesProBatchRecordExecutionSignatureService.ACTION_SUBMIT -> "提交审批";
            case MesProBatchRecordExecutionSignatureService.ACTION_APPROVE -> "审批通过";
            case MesProBatchRecordExecutionSignatureService.ACTION_REJECT -> "审批驳回";
            case MesProBatchRecordExecutionSignatureService.ACTION_ARCHIVE_SEAL -> "归档封存";
            default -> actionType;
        };
    }

    private String resolveSignerName(MesProBatchRecordExecutionSignatureDO signature) {
        return firstNonBlank(signature.getActorName(), signature.getActorNicknameSnapshot(),
                signature.getActorUsernameSnapshot(), value(signature.getActorId()));
    }

    private String resolveSignaturePurpose(MesProBatchRecordExecutionSignatureDO signature) {
        return firstNonBlank(signature.getSignaturePurpose(), signatureMeaning(signature.getActionType()));
    }

    private String resolveRecordHash(MesProBatchRecordExecutionSignatureDO signature) {
        return firstNonBlank(signature.getRecordHashSnapshot(), signature.getFieldAuditHeadHash(),
                signature.getCellValuesHash(), signature.getSelectedTimeAuditHash());
    }

    private String formatDateTime(LocalDateTime time) {
        return time == null ? "--" : DISPLAY_TIME.format(time);
    }

    private String displayTimeZone(MesProBatchRecordExecutionSignatureDO signature) {
        String zone = signature.getSelectedTimeZone();
        return StrUtil.isBlank(zone) ? "" : " (" + zone + ")";
    }

    private String firstNonBlank(String first, String second) {
        return StrUtil.isNotBlank(first) ? first : second;
    }

    private String firstNonBlank(String first, String second, String third, String fourth) {
        if (StrUtil.isNotBlank(first)) {
            return first;
        }
        if (StrUtil.isNotBlank(second)) {
            return second;
        }
        if (StrUtil.isNotBlank(third)) {
            return third;
        }
        return fourth;
    }

    private LocalDateTime firstNonNull(LocalDateTime first, LocalDateTime second, LocalDateTime third) {
        if (first != null) {
            return first;
        }
        if (second != null) {
            return second;
        }
        return third;
    }

    private String fileName(RenderData data) {
        return "EDHR-" + safeFileToken(data.execution().getExecutionCode())
                + "-" + data.context().getGeneratedAt().format(FILE_TIME_FORMATTER) + ".pdf";
    }

    private static final class PdfWriter {

        private final PDDocument document;
        private final PDType0Font font;
        private PDPageContentStream contentStream;
        private float cursorY;

        private PdfWriter(PDDocument document, PDType0Font font) throws IOException {
            this.document = document;
            this.font = font;
            addPage();
        }

        private void writeTitle(String text) throws IOException {
            ensureSpace(TITLE_FONT_SIZE + LEADING);
            contentStream.beginText();
            contentStream.setFont(font, TITLE_FONT_SIZE);
            contentStream.newLineAtOffset(MARGIN, cursorY);
            contentStream.showText(text);
            contentStream.endText();
            cursorY -= TITLE_FONT_SIZE + LEADING;
        }

        private void writeLine(String text) throws IOException {
            for (String wrappedLine : wrap(text)) {
                ensureSpace(LEADING);
                contentStream.beginText();
                contentStream.setFont(font, FONT_SIZE);
                contentStream.newLineAtOffset(MARGIN, cursorY);
                contentStream.showText(wrappedLine);
                contentStream.endText();
                cursorY -= LEADING;
            }
        }

        private void ensureSpace(float requiredHeight) throws IOException {
            if (cursorY - requiredHeight >= MARGIN) {
                return;
            }
            contentStream.close();
            addPage();
        }

        private void addPage() throws IOException {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            contentStream = new PDPageContentStream(document, page);
            cursorY = page.getMediaBox().getHeight() - MARGIN;
        }

        private void close() throws IOException {
            if (contentStream != null) {
                contentStream.close();
            }
        }

        private List<String> wrap(String text) {
            String source = value(text);
            if (source.isEmpty()) {
                return List.of("");
            }
            List<String> lines = new ArrayList<>();
            int index = 0;
            while (index < source.length()) {
                int end = Math.min(index + WRAP_CHARS, source.length());
                lines.add(source.substring(index, end));
                index = end;
            }
            return lines;
        }
    }
}
