-- Showroom V1 business schema baseline.
-- Reuses existing BPM, system notify, and file-storage tables; this file owns only showroom_* tables.

CREATE TABLE IF NOT EXISTS `showroom_company` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `company_code` varchar(64) NOT NULL,
    `display_name` varchar(255) NOT NULL,
    `display_name_en` varchar(255) DEFAULT NULL,
    `company_type` varchar(32) NOT NULL,
    `current_revision_id` bigint DEFAULT NULL,
    `current_revision_no` int DEFAULT NULL,
    `incomplete_flag` bit(1) NOT NULL DEFAULT b'0',
    `status` varchar(32) NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_company_code` (`tenant_id`, `company_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom company master';

CREATE TABLE IF NOT EXISTS `showroom_company_revision` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `company_id` bigint NOT NULL,
    `revision_no` int NOT NULL,
    `status` varchar(32) NOT NULL,
    `development_history` text DEFAULT NULL,
    `development_history_en` text DEFAULT NULL,
    `park_introduction` text DEFAULT NULL,
    `park_introduction_en` text DEFAULT NULL,
    `incubation_platform` text DEFAULT NULL,
    `incubation_platform_en` text DEFAULT NULL,
    `subsidiary_overview` text DEFAULT NULL,
    `subsidiary_overview_en` text DEFAULT NULL,
    `stock_info` text DEFAULT NULL,
    `stock_info_en` text DEFAULT NULL,
    `cover_image` text DEFAULT NULL,
    `core_manufacturing_capability` text DEFAULT NULL,
    `core_manufacturing_capability_en` text DEFAULT NULL,
    `honors_awards` text DEFAULT NULL,
    `honors_awards_en` text DEFAULT NULL,
    `display_name_snapshot` varchar(255) DEFAULT NULL,
    `display_name_en_snapshot` varchar(255) DEFAULT NULL,
    `company_type_snapshot` varchar(32) DEFAULT NULL,
    `submitted_by` bigint DEFAULT NULL,
    `approved_by` bigint DEFAULT NULL,
    `published_at` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_company_revision_no` (`tenant_id`, `company_id`, `revision_no`),
    KEY `idx_showroom_company_revision_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom company revision';

CREATE TABLE IF NOT EXISTS `showroom_product` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `product_master_id` bigint DEFAULT NULL,
    `product_code` varchar(64) NOT NULL,
    `legacy_product_code` varchar(64) DEFAULT NULL COMMENT '旧展厅底表产品编码，如 product_001',
    `current_revision_id` bigint DEFAULT NULL,
    `current_revision_no` int DEFAULT NULL,
    `incomplete_flag` bit(1) NOT NULL DEFAULT b'0',
    `status` varchar(32) NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_showroom_product_master_id` (`tenant_id`, `product_master_id`),
    UNIQUE KEY `uk_showroom_product_legacy_code` (`tenant_id`, `legacy_product_code`),
    UNIQUE KEY `uk_showroom_product_code` (`tenant_id`, `product_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom product master';

CREATE TABLE IF NOT EXISTS `showroom_product_revision` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `product_id` bigint NOT NULL,
    `revision_no` int NOT NULL,
    `status` varchar(32) NOT NULL,
    `name_cn` varchar(255) DEFAULT NULL,
    `name_en` varchar(255) DEFAULT NULL,
    `owner_company_id` bigint DEFAULT NULL,
    `product_owner_type` varchar(32) DEFAULT NULL,
    `lifecycle_stage` varchar(32) DEFAULT NULL,
    `target_market` text DEFAULT NULL,
    `target_market_en` text DEFAULT NULL,
    `pipeline_layout` text DEFAULT NULL,
    `pipeline_layout_en` text DEFAULT NULL,
    `registration_certificate` text DEFAULT NULL,
    `registration_certificate_en` text DEFAULT NULL,
    `indication_content` text DEFAULT NULL,
    `indication_content_en` text DEFAULT NULL,
    `core_selling_points` text DEFAULT NULL,
    `core_selling_points_en` text DEFAULT NULL,
    `model_specification` text DEFAULT NULL,
    `model_specification_en` text DEFAULT NULL,
    `cover_image` text DEFAULT NULL,
    `clinical_effect` text DEFAULT NULL,
    `clinical_effect_en` text DEFAULT NULL,
    `fim_status` varchar(64) DEFAULT NULL,
    `fim_status_en` varchar(255) DEFAULT NULL,
    `submitted_by` bigint DEFAULT NULL,
    `approved_by` bigint DEFAULT NULL,
    `published_at` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_product_revision_no` (`tenant_id`, `product_id`, `revision_no`),
    KEY `idx_showroom_product_revision_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom product revision';

CREATE TABLE IF NOT EXISTS `showroom_version_bundle` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `target_type` varchar(32) NOT NULL,
    `target_id` bigint NOT NULL,
    `revision_id` bigint NOT NULL,
    `revision_no` int NOT NULL,
    `release_preview_asset_version_id` bigint DEFAULT NULL,
    `narration_zh_version_id` bigint DEFAULT NULL,
    `narration_en_version_id` bigint DEFAULT NULL,
    `copied_from_revision_id` bigint DEFAULT NULL,
    `published_by` bigint DEFAULT NULL,
    `published_at` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_version_bundle_revision` (`tenant_id`, `target_type`, `target_id`, `revision_id`),
    UNIQUE KEY `uk_showroom_version_bundle_no` (`tenant_id`, `target_type`, `target_id`, `revision_no`),
    KEY `idx_showroom_version_bundle_published_at` (`target_type`, `target_id`, `published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom version center readable bundle';

CREATE TABLE IF NOT EXISTS `showroom_product_revision_relation` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `product_revision_id` bigint NOT NULL,
    `related_product_id` bigint NOT NULL,
    `relation_type` varchar(32) NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_product_revision_relation` (`tenant_id`, `product_revision_id`, `related_product_id`, `relation_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom product revision relation';

CREATE TABLE IF NOT EXISTS `showroom_product_cover_batch_task` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `operator_user_id` bigint NOT NULL,
    `status` varchar(32) NOT NULL,
    `keyword` varchar(255) DEFAULT NULL,
    `lifecycle_stage` varchar(32) DEFAULT NULL,
    `incomplete_status` varchar(32) DEFAULT NULL,
    `approval_status` varchar(32) DEFAULT NULL,
    `cover_generation_mode` varchar(32) NOT NULL,
    `prompt_version_id` bigint DEFAULT NULL,
    `matched_count` int NOT NULL DEFAULT 0,
    `published_count` int NOT NULL DEFAULT 0,
    `skipped_unpublished_count` int NOT NULL DEFAULT 0,
    `skipped_existing_count` int NOT NULL DEFAULT 0,
    `succeeded_count` int NOT NULL DEFAULT 0,
    `failed_count` int NOT NULL DEFAULT 0,
    `remaining_pending_count` int NOT NULL DEFAULT 0,
    `next_check_at` datetime DEFAULT NULL,
    `last_run_at` datetime DEFAULT NULL,
    `completed_at` datetime DEFAULT NULL,
    `last_failure_message` varchar(512) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_showroom_cover_batch_task_status` (`status`, `next_check_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom product cover batch task';

CREATE TABLE IF NOT EXISTS `showroom_product_cover_batch_task_item` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `task_id` bigint NOT NULL,
    `product_id` bigint NOT NULL,
    `source_revision_id` bigint DEFAULT NULL,
    `product_code` varchar(64) NOT NULL,
    `name_cn` varchar(255) DEFAULT NULL,
    `name_en` varchar(255) DEFAULT NULL,
    `prompt_fields_json` longtext NOT NULL,
    `status` varchar(32) NOT NULL,
    `attempt_count` int NOT NULL DEFAULT 0,
    `last_error` varchar(512) DEFAULT NULL,
    `generated_cover_image` text DEFAULT NULL,
    `last_attempt_at` datetime DEFAULT NULL,
    `completed_at` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_cover_batch_task_item` (`tenant_id`, `task_id`, `product_id`),
    KEY `idx_showroom_cover_batch_task_item_status` (`task_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom product cover batch task item';

CREATE TABLE IF NOT EXISTS `showroom_product_translate_publish_batch_task` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Task ID',
    `operator_user_id` bigint NOT NULL COMMENT 'Operator user ID',
    `status` varchar(32) NOT NULL COMMENT 'WAITING/RUNNING/COMPLETED',
    `keyword` varchar(255) DEFAULT NULL COMMENT 'Keyword filter snapshot',
    `lifecycle_stage` varchar(32) DEFAULT NULL COMMENT 'Lifecycle filter snapshot',
    `incomplete_status` varchar(32) DEFAULT NULL COMMENT 'Incomplete filter snapshot',
    `approval_status` varchar(32) DEFAULT NULL COMMENT 'Approval filter snapshot',
    `matched_count` int NOT NULL DEFAULT 0 COMMENT 'Matched product count',
    `succeeded_count` int NOT NULL DEFAULT 0 COMMENT 'Succeeded product count',
    `failed_count` int NOT NULL DEFAULT 0 COMMENT 'Failed product count',
    `remaining_count` int NOT NULL DEFAULT 0 COMMENT 'Remaining product count',
    `current_product_id` bigint DEFAULT NULL COMMENT 'Current product ID',
    `current_product_code` varchar(64) DEFAULT NULL COMMENT 'Current product code',
    `current_product_name_cn` varchar(255) DEFAULT NULL COMMENT 'Current product Chinese name',
    `last_run_at` datetime DEFAULT NULL COMMENT 'Last run time',
    `completed_at` datetime DEFAULT NULL COMMENT 'Completed time',
    `last_failure_message` varchar(512) DEFAULT NULL COMMENT 'Last failure message',
    `creator` varchar(64) DEFAULT '' COMMENT 'Creator',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `updater` varchar(64) DEFAULT '' COMMENT 'Updater',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted flag',
    `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT 'Tenant ID',
    PRIMARY KEY (`id`),
    KEY `idx_showroom_translate_publish_task_status` (`tenant_id`, `status`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom product translate publish batch task';

CREATE TABLE IF NOT EXISTS `showroom_product_translate_publish_batch_task_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Item ID',
    `task_id` bigint NOT NULL COMMENT 'Task ID',
    `product_id` bigint NOT NULL COMMENT 'Product ID',
    `source_revision_id` bigint DEFAULT NULL COMMENT 'Source revision ID',
    `product_code` varchar(64) NOT NULL COMMENT 'Product code',
    `name_cn` varchar(255) DEFAULT NULL COMMENT 'Chinese name',
    `name_en` varchar(255) DEFAULT NULL COMMENT 'English name',
    `status` varchar(32) NOT NULL COMMENT 'WAITING/RUNNING/COMPLETED/FAILED',
    `attempt_count` int NOT NULL DEFAULT 0 COMMENT 'Attempt count',
    `last_error` varchar(512) DEFAULT NULL COMMENT 'Last error',
    `published_revision_id` bigint DEFAULT NULL COMMENT 'Published revision ID',
    `last_attempt_at` datetime DEFAULT NULL COMMENT 'Last attempt time',
    `completed_at` datetime DEFAULT NULL COMMENT 'Completed time',
    `creator` varchar(64) DEFAULT '' COMMENT 'Creator',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `updater` varchar(64) DEFAULT '' COMMENT 'Updater',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT 'Deleted flag',
    `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT 'Tenant ID',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_translate_publish_batch_task_item` (`tenant_id`, `task_id`, `product_id`),
    KEY `idx_showroom_translate_publish_task_item_status` (`tenant_id`, `task_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom product translate publish batch task item';

CREATE TABLE IF NOT EXISTS `showroom_image_prompt_version` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `scene_code` varchar(64) NOT NULL,
    `version_no` int NOT NULL,
    `template_text` longtext NOT NULL,
    `change_note` varchar(255) DEFAULT NULL,
    `placeholder_codes_json` varchar(1000) NOT NULL,
    `use_count` int NOT NULL DEFAULT 0,
    `last_used_at` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_image_prompt_scene_version` (`scene_code`, `version_no`),
    KEY `idx_showroom_image_prompt_scene` (`scene_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom image prompt version';

CREATE TABLE IF NOT EXISTS `showroom_hall` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `hall_code` varchar(64) NOT NULL,
    `name` varchar(255) NOT NULL,
    `description` text DEFAULT NULL,
    `name_en` varchar(255) DEFAULT NULL,
    `description_en` text DEFAULT NULL,
    `canvas_background_image_url` varchar(1024) DEFAULT NULL,
    `display_order` int NOT NULL,
    `status` varchar(32) NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_hall_code` (`tenant_id`, `hall_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom hall';

CREATE TABLE IF NOT EXISTS `showroom_hall_product` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `hall_id` bigint NOT NULL,
    `product_id` bigint NOT NULL,
    `display_order` int NOT NULL,
    `layout_x` decimal(8,6) DEFAULT NULL COMMENT 'Normalized canvas rectangle x',
    `layout_y` decimal(8,6) DEFAULT NULL COMMENT 'Normalized canvas rectangle y',
    `layout_width` decimal(8,6) DEFAULT NULL COMMENT 'Normalized canvas rectangle width',
    `layout_height` decimal(8,6) DEFAULT NULL COMMENT 'Normalized canvas rectangle height',
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_hall_product` (`tenant_id`, `hall_id`, `product_id`),
    KEY `idx_showroom_hall_product_order` (`hall_id`, `display_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom hall product mapping';

CREATE TABLE IF NOT EXISTS `showroom_change_request` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `target_type` varchar(32) NOT NULL,
    `target_id` bigint NOT NULL,
    `target_revision_id` bigint DEFAULT NULL,
    `module_code` varchar(64) NOT NULL,
    `request_type` varchar(32) NOT NULL,
    `submission_source` varchar(32) NOT NULL,
    `status` varchar(64) NOT NULL,
    `process_instance_id` varchar(64) DEFAULT NULL,
    `submitted_by` bigint NOT NULL,
    `submitter_dept_id` bigint DEFAULT NULL,
    `submitted_at` datetime NOT NULL,
    `supervisor_user_id` bigint DEFAULT NULL,
    `supervisor_dept_id` bigint DEFAULT NULL,
    `supervisor_action_at` datetime DEFAULT NULL,
    `gaoxin_user_id` bigint DEFAULT NULL,
    `gaoxin_action_at` datetime DEFAULT NULL,
    `rejection_reason` varchar(1024) DEFAULT NULL,
    `source_assignment_id` bigint DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_showroom_change_request_target` (`target_type`, `target_id`, `target_revision_id`),
    KEY `idx_showroom_change_request_process` (`process_instance_id`),
    KEY `idx_showroom_change_request_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom change request';

CREATE TABLE IF NOT EXISTS `showroom_change_request_item` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `change_request_id` bigint NOT NULL,
    `field_code` varchar(128) NOT NULL,
    `old_value_json` json DEFAULT NULL,
    `new_value_json` json DEFAULT NULL,
    `approval_status` varchar(32) NOT NULL,
    `approved_by` bigint DEFAULT NULL,
    `approved_at` datetime DEFAULT NULL,
    `comment` varchar(1024) DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_showroom_change_request_item_request` (`change_request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom change request item';

CREATE TABLE IF NOT EXISTS `showroom_change_request_signature` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `change_request_id` bigint NOT NULL,
    `approval_stage` varchar(32) NOT NULL,
    `action_type` varchar(32) NOT NULL,
    `actor_id` bigint NOT NULL,
    `signature_mode` varchar(32) NOT NULL,
    `password_verified` bit(1) NOT NULL DEFAULT b'0',
    `comment` varchar(1024) DEFAULT NULL,
    `signed_at` datetime NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_showroom_change_request_signature_request` (`change_request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom change request signature';

CREATE TABLE IF NOT EXISTS `showroom_version_audit` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `target_type` varchar(32) NOT NULL,
    `target_id` bigint NOT NULL,
    `revision_id` bigint DEFAULT NULL,
    `field_code` varchar(128) NOT NULL,
    `old_value_json` json DEFAULT NULL,
    `new_value_json` json DEFAULT NULL,
    `operator_id` bigint NOT NULL,
    `operator_action` varchar(64) NOT NULL,
    `created_at` datetime NOT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_showroom_version_audit_target` (`target_type`, `target_id`, `revision_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom version audit';

CREATE TABLE IF NOT EXISTS `showroom_field_assignment` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `target_type` varchar(32) NOT NULL,
    `target_id` bigint NOT NULL,
    `field_code` varchar(128) NOT NULL,
    `assignee_user_id` bigint NOT NULL,
    `assigned_by` bigint NOT NULL,
    `status` varchar(32) NOT NULL,
    `notify_message_id` bigint NOT NULL,
    `last_saved_revision_id` bigint DEFAULT NULL,
    `last_change_request_id` bigint DEFAULT NULL,
    `latest_auto_saved_at` datetime DEFAULT NULL,
    `submitted_at` datetime DEFAULT NULL,
    `created_at` datetime NOT NULL,
    `closed_at` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_showroom_field_assignment_target` (`target_type`, `target_id`, `field_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom field assignment';

CREATE TABLE IF NOT EXISTS `showroom_product_comment` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `product_id` bigint NOT NULL,
    `target_revision_id` bigint DEFAULT NULL,
    `change_request_id` bigint DEFAULT NULL,
    `parent_comment_id` bigint DEFAULT NULL,
    `anchor_type` varchar(32) NOT NULL,
    `anchor_key` varchar(128) DEFAULT NULL,
    `content` text NOT NULL,
    `status` varchar(32) NOT NULL,
    `created_by` bigint NOT NULL,
    `created_at` datetime NOT NULL,
    `resolved_by` bigint DEFAULT NULL,
    `resolved_at` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_showroom_product_comment_anchor` (`product_id`, `anchor_type`, `anchor_key`),
    KEY `idx_showroom_product_comment_request` (`change_request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom product discussion comment';

CREATE TABLE IF NOT EXISTS `showroom_narration_version` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `target_type` varchar(32) NOT NULL,
    `target_id` bigint NOT NULL,
    `source_revision_id` bigint DEFAULT NULL,
    `audience_type` varchar(32) NOT NULL,
    `language` varchar(16) NOT NULL,
    `version_no` int NOT NULL,
    `script_text` text DEFAULT NULL,
    `audio_file_id` bigint DEFAULT NULL,
    `audio_duration_seconds` int DEFAULT NULL,
    `voice` varchar(64) DEFAULT NULL,
    `generation_status` varchar(32) NOT NULL,
    `status` varchar(32) NOT NULL,
    `generated_by_ai` bit(1) NOT NULL DEFAULT b'0',
    `generated_at` datetime DEFAULT NULL,
    `published_at` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_narration_version_no` (`tenant_id`, `target_type`, `target_id`, `audience_type`, `language`, `version_no`),
    KEY `idx_showroom_narration_live` (`target_type`, `target_id`, `audience_type`, `language`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom narration version';

CREATE TABLE IF NOT EXISTS `showroom_preview_asset_version` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `target_type` varchar(32) NOT NULL,
    `target_id` bigint NOT NULL,
    `source_revision_id` bigint DEFAULT NULL,
    `version_no` int NOT NULL,
    `image_file_id` bigint NOT NULL,
    `status` varchar(32) NOT NULL,
    `generated_by_ai` bit(1) NOT NULL DEFAULT b'0',
    `generated_at` datetime DEFAULT NULL,
    `published_at` datetime DEFAULT NULL,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_showroom_preview_asset_version_no` (`tenant_id`, `target_type`, `target_id`, `version_no`),
    KEY `idx_showroom_preview_asset_live` (`target_type`, `target_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Showroom preview asset version';
