export const SHOWROOM_EDITOR_ROLE = 'EDITOR'
export const SHOWROOM_SUPERVISOR_ROLE = 'DEPARTMENT_SUPERVISOR'
export const SHOWROOM_GAOXIN_ROLE = 'GAOXIN_APPROVER'
export const SHOWROOM_FRONTSTAGE_VIEWER_ROLE = 'FRONTSTAGE_VIEWER'

export const SHOWROOM_FIXED_ROLE_MODEL = Object.freeze([
  SHOWROOM_EDITOR_ROLE,
  SHOWROOM_SUPERVISOR_ROLE,
  SHOWROOM_GAOXIN_ROLE,
  SHOWROOM_FRONTSTAGE_VIEWER_ROLE
])

export const SHOWROOM_APPROVAL_ROUTE = Object.freeze([
  SHOWROOM_EDITOR_ROLE,
  SHOWROOM_SUPERVISOR_ROLE,
  SHOWROOM_GAOXIN_ROLE
])
