package cn.iocoder.yudao.module.dcc.signature.service.csv;

public enum SignatureGovernanceCsvBlockerCode {

    QUALITY_OWNER_MISSING,
    URS_MISSING,
    FRS_MISSING,
    RISK_ASSESSMENT_MISSING,
    IQ_MISSING,
    OQ_MISSING,
    PQ_MISSING,
    TRACE_MATRIX_MISSING,
    ELECTRONIC_SIGNATURE_SOP_MISSING,
    EVIDENCE_INDEX_MISSING,
    QUALITY_MATERIAL_INCOMPLETE,
    QUALITY_MATERIAL_NOT_APPROVED,
    TRACE_RELATION_MISSING,
    TRAINING_RECORD_MISSING,
    CHANGE_CONTROL_MISSING,
    QA_APPROVAL_MISSING,
    RECOVERY_EVIDENCE_MISSING
}
